### PR TITLE
[#950] Use surge as netlify alternative (testing, WIP)

### LINKED ISSUE #950: Find a netlify alternative
Netlify is implementing a limit of 300 build minutes per month; it may not be sufficient for RepoSense as we have been using it as a PR review tool.
Hence, we might need to look out for an alternative.

https://www.netlify.com/pricing/#features

### PR DESCRIPTION
**Pull request by jamessspanggg**
Fixes #950 

```
Netlify's build quota is not enough for RepoSense's build usage.
```

### CODE REVIEW

**Comment by jamessspanggg** [comment]
@eugenepeh In order to run deploy to surge, would need your help to:

1. Use your email to create a surge token (using `surge token`, need to install surge prior)
2. In Travis environment variables for RepoSense, set `SURGE_LOGIN` as your email and `SURGE_TOKEN` as the token generated in step 1.

**Comment by eugenepeh** [comment]
@jamessspanggg what are the rights needed for the `GITHUB_API_TOKEN` ?

**Comment by jamessspanggg** [comment]
@eugenepeh did you set the `SURGE_LOGIN` and `SURGE_TOKEN` in Travis?

Because the email i.e. `SURGE_LOGIN` is not found when running the script.
Screen Shot 2020-02-27 at 11 17 41 AM

More details on setting up `SURGE_LOGIN` and `SURGE_TOKEN`:
Screen Shot 2020-02-27 at 11 22 56 AM

**Comment by eugenepeh** [comment]
>@eugenepeh did you set the SURGE_LOGIN and SURGE_TOKEN in Travis?

Yes I did

**Comment by jamessspanggg** [comment]
@eugenepeh hmmm then it should work. Currently, with the same code, the team's repo seems to be unable to detect the surge email provided in `SURGE_LOGIN`, while my forked repo works perfectly fine.

Travis build for my forked repo:
Screen Shot 2020-02-29 at 12 19 46 AM

Travis build for team's repo:
Screen Shot 2020-02-29 at 12 19 58 AM

I'm still very new to deploying stuffs, but would it be due to some permission settings in GitHub/Travis?

**Comment by eugenepeh** [comment]
>@eugenepeh hmmm then it should work. Currently, with the same code, the team's repo seems to be unable to detect the surge email provided in SURGE_LOGIN, while my forked repo works perfectly fine.

Yes, i noticed. If `SURGE_LOGIN` is not provided, will your fork be stuck at the email: dialogue too?

**Comment by jamessspanggg** [comment]
@eugenepeh removed both `SURGE_LOGIN` and `SURGE_TOKEN` and the fork is stuck on the dialogue:

Screen Shot 2020-02-29 at 12 50 43 AM

**Comment by eugenepeh** [comment]
I see, just realized that the protected vars are not enabled to pull req from fork, going to merge your PR into surge and have it merge to master from there

**Comment by eugenepeh** [comment]
@jamessspanggg please open a PR to merge surge into master

**Comment by jamessspanggg** [comment]
> @jamessspanggg please open a PR to merge surge branch into master

noted

**Pull request merged**
