### PR TITLE
[#1037] Add word-wrap break-word to error box

### LINKED ISSUE #1037: Summary Page: Error message extends out of red box if box is too thin
image

The issue happens when the right panel is shortened too much.

### PR DESCRIPTION
**Pull request by ccyccyccy**
Fixes #1037 
```
The error message appears outside of the red error box when the word is
too long, and the red box is too thin.

We should fit the entire message into the red box, while still allowing
users to view the full message.

Let's use overflow: auto for the error message box CSS.
```

### CODE REVIEW

**Comment by ccyccyccy** [comment]
@eugenepeh Thanks for the suggestion. I changed it to use `overflow: auto` so that users can scroll to view the entire message instead of having it all mangled up.

**Comment by eugenepeh** [comment]
>@eugenepeh Thanks for the suggestion. I changed it to use overflow: auto so that users can scroll to view the entire message instead of having it all mangled 

Looks good but I think it might look better if we let the overflow happens at panel level (e.g. the summary view), where the error box will have a minimum width to fit the content, while the summary view will overflow to keep the full error box in view.

Something like that instead
image

But you might need to put in more work to ensure that a gap (between error box and end of the ramp chart) like this doesn't happen
image

**Comment by eugenepeh** [comment]
Current solution is good but it somehow creates a chunk of underutilized space, so if you can address this, I am fine with the current solution too.

image

**Comment by Tejas2805** [comment]
@ccyccyccy Any update on this?

**Comment by Tejas2805** [comment]
@ccyccyccy What's the update on this. Maybe you can look into #1008 regarding overflow and try to solve this issue.

**Comment by ccyccyccy** [comment]
I'm trying to make the overflow happen at a panel level, but facing troubles getting the CSS to work.

> Maybe you can look into #1008 regarding overflow and try to solve this issue.

Will take a look at that.

**Comment by fzdy1914** [comment]
Closing this PR because it has been inactive for a very long time. For the contributors who are willing to take over, you may just use the code here as a start point.

**Pull request closed without merging**
