### PR TITLE
[On Hold] Modification to parser to support newer specs #135

### PR DESCRIPTION
**Pull request by yong24s**
Part of #135

```
Generate the entire report takes time, hence we should reduce the
time of sub-sequence build by doing it incrementally.

To support incremental report build in a OOP fasion, subcommands
are used for separation of concerns. This way, we do not need to
maintain the mutual exclusiveness between mandatory arguments and
we can show specific help pages per subcommand.

Let's add subcommands to ArgsParser to support incremental report
build.
```
Depends on #165

### CODE REVIEW

**Comment by yong24s** [comment]
PR is not polished yet.

If usage of subparsers is allowed, then please update build command by adding ```run``` as shown the below.

```
Build command
mkdir output && ./gradlew clean build && ./gradlew run -Dargs="run -config sample.csv -output output"
```

**Comment by eugenepeh** [comment]
@yong24s problem is, is it intuitive enough for user to know how to show the sub command list?
Also, date range parameter is pointless in incremental build.

The thing is, if you don't have much distinction between "once" and "incremental", you don't need to have mutual exclusiveness. Since "once" is just the very first execution of "incremental", and "incremental" is just looking for artifacts left behind from "once" to save some work.

**Comment by yong24s** [comment]
@eugenepeh Please reopen, I think GitHub auto closed it?

**Comment by yong24s** [comment]
@eugenepeh @yamidark 
PR ready for comment.

**Comment by eugenepeh** [comment]
Closing this as this feature has already been added

**Pull request closed without merging**
