### PR TITLE
[#1377] DG: minor improvement to `Setting Up` section

### LINKED ISSUE #1377: Minor improvement to consistency and readability of Developer Guide section
**What problem(s) did you run into that caused you to request additional documentation? What, if any, existing documentation relates to this proposal?**

A minor improvement to the **Setting Up** section in the Developer Guide would allow the setting up process to be more seamless.

**What would you like added or modified in the documentation?**
For each bullet point, include a tip to find out the version of each prerequisite from the OS terminal. 

Suggestions:
- Type `java --version` on your OS terminal and ensure that you have the correct version of **JDK**.
- Type `npm -v` on your OS terminal and ensure that you have the correct version of **npm**.

image

### PR DESCRIPTION
**Pull request by rolandyuwy**
Fixes #1377 

To allow the setting up process to be more seamless, include a quick tip to find out the version of each prerequisite from the OS terminal.

Proposed commit message:

```
In the Setting Up section of the Developer Guide,
a hint is provided for checking the version of git,
but not for JDK or npm.

Let's provide hints for JDK and npm as well.

### CODE REVIEW

**Comment by damithc** [comment]
I think the proposed commit message can be shorter. Something along these lines.
```
In the .... a hint is provided for x but not for y and z.

Let's provide hints for y and z as well.
```

**Review by Tejas2805 — APPROVED** [review]
LGTM!

**Review by fzdy1914 — CHANGES_REQUESTED** [review]
@rolandyuwy Can u modify the proposed message as pointed out by Prof?

**Comment by rolandyuwy** [comment]
> @rolandyuwy Can u modify the proposed message as pointed out by Prof?

Changes to the proposed message have been made. Thank you!

**Review by jamessspanggg — APPROVED** [review]

**Review by fzdy1914 — APPROVED** [review]

**Pull request merged**
