### PR TITLE
Remove Codecov robot comment

### PR DESCRIPTION
**Pull request by fzdy1914**
Codecov robot will post comments in each PR reporting the coverage diff
of the current PR.

The coverage is already clear in the PR status. This creates unnecessary noise. 

Let's unable Codecov robot by adding codecov.yml.

### CODE REVIEW

**Comment by damithc** [comment]
The spam comment still seems to happen though.

**Comment by fzdy1914** [comment]
> The spam comment still seems to happen though.

I am looking into it.

**Comment by fzdy1914** [comment]
Some of Pr still have a comment because they haven't merged the latest master yet.

**Comment by damithc** [comment]
> Some of Pr still have a comment because they haven't merged the latest master yet.

I see. Thanks for checking.

**Comment by fzdy1914** [comment]
> > Some of Pr still have a comment because they haven't merged the latest master yet.
> 
> I see. Thanks for checking.

We can wait to see if there is a comment in the newly created PR.

**Pull request merged**
