### PR TITLE
[#1928] Fix tooltip zIndex such that it doesn't occlude next file title

### LINKED ISSUE #1928: Tooltip of the collapse button occludes the next file title
### Tell us about your environment

* **RepoSense Version:** master
* **OS and Version:** Windows 10
* **Web Browser and Version (if applicable):** Edge

### Please include the steps to reproduce the bug.

1. Open the [report](https://dashboard-1860-pr-reposense-reposense.surge.sh/?search=&sort=groupTitle&sortWithin=title&since=2017-10-09&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=false)
1. Open the authorship contribution panel of the first repository
image
1. On the right panel, keep the content of `config/checkstyle/checkstyle.xml` open while scrolling to the end of its content. Hover the mouse on the collapse button on the pinned title.

### What was expected to happen?

The tooltip does not occlude the next file title.

### What actually happened? Please include a screenshot of the output.

The tooltip occludes the next file title.

image

### If possible, include the URL to your RepoSense report or log files (if any).

https://dashboard-1860-pr-reposense-reposense.surge.sh/?search=&sort=groupTitle&sortWithin=title&since=2017-10-09&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=false

### PR DESCRIPTION
**Pull request by pratham31012002**
Fixes #1928 

### Proposed commit message

```
Currently, if one hovers over a tooltip of the pinned title of
a file whose content is scrolled almost completely, such that 
the title of the next file is just below the pinned title, the 
tooltip is not displayed appropriately, as the title of the next 
file obstructs it.

Let's fix this issue.
```

### Other information

This PR should be merged after #2056 is merged.

Previously:
image

After fix:
image

This issue was happening because `title` had `position` as `sticky`, and `tooltip-text` is a child of `title`, which affected the `z-index` stacking order of elements, and hence `z-index` of `tooltip-text` couldn't exceed the `z-index` of `title`. To fix this, we change the `z-index` of the `title`, whenever we hover over a tooltip in that `title`, and set the `title`'s `z-index` to `max-value` defined in `_z-indices.scss`.

### CODE REVIEW

**Comment by pratham31012002** [comment]
The `codecove/project` check, and `Continuous Integration / windows-2022 JDK 8` check is failing, I don't seem to understand why. Could anyone help with this / rerun the jobs?

**Comment by chan-j-d** [comment]
Hi @pratham31012002, I've resolved the issue. It was a problem of codecov randomly failing on the Windows-2022 run which caused both it and the codecov/project to fail this time round.

**Comment by pratham31012002** [comment]
> Hi @pratham31012002, I've resolved the issue. It was a problem of codecov randomly failing on the Windows-2022 run which caused both it and the codecov/project to fail this time round. 

Okay thank you👍

**Comment by pratham31012002** [comment]
Kindly requesting your attention to review this pending PR at your earliest convenience.

**Review by ckcherry23 — APPROVED** [review]
Thanks for fixing this!

**Comment by pratham31012002** [comment]
Kindly requesting your attention to review this pending PR at your earliest convenience.

**Review by MarcusTXK — APPROVED** [review]
LGTM, great job!

**Comment by chan-j-d** [comment]
Hi @pratham31012002, apologies for the slow response. Could you resolve the merge conflicts now that #2056 is merged

**Comment by chan-j-d** [comment]
Hi @pratham31012002, could you take a look at the failing frontend tests? `chartView/chartView_zoomFeature.cy.js` appears to be failing for the changing righthand and/or lefthand boundary tests

**Comment by pratham31012002** [comment]
> Hi @pratham31012002, could you take a look at the failing frontend tests? `chartView/chartView_zoomFeature.cy.js` appears to be failing for the changing righthand and/or lefthand boundary tests

Yeah I am looking into it, it's weird because the CI was passing initially.

**Comment by pratham31012002** [comment]
Locally, the test case passes for me, Could you rerun the job?

image

**Comment by chan-j-d** [comment]
@pratham31012002 the frontend tests fails for several consecutive runs. I'm not too familiar with Cypress configurations but the cypress actual results are quite consistent. do you have any insights?
image

**Comment by pratham31012002** [comment]
The issue seems to be a recurring one, a month ago, a seemingly exact same issue was fixed by just changing the expected and actual values and point of clicking ([here](https://github.com/reposense/RepoSense/pull/2047)), shall I proceed to fix this in a similar way?


Tagging the developers involved in #2047 for more insights @jq1836 , @ckcherry23

**Comment by pratham31012002** [comment]
I have fixed the cypress tests.

I tried to play around with the boundary points of the zoom feature in the chart view to understand why the test cases were failing. Based on my understanding I came to the following conclusion:

For test `changing the righthand boundary`, the right boundary point chosen was (185, 20). This point seems to be in between commits `[2020-05-23] [#1241] Restore checked file types (#1256): +14 -1 lines`(a) and `[2020-09-27] Add optional check for quotes in diff file regex (#1330): +1 -1 lines`(b).

However, it seems that (185, 20) is very close to the commit (b), and hence, the behaviour of the test case is slightly undeterministic (choosing this range sometimes includes (b) and sometimes doesn't include (b)), and hence it passes on my local machine but CI fails.

Between commit (a) and commit (b), there is a substantial gap (approximately 4 months), hence, we can choose a much conservative boundary point to ensure that the test case passes deterministically. Hence, I changed the boundary point to (170, 20).

SImilar arguments for the other 2 test cases.

Note that a month ago, a seemingly same issue was reported [here](https://github.com/reposense/RepoSense/issues/2045), and the same approach was used to fix it [here](https://github.com/reposense/RepoSense/pull/2047).

**Comment by chan-j-d** [comment]
Thanks so much for the investigation. Very nice work. I wonder if there might be some underlying resolution dependent issue. Would it be possible to note your findings down in an issue and reference the previous one as well? This seems like something we might want to note down and if it occurs again, we will probably have to identify the proper cause as to why it can pass locally but fail on GitHub Actions. 

Also note that for the commit message, we enforce a maximum of 72 char per line for easy mobile reading. I've updated it for you here but do note for future contributions. 

Again, thanks for much for fixing this!

**Comment by pratham31012002** [comment]
Will do, and noted.

**Pull request merged**
