### PR TITLE
[#1073] Use ES6+ way for string interpolation

### LINKED ISSUE #1073: Use ES6+ way for string interpolation
In the front end pug files, strings are concatenated with variables using the `+` operator. This might be messy for lines with a lot of variables concatenated together. Let's use ES6's way for string interpolation: title="\`${fileType}: ${user.fileTypeContribution[fileType]} lines, ...\`"

https://github.com/reposense/RepoSense/blob/61f1fc4f4f854a176ab1f6672f6759c42712c9c3/frontend/src/index.pug#L267-L269

### PR DESCRIPTION
**Pull request by calvintanwj**
Fixes #1073

## Proposed commit message

```
There are several .vue files that use string concatenation instead.

This is rather messy for lines with a lot of variables concatenated
together. Opting for string interpolation improves code readability.

Let's use ES6's way of string interpolation for such files.
```

### CODE REVIEW

**Review by yhtMinceraft1010X — DISMISSED** [review]
Nice work on the existing files.

There are a few more lines in api.js that can also be changed to use interpolation:
https://github.com/reposense/RepoSense/blob/f80e94493eac2eb3ae5abc87986823b944516bbc/frontend/src/utils/api.js#L129-L132

https://github.com/reposense/RepoSense/blob/f80e94493eac2eb3ae5abc87986823b944516bbc/frontend/src/utils/api.js#L146-L170

**Comment by HCY123902** [comment]
There are actually several other places for interpolation in the js and vue scripts.

https://github.com/reposense/RepoSense/blob/f80e94493eac2eb3ae5abc87986823b944516bbc/frontend/src/utils/repo-sorter.js#L59

https://github.com/reposense/RepoSense/blob/f80e94493eac2eb3ae5abc87986823b944516bbc/frontend/src/utils/safari_date.js#L43

https://github.com/reposense/RepoSense/blob/f80e94493eac2eb3ae5abc87986823b944516bbc/frontend/src/utils/safari_date.js#L45

https://github.com/reposense/RepoSense/blob/f80e94493eac2eb3ae5abc87986823b944516bbc/frontend/src/app.vue#L126

https://github.com/reposense/RepoSense/blob/f80e94493eac2eb3ae5abc87986823b944516bbc/frontend/src/views/c-summary.vue#L297

https://github.com/reposense/RepoSense/blob/f80e94493eac2eb3ae5abc87986823b944516bbc/frontend/src/views/c-authorship.vue#L88

https://github.com/reposense/RepoSense/blob/f80e94493eac2eb3ae5abc87986823b944516bbc/frontend/src/views/c-authorship.vue#L95

You can take a look when you have the time

**Review by HCY123902 — CHANGES_REQUESTED** [review]
There are actually several other places for interpolation in the js and vue scripts.

https://github.com/reposense/RepoSense/blob/f80e94493eac2eb3ae5abc87986823b944516bbc/frontend/src/utils/repo-sorter.js#L59

https://github.com/reposense/RepoSense/blob/f80e94493eac2eb3ae5abc87986823b944516bbc/frontend/src/utils/safari_date.js#L43

https://github.com/reposense/RepoSense/blob/f80e94493eac2eb3ae5abc87986823b944516bbc/frontend/src/utils/safari_date.js#L45

https://github.com/reposense/RepoSense/blob/f80e94493eac2eb3ae5abc87986823b944516bbc/frontend/src/app.vue#L127

https://github.com/reposense/RepoSense/blob/f80e94493eac2eb3ae5abc87986823b944516bbc/frontend/src/views/c-summary.vue#L297

https://github.com/reposense/RepoSense/blob/f80e94493eac2eb3ae5abc87986823b944516bbc/frontend/src/views/c-authorship.vue#L88

https://github.com/reposense/RepoSense/blob/f80e94493eac2eb3ae5abc87986823b944516bbc/frontend/src/views/c-authorship.vue#L95

You can take a look when you have the time

**Review by HCY123902 — APPROVED** [review]

**Comment by HCY123902** [comment]
It seems that there is a change that breaks the single quote eslint style rule. Can you take a look

**Review by dcshzj — APPROVED** [review]
LGTM!

**Pull request merged**
