### PR TITLE
[#1575] Fix misidentification of deleted files as edited files

### LINKED ISSUE #1575: Analysis of edited files misidentifies deleted files
**Tell us about your environment**

* **RepoSense Version:** master branch
* **OS and Version:** Windows 10
* **Web Browser and Version (if applicable):** N.A.

**Please include the steps to reproduce the bug.**

1. Add the following 2 println statements to the `FileInfoExtractor` beginning at line 116. (Or any means of viewing the value of `filePath` at these lines).
image

1. Run RepoSense on intellij with the following arguments: `--repos https://github.com/reposense/RepoSense.git --since 31/12/2018`

**What was expected to happen?**
Output contains lines with `DELETED-FILE: /dev/null`

**What actually happened? Please include a screenshot of the output.**
Output contains lines with `INVALID-TEXT-FILE: dev/null`
image

**If possible, include the URL to your RepoSense report or log files (if any).**

### PR DESCRIPTION
**Pull request by chan-j-d**
Fixes #1575 

A normal file path looks like `+++ b/file/path/` while a deleted file shows up as `+++ /dev/null/`

The current regex will instead parse out the string `dev/null` without the initial slash for deleted files and attempt to match it to `/dev/null/`.

This change has no direct impact on the output of the program at the moment as the relevant lines of code (linked below) has an additional `if` statement where the `dev/null` filepaths are discarded unintentionally. However, if there is a change in the program flow then it might become an issue in the future.
https://github.com/reposense/RepoSense/blob/6b94f82545bbd84852f7bd110af72e495ad23652/src/main/java/reposense/authorship/FileInfoExtractor.java#L114-L121

Commit message:
```
Current regex expression matches dev/null/ while the variable is
/dev/null/. This causes files to be wrongly treated as being edited
instead of being deleted.

Let's fix the misidentification of deleted files.
```

### CODE REVIEW

**Comment by chan-j-d** [comment]
Ready for review.

**Comment by HCY123902** [comment]
Hello, thanks for the contribution. Can you link it to a corresponding issue? In particular, can you reproduce the problems caused by the misidentification of deleted files in the issue

**Comment by chan-j-d** [comment]
Hi @HCY123902, I have created issue #1575 to demonstrate the faulty logic with the current `if` statements.

**Review by HCY123902 — APPROVED** [review]

**Review by dcshzj — APPROVED** [review]
LGTM! I was initially confused by your PR description, so I wanted to add on to it (feel free to correct me if I interpret it incorrectly).

The file path regex matcher that we currently use is given as follows;
https://github.com/reposense/RepoSense/blob/6b94f82545bbd84852f7bd110af72e495ad23652/src/main/java/reposense/authorship/FileInfoExtractor.java#L49

However, the part of the regex `b?/(?<filePath>.*)\n` causes the initial forward slash to be stripped when the pattern matching is performed here:
https://github.com/reposense/RepoSense/blob/6b94f82545bbd84852f7bd110af72e495ad23652/src/main/java/reposense/authorship/FileInfoExtractor.java#L105

This meant that by the following line, the `filePath` would be `dev/null`, as the original match line will say `+++ /dev/null`.
https://github.com/reposense/RepoSense/blob/6b94f82545bbd84852f7bd110af72e495ad23652/src/main/java/reposense/authorship/FileInfoExtractor.java#L112

Hence, there is a need to change the `FILE_DELETED_SYMBOL` to remove the leading forward slash, so that it can correctly match deleted files.

**Review by fzdy1914 — APPROVED** [review]

**Pull request merged**
