### PR TITLE
[#2011] Fix bugs in UG

### LINKED ISSUE #2011: Documentation links to config files don't work
### Please include the steps to reproduce the bug.

1. Under the FAQ section of the UG, all the existing links to the config files do not work
    when pressed. https://reposense.org/ug/faq.html

### What was expected to happen?
It should direct the user to the config files section in the UG.

### What actually happened? Please include a screenshot of the output.
The user remains on the same page

### PR DESCRIPTION
**Pull request by nseah21**
Fixes #2011

### Fix bugs in UG

```
Some of the links in the FAQ and troubleshooting
sections of the UG are not working. Some embedded 
content is also not being rendered correctly.

Let's update the links and fix the embedded content.
```

### Other information

NA

### CODE REVIEW

**Comment by ckcherry23** [comment]
Thanks for fixing the broken links @nseah21! 

I just have a minor comment about the commit message. Each line in it should be under 72 characters. 
(You can read more about what we follow in the [SE-EDU guidelines for submitting a PR](https://se-education.org/guides/guidelines/PRs.html#submitting-a-pr).)

**Review by ckcherry23 — CHANGES_REQUESTED** [review]
Thanks for fixing the broken links @nseah21! 

I just have a minor comment about the commit message. Each line in it should be under 72 characters. 
(You can read more about what we follow in the [SE-EDU guidelines for submitting a PR](https://se-education.org/guides/guidelines/PRs.html#submitting-a-pr).)

**Comment by nseah21** [comment]
Thank you for the reminder @ckcherry23. I have updated the commit message accordingly.

**Review by ckcherry23 — APPROVED** [review]

**Comment by gok99** [comment]
Thanks for catching these @nseah21

It looks like some links in the `Troubleshooting` appendix are also broken - could you do a quick look around the other sections and get them fixed here too?

**Comment by nseah21** [comment]
Thank you for pointing them out, @gok99. 

I have fixed the broken links, as well as some other minor UG bugs in `troubleshooting.md` and `withTravis.md`.

**Comment by gok99** [comment]
Thanks! Could you also update the PR title and commit message?

**Review by gok99 — APPROVED** [review]
LGTM!

**Pull request merged**
