### PR TITLE
[#1872] Update Node version to 18

### LINKED ISSUE #1872: Frontend DevOps: Upgrade Node to 16 then 18
**What feature(s) would you like to see in RepoSense?**

Node 14 will reach [end-of-life](https://github.com/nodejs/release#release-schedule) on 30 April 2023. Although Node 16's EOL would usually be 1 year later, it has been pushed forward to 11 September 2023 since OpenSSL 1.1.1 is also [no longer supported](https://nodejs.org/en/blog/announcements/nodejs16-eol/) on the same day.

**If possible, describe the solution**

The Node version needs to be updated in `build.gradle` as well as our workflows under the `.github` directory.

Suggested upgrade step:

1. Upgrade to Node 16 before 30 April 2023. 
2. Upgrade to Node 18 before 11 September 2023

The rationale for doing this is so that it is easier to resolve any breaking changes.

**Additional context**

You may want to keep #1871 in mind while working on this.

### PR DESCRIPTION
**Pull request by sopa301**
Fixes #1872 

### Proposed commit message
```
Node.js 16 has reached its end-of-life on 11 September 2023.

Let us update Node.js to use Node 18 in the GitHub workflows.
```

### Other information

The update involved removing the depreciated node-sass.

### CODE REVIEW

**Comment by sopa301** [comment]
Closed because I don't have the required competencies (as of now) to properly fix the issue. Here are some things I learned in the process.

- Updating Node to 18 requires [node-sass](https://www.npmjs.com/package/node-sass) to be updated to at least 8.0
- However, node-sass has been [depreciated](https://sass-lang.com/blog/libsass-is-deprecated/) in favor of dart-sass, which is already used in the project.
- Additionally, node-sass on windows has a few more [requirements](https://stackoverflow.com/questions/46953808/node-sass-installation-issue-on-windows-10) that make it harder to set up.
- Therefore, it would be easier to remove node-sass and use sass exclusively.
- Attempting to do so resulted in a bug similar to #1784

**Comment by ckcherry23** [comment]
Thanks @sopa301 for your detailed investigation regarding the issue and reporting it here! 
We can figure out a fix for this in a future PR.

**Comment by sopa301** [comment]
It's interesting to note #2102 somehow fixed the bug mentioned above.

**Review by ckcherry23 — APPROVED** [review]
LGTM!

**Review by vvidday — APPROVED** [review]
Thanks for your work on this @sopa301, can you look into resolving the merge conflict?

**Comment by sopa301** [comment]
@vvidday Updated!

**Comment by vvidday** [comment]
> @vvidday Updated!

thanks! :)

**Pull request merged**
