### PR TITLE
[#1284] Adjust the design documentation

### LINKED ISSUE #1284: Update design documentation
To be done after merging #1281 

See @fzdy1914 's comments for #1281 for some areas to improve

### PR DESCRIPTION
**Pull request by HCY123902**
Resolves #1284
Commit message:
```
Add the documentation for v_resizer.js and adjust
the documentation of api.js

There seems to be some deviation between the
implementation and documentation of api.js. The
documentation of v_resizer.js also seems to be missing.

Adjusting the existing documentation may make it more
consistent with the current implementation.

Lets's adjust the documentation of api.js and add the
documentation for v_resizer.js.
```

I did not split this PR into 2 separate ones because the problems mentioned above is included in a single issue.

### CODE REVIEW

**Comment by Tejas2805** [comment]
Not too sure but I think there are changes required in the diagram too if I am correct. @fzdy1914 Your opinion?

**Comment by fzdy1914** [comment]
Let's edit this documentation after the whole morphing of frontend code first. It is kind of acceptable now.

**Comment by HCY123902** [comment]
Sure, no problem

**Comment by HCY123902** [comment]
This pull request is ongoing and it will adapt to the change in implementation

**Pull request closed without merging**
