### PR TITLE
[#2109] Add search by tag functionality

### LINKED ISSUE #2109: Give a way to find repos with a specific tag
Suggestion: enhance the search feature to find repos with a specific tag e.g, `tag:A-JUnit`
image

This is a niche use case but could be useful for courses such as CS2103, for students/instructors to easily find repos which has a specific tag

Not sure how hard it is to implement though.

### PR DESCRIPTION
**Pull request by jonasongg**
Fixes #2109

### Proposed commit message

```
Add search by tag functionality

It can be useful to search author/repos by git tags.

Let's add this functionality to make it easier to filter by tags. This
commit also fixes a bug that existed in a previous version of the
feature which resulted in all users being shown to belong to same group.
```

### CODE REVIEW

**Review by sopa301 — APPROVED** [review]
LGTM! I realised that the bug may be caused by my comment in the original PR suggesting to move the `full.push(res)` statement block out of the if-else statement (oops).

I think the `getFilteredRepos` method should probably be refactored sometime soon though, since there are some lines going up to 5(!) levels of indentation. In another PR maybe?

**Review by vvidday — APPROVED** [review]
Thanks @jonasongg - can I confirm that we can't add a test for the bug in #2164 due to our testing report only containing one group?

**Comment by vvidday** [comment]
> I think the `getFilteredRepos` method should probably be refactored sometime soon though, since there are some lines going up to 5(!) levels of indentation. In another PR maybe?

@sopa301 Great point, I agree that it could be refactored to increase readability - feel free to file an issue for this!

**Review by ckcherry23 — APPROVED** [review]
LGTM, thanks for fixing the bug @jonasongg! 

Regarding the regression, I think we can file a new issue to add more repos to our Cypress setup and implement tests so that this doesn't happen again.

**Comment by jonasongg** [comment]
@vvidday Sorry for the late response, but yes, it's because our testing config contains only one repo. I will be creating an issue to add more repos soon!

**Pull request merged**
