### PR TITLE
Sort order name: rename from Team to Repo/Branch #30

### LINKED ISSUE #30: Sort order: team name --> repo
It's more accurate to say sort by `Repo` ?

### PR DESCRIPTION
**Pull request by hzf1174**
As mentioned in #30, the sorting behavior now looks like sorting by the Repo/Branch name instead of the Team name. 

Using the term `Team` may cause confusion to users. Renaming to `Repo/Branch` can also keep consistent with `group by repo/branch`.

Let's rename the sort order name from `Team` to `Repo/Branch`.

### CODE REVIEW

**Comment by hzf1174** [comment]
@reposense/devs Ready for review.

**Comment by hzf1174** [comment]
@reposense/devs Changes are made. Ready for review.

**Comment by damithc** [comment]
> 😕 Repo isn't correct either because we don't group 2 different branches of the same repo together. I think we should probably retain it as team unless there's a better proposition.
> @damithc your opinion on this?

That's true. `Repo/Branch`?

**Comment by eugenepeh** [comment]
>That's true. Repo/Branch?

Sounds good to me. @hzf1174 please proceed with that.

Also, for the `group by repo` check box, can we have it relabeled correspondingly as well?

**Comment by hzf1174** [comment]
> > That's true. Repo/Branch?
> 
> Sounds good to me. @hzf1174 please proceed with that.
> 
> Also, for the `group by repo` check box, can we have it relabeled correspondingly as well?

so we use `group by repo/branch` right?

**Comment by eugenepeh** [comment]
> so we use group by repo/branch right?

yup

**Comment by hzf1174** [comment]
Hi @eugenepeh, changes are made. Ready for review.

**Comment by eugenepeh** [comment]
Nits to the proposed message:

```
In our tool bar, we use the term `Team` to define the group of authors
that from the same repository and branch. 

However, the use of this term can cause confusion to users as it is not
a common terminology among the Git users.

To improve the clarity of our selectable options, let's rename the word
Team to Repo/Branch.

**Pull request merged**
