### PR TITLE
Change header style for GitHub Issue and PR Templates

### PR DESCRIPTION
**Pull request by yhtMinceraft1010X**
## Proposed commit message

```
The current header style of bolding for issue templates is difficult to 
notice compared to the body text. The level 2 header for pull request
template is too large.

Let's update both to use level 3 headings.
```

## For PRs:

#1896 provides a preview of what level 3 headers would look like.

### CODE REVIEW

**Comment by dcshzj** [comment]
My personal preference is to use the 3rd level heading instead. I think the 2nd level might be too large, especially since the header is a little wordy. What do you/the others think?

**Review by HCY123902 — COMMENTED** [review]
I agree with the third level heading as well

**Comment by yhtMinceraft1010X** [comment]
> I agree with the third level heading as well

In this case, should we change to third level heading for the pull request template? I took reference from that when changing the header for the issue templates.

**Comment by HCY123902** [comment]
> > I agree with the third level heading as well
> 
> In this case, should we change to third level heading for the pull request template? I took reference from that when changing the header for the issue templates.

@dcshzj Can I ask for your opinion on this

**Comment by dcshzj** [comment]
No strong opinions from me, I think 3rd-level is fine too.

**Review by HCY123902 — APPROVED** [review]

**Review by chan-j-d — APPROVED** [review]
LGTM!

**Pull request merged**
