### PR TITLE
[#960] Refactor Ramp css

### PR DESCRIPTION
**Pull request by Tejas2805**
Fixes part of #960 

```
The JS/HTML code of each component has already rested in its 
own file, but all the CSS are in one file. 

Let's refactor the Ramp CSS into a new file for better 
scalability and readability.
```

### CODE REVIEW

**Comment by jamessspanggg** [comment]
Can you re-fork the RepoSense team repo? It seems like you committed directly to your master branch and there's a lot of unrelated commits

**Comment by 0blivious** [comment]
Actually the problem here is you should branch at a specific commit, which is the latest commit in the master branch of this Reposense repo.

**Comment by Tejas2805** [comment]
@jamessspanggg Have corrected it. Can you review it now? It will be okay from my future PRs.

**Comment by jamessspanggg** [comment]
Hmm seems like there's still an unrelated commit

Screen Shot 2020-02-06 at 6 04 36 PM

**Comment by Tejas2805** [comment]
Can’t seem to get rid of it.

**Comment by fzdy1914** [comment]
You can use `rebase -i`  to squash all the commit in to one, and then force push the branch.

**Comment by Tejas2805** [comment]
> You can use `rebase -i` to squash all the commit in to one, and then force push the branch.
 Thanks for guiding. Have done the needful

**Comment by jamessspanggg** [comment]
Yep looks good now!

**Comment by Tejas2805** [comment]
@fzdy1914 @jylee-git For your review

**Comment by Tejas2805** [comment]
@fzdy1914 Any update rquired?

**Pull request merged**
