### PR TITLE
[#1097][#929][#1002]: Remove unused code

### LINKED ISSUE #929: FileUtil: `attachJsPrefix` method is not used anywhere
There appears to be an unused method in the `FileUtil` class.

image

Based on some preliminary searching using `git blame`, I think it was first introduced in [this PR](https://github.com/reposense/RepoSense/pull/1/files) and it was not used after [this PR](https://github.com/reposense/RepoSense/pull/111/files). 

Does anyone know more about it? Should it be removed?

### LINKED ISSUE #1002: LogsManager: `setConsoleHandlerLevel` and `setFileConsoleHandlerLevel` methods are not used anywhere
Relevant code snippet: 

https://github.com/reposense/RepoSense/blob/74ac22a3848f1009bab31d3ecb865c00f227e71e/src/main/java/reposense/system/LogsManager.java#L136-L142

These methods were added in this [pull request](https://github.com/reposense/RepoSense/pull/123).

To me, it seems these can be safely removed. Does anyone have more information?

### LINKED ISSUE #1097: RepoLocation: `convertStringsToLocations` method is unused
The method `convertStringsToLocations` is not used in the codebase.

It was introduced in [this PR](https://github.com/reposense/RepoSense/pull/425).

https://github.com/reposense/RepoSense/blob/cd9e636fec6c7919fc50ed040da195e699760fa3/src/main/java/reposense/model/RepoLocation.java#L109-L126

Let's decide if this method should be kept?

### PR DESCRIPTION
**Pull request by yash-chowdhary**
Fixes #1097 
Fixes #929
Fixes #1002
```
There are instances of unused code across the
files RepoLocation.java, LogsManager.java and 
FileUtil.java.

Let's remove them.
```

### CODE REVIEW

**Comment by anubh-v** [comment]
Thanks for the PR @yash-chowdhary 
I think we can also address [issue 929](https://github.com/reposense/RepoSense/issues/929) in this PR, as it also involves another unused method.

**Comment by anubh-v** [comment]
I suggest we also tackle #1002 here

**Comment by anubh-v** [comment]
The deletions are ok.
@yash-chowdhary, could you include the names of the classes with unused code (RepoLocation, FileUtil, LogsManager) in the proposed commit message?

**Comment by anubh-v** [comment]
Checks on Travis have passed, but the PR doesn't seem to be updated:
image

**Comment by fzdy1914** [comment]
There are instances of unused code across the files 
`RepoLocation.java`, `LogsManager.java` and `FileUtil.java`.

Let's remove them for better code quality.

**Pull request merged**
