### PR TITLE
[#1293] Fix case types in documentation

### LINKED ISSUE #1293: Remaining erros in documentation
Few observations and nits:

1) This should be `report`

Screen Shot 2020-06-20 at 2 10 39 PM

2) This should be `Commits panel`

Screen Shot 2020-06-20 at 2 11 31 PM

3) Let's make it consistent by following the `Step 1` method in `RepoSense with Netlify`

Screen Shot 2020-06-22 at 9 25 48 AM

---

Screen Shot 2020-06-22 at 9 26 02 AM

### PR DESCRIPTION
**Pull request by lm5lm5**
Fixes #1293
```
Some words in the documentation do not follow the same case types.

Let's standardise the case types within the documentation.
```

### CODE REVIEW

**Comment by Tejas2805** [comment]
Hi, thank you for your contribution! Can you please edit your commit message to follow our style guide. You can find it [here](https://reposense.org/RepoSense/dg/styleGuides.html)

**Comment by lm5lm5** [comment]
@Tejas2805 I have edited the commit message. Could you please check? Thank you.

**Comment by lm5lm5** [comment]
I saw that my PR now contains the information about some other PRs, is it because I made some mistake in synchronising the local repo with the remote one?

image

**Comment by jamessspanggg** [comment]
> I saw that my PR now contains the information about some other PRs, is it because I made some mistake in synchronising the local repo with the remote one? Or because I edited the commit message of the commit I made previously?

can you try to pull the latest changes from the master branch, merge to this branch and push again?

**Review by jamessspanggg — APPROVED** [review]
LGTM

**Comment by lm5lm5** [comment]
> > I saw that my PR now contains the information about some other PRs, is it because I made some mistake in synchronising the local repo with the remote one? Or because I edited the commit message of the commit I made previously?
> 
> can you try to pull the latest changes from the master branch, merge to this branch and push again?

I have done so.

**Comment by jamessspanggg** [comment]
Seems like your branch contains some redundant commits, might be some mistake done when merging the branches. 

Not to worry, we will be squashing the commits before merging the PR to the master branch.

**Review by Tejas2805 — APPROVED** [review]
LGTM!

**Comment by fzdy1914** [comment]
Any idea why Travis is not reporting the status back?

**Comment by fzdy1914** [comment]
@lm5lm5 Can you try to login to Travis at least once? See the link here: `https://travis-ci.community/t/some-pr-are-not-analyzed-with-message-abuse-detected/1191`. If it still does not help, you may contact Travis support via e-mail (support@travis-ci.com)

**Comment by lm5lm5** [comment]
> @lm5lm5 Can you try to login to Travis at least once? See the link here: `https://travis-ci.community/t/some-pr-are-not-analyzed-with-message-abuse-detected/1191`. If it still does not help, you may contact Travis support via e-mail ([support@travis-ci.com](mailto:support@travis-ci.com))

I have logged in to Travis. How do I re-trigger Travis build for this PR?

**Comment by lm5lm5** [comment]
I figured out why my previous commits were not linked to my Github account - I didn't change the commit email to my current Github account email. My future commits will be properly linked to my Github account, but I suppose there is no convenient way of changing the author (i.e. email) of my previous commits.
In that case, how about I close my pending PRs and redo the commits from the master branch since not many lines of code were changed in these PRs?

**Comment by lm5lm5** [comment]
Hi @fzdy1914, I have contacted Travis CI support and now my PR can trigger and pass Travis CI check.

**Pull request merged**
