### PR TITLE
Frontend: update Node packages and fix code for checks

### PR DESCRIPTION
**Pull request by yhtMinceraft1010X**
Part of #1703 

## Proposed commit message

```
Many dependencies are not up to date with the latest versions. This
gives rise to vulnerabilities as well as dependency conflicts when
attempting to run npm update.

In addition, there are ESLint checks for Airbnb JS standards which fail
upon updating these dependencies.

Let's update the dependencies and refactor the Javascript code
accordingly.
```

### New argument format for `CopyWebpackPlugin` in `vue.config.js`
With the upgrading of the dependencies, Webpack has been bumped to version 5. In particular, `ignore` is now under `globOptions` as illustrated in [this format](https://webpack.js.org/plugins/copy-webpack-plugin/#ignoring-files):
```
new CopyPlugin({
      patterns: [
        {
          from: "public/**/*",
          globOptions: {
            dot: true,
            gitignore: true,
            ignore: ["**/file.*", "**/ignored-directory/**"],
          },
        },
      ],
    }),
```
The change in `vue.config.js` is to allow `'*.json'` to be passed in through the new method. Otherwise, the original method would result in an error.

### Removal of automatic syntax inference in Stylelint from `v14` onwards
As mentioned in the Stylelint [migration guide for 14](https://stylelint.io/migration-guide/to-14/), Stylelint no longer has support for SCSS and Vue syntaxes. The `.stylelintrc.json` file has to be extended with `stylelint-config-recommended-scss` and `stylelint-config-recommended-vue`, without which errors like these can happen (Some other files that have this error are not shown):

Screenshot (269)

### Additional ESLint checks:
The Javascript code has been updated for the following checks:
* [`no-mixed-operators`](https://eslint.org/docs/rules/no-mixed-operators)
* [`function-paren-newline`](https://eslint.org/docs/rules/function-paren-newline)
* [`no-multiple-empty-lines`](https://eslint.org/docs/rules/no-multiple-empty-lines)

The above 3 checks can be found in the [Airbnb style guide](https://github.com/airbnb/javascript/blob/master/README.md). There is also one more check ([`prefer-object-spread`](https://eslint.org/docs/rules/prefer-object-spread)) that the guide refers to but I am not sure about whether to enable it since the eslint website mentions not to if our code does not support ES2018. An example of a line that fails this check is given below:
https://github.com/reposense/RepoSense/blob/b12d3485d4b7a3aca5f2545404b5545a5277ff5e/frontend/src/views/v-zoom.vue#L177

There are also 2 more checks which I have also disabled because they were not mentioned in the Airbnb guide:
* [`function-call-argument-newline`](https://eslint.org/docs/rules/function-call-argument-newline)
* [`vue/no-computed-properties-in-data`](https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/no-computed-properties-in-data.md)

~~Finally, the `max-len` for `code` is lowered since the [SE-EDU coding standard](https://se-education.org/guides/conventions/javascript.html) specifies a hard limit of 120 characters.~~ This change has been moved to #1766 

### Additional Stylelint checks:
Some new failing checks are currently disabled:
* [`scss/at-import-partial-extension`](https://github.com/stylelint-scss/stylelint-scss/blob/master/src/rules/at-import-partial-extension/README.md)
* [`scss/at-import-no-partial-leading-underscore`](https://github.com/stylelint-scss/stylelint-scss/blob/master/src/rules/at-import-no-partial-leading-underscore/README.md)
* [`scss/no-global-function-names`](https://github.com/stylelint-scss/stylelint-scss/blob/master/src/rules/no-global-function-names/README.md)
* [`function-no-unknown`](https://stylelint.io/user-guide/rules/list/function-no-unknown/)
* [`no-descending-specificity`](https://stylelint.io/user-guide/rules/list/no-descending-specificity/)
* [`selector-type-no-unknown`](https://stylelint.io/user-guide/rules/list/selector-type-no-unknown/)
* [`at-rule-no-unknown`](https://stylelint.io/user-guide/rules/list/at-rule-no-unknown/)
* [`no-duplicate-selectors`](https://stylelint.io/user-guide/rules/list/no-duplicate-selectors/)

All disabled checks are appended at the back of `rules` for both `.eslint.json` and `.stylelintrc.json`. Should we re-enable them (and change the frontend code to ensure that these checks pass)?

### Cypress `package-lock.json`
Running `npm update` in the `cypress` directory (needed to keep Cypress version up to date) updates the `package-lock.json`. Since the `package-lock.json` for the `cypress` directory is tracked on this repo, the change has to be committed here.

## Steps to take after merging
Since the `package-lock.json` file and `node_modules` directory in `frontend` are not tracked on this repo, both have to be deleted and `npm install` should be re-run in the `frontend` working directory so that the latest packages can be installed on your local computers.

### CODE REVIEW

**Comment by gerhean** [comment]
Is it possible to separate the Update Node packages and fix code for checks?

**Comment by yhtMinceraft1010X** [comment]
> Is it possible to separate the Update Node packages and fix code for checks? They are not very related so prefer different PRs.

If this step is taken, the Update Node packages PR will fail CI since some of the ESLint checks only failed after the upgrade (without the code being changed). 

I feel that fixing all the code in a separate PR is pointless since regardless of whether the fixes are applied or not, with the old dependencies, the checks don't seem to fail. The only code change that I can safely move out is the line length change.

**Comment by yhtMinceraft1010X** [comment]
> Hi, We are going to mark this PR as stale because it has been inactive for the past 30 days. If no further activity occurs within the following 7 days, it will be automatically closed so that others can take up the issue. If you are still working on this PR, please make a follow-up commit within 7 days and leave a comment to remove the stale label. Do let us know if you are stuck so that we can help you!'

This PR is still ongoing.

**Review by dcshzj — APPROVED** [review]
LGTM!

**Comment by dcshzj** [comment]
@yhtMinceraft1010X Some of the code might need to be fixed due to the new lint rules

**Comment by yhtMinceraft1010X** [comment]
> @yhtMinceraft1010X Some of the code might need to be fixed due to the new lint rules

While resolving the code, I noticed something about the `indent` rule in `.eslintrc.json`:
https://github.com/reposense/RepoSense/blob/11421c8394bdca3464957d550186715e9a94bf0a/frontend/.eslintrc.json#L22-L35

In lines 26-30, the numbers there actually mean "multiples of the base indentation" according to the [ESLint page on indent](https://eslint.org/docs/latest/rules/indent). Since our base indentation level is 2 spaces, for a `CallExpression` with value of `2`, that would mean the expected indentation level is 2 * 2 = 4 spaces. We may have to change those multiples in lines 26-30.

I tried changing all the multiples to 1 and a lot of code failed the checks. In the interest of moving this PR along, the change in my most recent commit will have 4 spaces indentation in the affected line. Once this PR merges, I will create a new PR to change the indentation multiples.

**Comment by dcshzj** [comment]
@yhtMinceraft1010X I think in the interest of getting the PRs for the IWM students merged first, I will put this change on hold.

**Comment by dcshzj** [comment]
Sorry @yhtMinceraft1010X I should have checked this. It seems like this change caused some differences in the code panel. See below:

**Before ([report link](https://dashboard-1807-pr-reposense-reposense.surge.sh/?search=&sort=groupTitle&sortWithin=title&since=2017-10-09&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=Eugene%20Peh&tabRepo=reposense%2Ftestrepo-Alpha%5Bmaster%5D&authorshipIsMergeGroup=false&authorshipFileTypes=json&authorshipIsBinaryFileTypeChecked=false&authorshipIsIgnoredFilesChecked=false))**

Screenshot 2022-08-07 at 11 45 19

**After ([report link](https://dashboard-1762-pr-reposense-reposense.surge.sh/?search=&sort=groupTitle&sortWithin=title&since=2017-10-09&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=authorship&tabAuthor=Eugene%20Peh&tabRepo=reposense%2Ftestrepo-Alpha%5Bmaster%5D&authorshipIsMergeGroup=false&authorshipFileTypes=json&authorshipIsBinaryFileTypeChecked=false&authorshipIsIgnoredFilesChecked=false))**

Screenshot 2022-08-07 at 11 46 32

Are you able to propose a fix?

**Comment by Zhou-Jiahao-1998** [comment]
@dcshzj I am looking into the issue.

**Pull request merged**
