### PR TITLE
DeveloperGuide: Update gradle command to gradle test systemtest

### PR DESCRIPTION
**Pull request by RonakLakhotia**
Fix [#411](https://github.com/reposense/RepoSense/issues/411)

### CODE REVIEW

**Comment by yamidark** [comment]
Hi @RonakLakhotia,

Thank you for your contribution to RepoSense!

Your PR looks good to me. All that's left now is to construct your merge commit message as specified in our [commit organization](https://oss-generic.github.io/process/docs/FormatsAndConventions.html#commit-message), and you can tag prof for the final review afterwards.

Please follow the following flow:
```
{current situation} -- use present tense

{why it needs to change}

{what is being done about it} -- use imperative mood

{why it is done that way}

{any other relevant info}
```

For your PR here, do reference the previous PR (#306) where we renamed the test command from `functional` -> `systemtest`.

Do use the examples (given in the url) or our past commit messages as reference.

**Comment by RonakLakhotia** [comment]
Fix [#411](https://github.com/reposense/RepoSense/issues/411) and [#306](https://github.com/reposense/RepoSense/pull/306)

```
In Verifying the setup part of Developer Guide, the gradle command 
to run the tests given is gradlew test functional.

However, the command is outdated and the exact command should 
be gradlew test systemtest instead.

Let's rename functional to systemtest instead in the Developer Guide instructions.

```

@damithc @yamidark ready for review

**Comment by RonakLakhotia** [comment]
@eugenepeh updated commit message.

**Comment by eugenepeh** [comment]
@RonakLakhotia , 

I mean adding the #306 into your proposed message itself :P
I will fix it for you for this one,

```
In `Verifying the setup part` of Developer Guide, the gradle command 
to run the tests given is `gradlew test functional`.

However, the functional task in gradlew has been renamed to systemtest
in #306 and therefore the command should be updated to
`gradlew test systemtest` correspondingly.

Let's correct this outdated command in the Developer Guide instructions.
```

**Comment by RonakLakhotia** [comment]
Oh right :P Thanks! 👍

**Pull request merged**
