### PR TITLE
[#1044] Update date hashes on reset date range

### LINKED ISSUE #1044: Reset date range does not update the since and until date hashes
To reproduce: modify the link since/until date url hashes. Reload the page. Click the reset date range button. Reload again to see that the dates are not updated. [link](https://deploy-preview-1008--reposense.netlify.com/#search=&sort=groupTitle&sortWithin=title&since=2017-10-09&timeframe=commit&mergegroup=false&groupSelect=groupByRepos&breakdown=false&until=2019-01-20)

Kapture 2020-02-03 at 0 08 19

### PR DESCRIPTION
**Pull request by ccyccyccy**
Fixes #1044
```
Resetting the date range would occasionally not change the date hashes
in the url, causing a refresh of the page to load the outdated filter
date range. The bug occurs when until or since date is not specified on
generating the report.

Let's make sure that the date hashes gets updated all the time.
```

### CODE REVIEW

**Comment by anubh-v** [comment]
Is this ok for review?

**Comment by ccyccyccy** [comment]
> Is this ok for review?

Yes this is ready for review.

**Comment by fzdy1914** [comment]
@ccyccyccy Can you update the branch, please. Meanwhile, can you tick the `allow the maintainer to edit this branch` when creating new PRs so we can update the branch for you.

**Comment by ccyccyccy** [comment]
> @ccyccyccy Can you update the branch, please. Meanwhile, can you tick the `allow the maintainer to edit this branch` when creating new PRs so we can update the branch for you.

Thanks. Will do in the future. Just updated the branch.

**Pull request merged**
