### PR TITLE
UserGuide.md: update images to the new UI

### PR DESCRIPTION
**Pull request by yamidark**
```
After the UI revamp for v1.1 release, the images of the dashboard
in UserGuide.md is now outdated.

Let's update the images in UserGuide.md to reflect the new dashboard
UI.
```

### CODE REVIEW

**Comment by yamidark** [comment]
@eugenepeh For your review.

**Comment by damithc** [comment]
nit: the `ramp chart` arrow should not point to an individual ramp?

**Comment by yamidark** [comment]
@damithc 
Pointing to the whole bar like this? dashboard

**Comment by damithc** [comment]
> Pointing to the whole bar like this?

Yes, that's better.

**Pull request merged**
