### PR TITLE
[#1912] Add TypeScript rules to ESLint

### LINKED ISSUE #1912: Add TypeScript rules to ESLint
### What feature(s) would you like to see in RepoSense

Currently, our frontend's ESLint is linting [based on](https://github.com/reposense/RepoSense/blob/master/frontend/.eslintrc.json#L5) rules from `airbnb-base`, which is only configured for JavaScript code. The `@vue/typescript` ruleset only enables rules for TypeScript code within `.vue` files. 

This means that ESLint does not currently lint any TypeScript-specific code (It still lints regular JavaScript code within `.ts` files). This can be seen by introducing a style error in TypeScript code, such as removing the space before the curly brace [here](https://github.com/reposense/RepoSense/blob/master/frontend/src/types/types.ts#L10), and noticing that it still passes the linter. On the other hand, introducing a similar style error in JavaScript code, such as removing the space before the curly brace [here](https://github.com/reposense/RepoSense/blob/master/frontend/src/utils/api.ts#L23) will rightly be caught by the linter.

### Is the feature request related to a problem?

TypeScript code should be linted similar to JavaScript code, to enforce consistency and avoid errors.

### If possible, describe the solution

We can add the [airbnb-typescript](https://github.com/iamturns/eslint-config-airbnb-typescript) ruleset, which is similar to the existing airbnb-base ruleset that we are following, but configured for TypeScript code.

Additionally, I propose adding the [rules recommended by typescript-eslint](https://typescript-eslint.io/rules/) that includes rules that enforces more strict type safety (e.g. disallowing explicit `any` types). This will increase type safety across the codebase, which is one of the main reasons for using TypeScript in the first place.

### PR DESCRIPTION
**Pull request by vvidday**
Fixes #1912
Should only be merged after #1914 fixes the lint errors

### Proposed commit message

```
Currently, ESLint is not configured to lint TypeScript specific code.
This may result in errors not being detected by the linter, which could
lead to bugs and a decrease in code quality and consistency.

Let's add the airbnb-typescript config to enforce style rules, and add
the typescript-eslint recommended rules to enforce greater type safety
within TypeScript code.
```

### Other information

We're specifying the TypeScript rules under `overrides` -> `files: *.ts` to separate the linting of `.vue` and `.ts` files. (Otherwise, the linter will try to lint the `.vue` files according to the TypeScript rules, which causes errors.)

The two rulesets that are extended are [airbnb typescript config](https://github.com/iamturns/eslint-config-airbnb-typescript), which is just the style rules from `airbnb-base` configured for TypeScript code, and the [recommended rules from typescript-eslint](https://typescript-eslint.io/rules/). As mentioned in #1912, these rules will help enforce type safety in our TypeScript code (e.g. by warning when we use `any`, which should be minimized since it defeats the purpose of using TypeScript).

The rule override is due to the base airbnb config configuring [SwitchCase to 1](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/style.js#L124), which [enforces the indent in case statements](https://eslint.org/docs/latest/rules/indent#switchcase).

I'll be fixing the existing errors (e.g. use of `any`) in #1914, which should resolve the errors produced by this PR.

### CODE REVIEW

**Comment by yhtMinceraft1010X** [comment]
I'm curious about why PR #1914 and this PR are separate from each other. IMO, if any changes to linting rules results in lint checks failing, the rectifications to the source code should be made in the same PR so that there is a way to enforce them.

**Comment by vvidday** [comment]
> I'm curious about why PR #1914 and this PR are separate from each other. IMO, if any changes to linting rules results in lint checks failing, the rectifications to the source code should be made in the same PR so that there is a way to enforce them.

Yeah I also wasn't too sure on whether to separate these into two PRs or not, I mainly chose to separate them because it was similar to #1903 and #1904 where I also separated the changes to the lint setup and the source code. But I do agree that it makes sense for any changes that make lint checks fail to be submitted together with the changes to source code that makes it pass again. There was also the issue with #1903 and #1904 where we had to merge the changes to the lint rules back into the branch with the source code changes, and we couldn't see whether the CI for the updated rules + source code passed until then. I can close this PR and combine the changes into the other one, if that will be better!

**Review by ckcherry23 — APPROVED** [review]
I think this PR can be separate from #1914 as the TypeScript ESLint rules configured could have their own discussions. The changes LGTM!

**Review by HCY123902 — APPROVED** [review]
Great work. You can adjust the status of the pull request from `Draft` to `Open` after the changes are settled

**Review by dcshzj — APPROVED** [review]
LGTM!

**Pull request merged**
