### PR TITLE
Fix some minor cosmetic issues in docs

### PR DESCRIPTION
**Pull request by damithc**
Fixes for some minor cosmetic issues I noticed while reading the UG.

You can do a rebase merge for this, as each commit is a separate fix.

```
Fix some minor cosmetic issues in docs

The documentation site for RepoSense uses the legacy <span> syntax for
defining variables. The example dashboards are also outdated. Moreover, the
word 'Git' has been capitalised wrongly in the docs.

Let's update variables.md to use the proper <variable> syntax instead
of the legacy <span> syntax for defining variables. Also, let's remove
the variables.json file as it is not used. Let's update links of example
dashboards to point to a later version which uses a more recent version of
RepoSense. Lastly, let's fix the 'Git' typos across the docs. 
```

### CODE REVIEW

**Review by ckcherry23 — APPROVED** [review]
LGTM, thanks!

**Comment by ckcherry23** [comment]
I'll have to squash merge as "Rebase and merge" is disabled for RepoSense.

**Comment by damithc** [comment]
> I'll have to squash merge as "Rebase and merge" is disabled for RepoSense.

@ckcherry23 I enabled it just now.

**Comment by ckcherry23** [comment]
Completed in #2219 to rebase with master instead of merge commits

**Pull request closed without merging**
