### PR TITLE
Console output: fix grammar and improve readability #200

### LINKED ISSUE #200: Console output: use info instead of infos
Current console output:
```
09:31:30 - Log folder has been successfully created
09:31:30 - Cloning CS2103AUG2017-W09-B1/main...
09:31:39 - Cloning completed!
09:31:39 - Extracting commits info for CS2103AUG2017-W09-B1/main...
09:31:44 - Extracting relevant file infos...
09:36:05 - Cloning CS2103JAN2018-F14-B1/main...
09:36:14 - Cloning completed!
09:36:15 - Extracting commits info for CS2103JAN2018-F14-B1/main...
09:36:19 - Extracting relevant file infos...
```

Shall we use `info` instead of `infos`?

### PR DESCRIPTION
**Pull request by nadhira15**
Fixes #200

### CODE REVIEW

**Comment by yamidark** [comment]
Hi @nadhira15,

Thanks for your contribution to RepoSense!

Your PR looks good to me. As your PR title is self-explanatory, there isn't a need for you to propose
a commit message for this.

However, do update your PR title to follow our [convention](https://oss-generic.github.io/process/docs/FormatsAndConventions.html#pr) for PR titles (basically, copy and paste the issue title and number as your PR title), and you may tag prof for the final review afterwards.

**Comment by nadhira15** [comment]
Hi @yamidark, I just changed the PR title according to the convention.

**Comment by yamidark** [comment]
@eugenepeh Reminder for your review

**Comment by eugenepeh** [comment]
Normally for such typo or grammar issues, we tend to fix in a bunch or when we touched upon it so that the commits wouldn't be too `fine-grained`.

**Comment by nadhira15** [comment]
Hi @eugenepeh, thanks for the review. I just updated the console messages to "Extracting relevant file info `from` " + config.getLocation() + "..." and "Cloning `from` "

**Comment by eugenepeh** [comment]
Hi @nadhira15, thanks for the fix!

Would you kindly help us by uploading a log of the updated console message as well?
So that we can see if anymore changes that are necessary to be made.
Thank you!

**Comment by nadhira15** [comment]
@eugenepeh, here's the updated log

image

**Pull request merged**
