### PR TITLE
[#798] Fix duplicate commit results for author using multiple aliases

### PR DESCRIPTION
**Pull request by jylee-git**
```
When analyzing repos without a specified author configuration, authors 
with multiple aliases will result in duplicate commits being recorded 
and displayed in the report view.

Let's remove the duplicate commit messages from being displayed in the 
zoom panel.

This is performed by changing the data type of commitResults for each 
author from List to LinedHashSet to remove the duplicates.
```

### CODE REVIEW

**Comment by damithc** [comment]
Use imperative mood in commit naming `Changed` -> `Change`

**Comment by jamessspanggg** [comment]
For the commit message, can you explain more on how you are removing the duplicate commit messages? e.g. using LinkedHashSet() instead of List for `commitResults`

**Comment by fzdy1914** [comment]
> When analyzing repos without a specified author configuration, authors 
> with multiple aliases will result in duplicate commits being recorded 
> and displayed in the report view.

Can you explain why this will happens? One commit can only have one author right?

**Comment by jylee-git** [comment]
Closing this PR as this isn't the ideal solution, and hence may be more complicated and needs further investigation.

**Pull request closed without merging**
