### PR TITLE
[#652] ChartView: fix url directing to wrong repository

### LINKED ISSUE #652: All charts of the an author pointing to the same repo
Example:
image

[link](https://nus-cs3281.github.io/2019-dashboard/#search=zhen&sort=name&sortWithin=searchPath&since=2018-12-01&until=2019-05-04&timeframe=day&reverse=false&groupSelect=groupByAuthors&breakdown=false&tabAuthor=marvinchin&tabRepo=se-edu_learningresources_master)

Grouped by Author.

Actual: All github links point to the same repo
Expected: Each should link to the respective repo

### PR DESCRIPTION
**Pull request by jamessspanggg**
Fixes #652 

```
The Octocat icon links to a GitHub repository by using the index 0 to
get the URL of the first repository.

When summary charts are grouped by Author, different repositories 
under the same Author to all link to the same URL as the first 
repository.

Let's update the URL to point to their respective repository by
referencing with the correct index.
```

### CODE REVIEW

**Comment by fzdy1914** [comment]
Do note that you need to write commit messages according to our rules.

**Comment by fzdy1914** [comment]
Instead of opening a new pr, you can directly edit your message in the same pr.

**Comment by fzdy1914** [comment]
@jamessspanggg 
Please make the PR fixes only one issue at one time. We usually do not sneak in code that is not related to the PR. Please open another PR for your second commit.

**Comment by jamessspanggg** [comment]
My apologies for the messy commits. Is this alright?

**Comment by fzdy1914** [comment]
@jamessspanggg 
Please follow the following flow as specified in our [commit organization](https://oss-generic.github.io/process/docs/FormatsAndConventions.html#commit-message) as specified in the [contribution guidelines](https://github.com/reposense/RepoSense/blob/master/docs/Process.md#how-to-contribute-to-the-reposense-repository):
```
{current situation} -- use present tense

{why it needs to change}

{what is being done about it} -- use imperative mood

{why it is done that way}

{any other relevant info}
```
Please make it more detailed.

**Comment by jamessspanggg** [comment]
Is this better? Sorry for the inconvenience caused.

**Comment by fzdy1914** [comment]
@jamessspanggg Myself is not good at writing a commit message, too. But try to keep each line within 72 characters.

**Comment by yong24s** [comment]
@jamessspanggg

Some suggestions.

```
The Octocat icon links to a GitHub repository by using the index 0 to
get the URL of the first repository.

When grouped by Author, this results in different repositories under the
same Author to all link to the same URL as the first repository.

Let's update the URL to point to their respective repository by
referencing with the correct index.
```
This is my attempt to make the commit message more concise.

A good commit message takes time and practice, try giving yourself at least 15 minutes. 😆  
You got lots of facts already but you got to refine it iteratively.

For example, this is how I worked on my word choice.
```
repository <-> repo
repo location -> location -> address -> URL
```

**Comment by jamessspanggg** [comment]
@yong24s thanks for the advice! I will definitely take more time to come up with a more concise commit message 👍

**Pull request merged**
