### PR TITLE
[#2112] Move Segment CSS into segment.vue

### LINKED ISSUE #2112: Move CSS for Segment component into c-segment.vue
### What feature(s) would you like to see in RepoSense

The CSS for c-segment is currently located in c-authorship-file.vue. We should move it into segment.vue.

### Is the feature request related to a problem?
No, but it may be troublesome to edit the styling for the segment component if it remains in a separate file.

### If possible, describe the solution
Copy the relevant code over to segment.vue.

### If applicable, describe alternatives you've considered
NIL

### Additional context
Original discussion in #2096.

### PR DESCRIPTION
**Pull request by sopa301**
Fixes #2112.

### Proposed commit message

```
The segment component CSS currently resides in the c-authorship-file
component. Moving it to the segment component would make it easier to
edit the segment component in the future.

Lets move the CSS into segment.vue.
```

### Other information

I've also decided to add the `scoped` attribute to the segment CSS style block since it's not being used anywhere else in the code base.

### CODE REVIEW

**Review by jonasongg — APPROVED** [review]
LGTM!

**Review by ckcherry23 — APPROVED** [review]
LGTM!

**Review by vvidday — APPROVED** [review]
LGTM!

**Comment by ckcherry23** [comment]
Merging this PR _appears_ to have broken the code-highlighting feature. We need further investigation to see what caused the issue and it needs to be fixed as soon as possible.

**Comment by damithc** [comment]
Also, whenever a regression happens, also look into if if a similar thing can be prevented in future, for example, by adding a test case.

**Pull request merged**
