### PR TITLE
[#2082] Fix typo in command in Setting Up page

### LINKED ISSUE #2082: Fix typo in command in Setting Up page
image

This should say `node -v`, as `npm -v` gives the version of npm.

### PR DESCRIPTION
**Pull request by supermii2**
Fixes #2082 

```
Replace the command `npm -v` with `node -v`.
This displays the node version instead of the npm version.
```

### CODE REVIEW

**Review by asdfghjkxd — APPROVED** [review]
LGTM, `node -v` appears to show the installed `node` version!

**Comment by sopa301** [comment]
LGTM

**Review by sopa301 — APPROVED** [review]
LGTM

**Comment by jonasongg** [comment]
Might want to change "Replaced" to "Replace" for the commit message!

**Comment by supermii2** [comment]
> Might want to change "Replaced" to "Replace" for the commit message!

Edited! Thank you!

**Review by ckcherry23 — APPROVED** [review]
Thanks @supermii2 for reporting and fixing this issue in the docs! Fixing such issues is very useful for future first-time contributors to get started easily.

**Review by vvidday — APPROVED** [review]
Nice catch!

Minor thing about the commit message body: try to follow the recommended format [(more details)](https://se-education.org/guides/guidelines/PRs.html#submitting-a-pr)
```
{current situation} -- use present tense

{why it needs to change}

{what is being done about it} -- use imperative mood

{why it is done that way}

{any other relevant info}
```
Some parts might seem obvious/redundant especially for smaller changes, but it's good to develop the habit for future PRs. For example, the body could be:
```
Fix typo in Setting Up page

The command given in the developer guide for checking the local Node.js
version is `npm -v`, which displays the version of npm instead.

Let's replace the command with `node -v`, which correctly displays the
Node.js version.
```

**Pull request merged**
