### PR TITLE
[#1726] Add support for GitLab and Bitbucket test repos

### LINKED ISSUE #1726: Tracking tasks related to supporting other types of remote repo URLs in PR#1644
The following are a list of necessary tasks related to but not implemented in PR#1644. This issue is meant to document and track the necessary changes.  

- [ ] [Docs] Update UG, DG and codebase for direct references to GitHub to use more general language
- [x] [Docs & Backend] Change `author-config.json` column header `Author's GitHub ID` to `Author's Git Host ID`  while maintaining backward compatibility with older `author-config.json` files that still use `Author's GitHub ID` column header
    - **Assigned to @SkyBlaise99** (https://github.com/reposense/RepoSense/pull/1799) 
- [x] ~[Frontend] Add message or warning when unsupported links are clicked to notify user that the link is not supported~
- [x] [Frontend] Allow the repo icon to use respective github, gitlab, and bitbucket icons (fontawesome has all three) when we know the repo is one of them, but that can be a separate enhancement (taken from [this suggestion]( https://github.com/reposense/RepoSense/pull/1644#discussion_r835710517))
    - **Assigned to @SkyBlaise99** (https://github.com/reposense/RepoSense/pull/1800)
- [x] [Tests] Expand list of repositories used for PR dashboard previews to include other git hosting platforms
    - **Assigned to @SkyBlaise99** (https://github.com/reposense/RepoSense/pull/1805)

### PR DESCRIPTION
**Pull request by SkyBlaise99**
Part of #1726

## Proposed commit message

```
Currently, only GitHub repos are used for testing.

As we allow more repository types, we should also include repos from 
other platforms that we now support, namely GitLab and BitBucket.

Let's add GitLab and BitBucket repositories for testing.
```

## Other information

Part 5 of #1726

### CODE REVIEW

**Comment by chan-j-d** [comment]
I don't think this "Fixes #1726", just part of it

**Review by chan-j-d — APPROVED** [review]
LGTM! All the links (blame, history, commit, author, repo) seem to be working

**Comment by SkyBlaise99** [comment]
> I don't think this "Fixes #1726", just part of it

Ah yes my bad, updated now.

**Comment by dcshzj** [comment]
I see you created the reposense group in GitLab.

@damithc would it be an issue? Would it be good if you are made an owner of that group on GitLab as well?

**Comment by damithc** [comment]
> I see you created the reposense group in GitLab.
> 
> @damithc would it be an issue? Would it be good if you are made an owner of that group on GitLab as well?

Yes, perhaps safer to add me as an owner, for purposes of continuity.

**Comment by dcshzj** [comment]
@damithc Do you have a GitLab ID that can be added? @SkyBlaise99 are you able to add Prof @damithc as an owner on GitLab?

**Comment by SkyBlaise99** [comment]
Sure. Prof @damithc, what's your ID?

**Comment by damithc** [comment]
> Sure. Prof @damithc, what's your ID? Or I can add any of you first.

`@damithcr`

**Comment by SkyBlaise99** [comment]
Just sent an invite. Do let me know if there's any issue.

**Comment by damithc** [comment]
> Just sent an invite. Do let me know if there's any issue.

Received. 👍

**Review by dcshzj — APPROVED** [review]
Great! I think for BitBucket it is not too much of a concern. If the CI fails in the future due to missing repo, I think we can safely find a replacement.

**Comment by SkyBlaise99** [comment]
Hi @dcshzj can you merge this as soon as possible as my IWM is coming to an end? Thank you.

**Pull request merged**
