### PR TITLE
Use header files (not tags) to show/hide the version alert

### PR DESCRIPTION
**Pull request by damithc**
For details of this PR, see the proposed commit message.

Testing instructions:
* See the alert appearing at the top of UG pages. A similar alert will appear in the DG pages of the production site.
* See the topNav for the extra link to the production website. This link will not appear in the production website (appears only in the dev website).
* See the `DG > Workflow > Writing documentation` section

Proposed commit message:
```
Use header files (not tags) to show/hide the version alert

The 'version alert' that tells readers whether they are looking at
the production or the dev website is an <include> in every
DG page. Showing/hiding it is controlled by the MarkBind
tags mechanism.

Let's use the header mechanism instead, which does not require any
changes to the DG pages as it is controlled by the site.json entirely.
At the same time, let's also add an alert in the UG of the dev website
to alert readers in case a user accidentally ended up in the dev
website when intending to go to the production website.

The above change removes the use of tagging in the website entirely.
However, the tagging mechanism might be useful for other variations
between the two sites. Let's include an extra link in the topNav of
the dev website to point to the production website, as an example of
content controlled by tags. Let's also update the DG to explain how
to use the tagging mechanism to control contents.
```

### CODE REVIEW

**Comment by damithc** [comment]
Ready for review

**Comment by Tejas2805** [comment]
Any reason why we are not keeping the alert header's colour consistent across the two sites? 

I also personally felt that the yellow was a bit too bright in contrast to the page. Not sure what others thing about it.

**Comment by damithc** [comment]
> Any reason why we are not keeping the alert header's colour consistent across the two sites?
> 
> I also personally felt that the yellow was a bit too bright in contrast to the page. Not sure what others thing about it.

It will be the same in appearance and color (i.e., a ribbon at the top, not a box) only the text will vary. I'm using Bootstrap 'warning' color in this new version.

**Comment by Tejas2805** [comment]
> > Any reason why we are not keeping the alert header's colour consistent across the two sites?
> > I also personally felt that the yellow was a bit too bright in contrast to the page. Not sure what others thing about it.
> 
> It will be the same in appearance and color (i.e., a ribbon at the top, not a box) only the text will vary. I'm using Bootstrap 'warning' color in this new version.

Ah okay. They are different in the PR so got confused.

**Comment by damithc** [comment]
> Ah okay. They are different in the PR so got confused.

If you click the 'PRODUCTION SITE' link in the surge preview, it goes to the actual production site which uses the previous style.

**Comment by Tejas2805** [comment]
The alignment of the `siteNav` in the Production Website is a bit distorted.

Screen Shot 2020-06-16 at 4 33 28 PM

-------
Screen Shot 2020-06-16 at 4 33 39 PM

**Comment by damithc** [comment]
> Aside from the indentation issues mentioned by @Tejas2805 , everything else LGTM

The production website was deployed using a newer version of MarkBind which has this alignment problem. A fix is in the works.

**Comment by damithc** [comment]
> Once the `Project management` is fixed, rest is okay from my side.

It's not related to this PR. Let's fix that as a separate PR.

**Comment by Tejas2805** [comment]
> > Once the `Project management` is fixed, rest is okay from my side.
> 
> It's not related to this PR. Let's fix that as a separate PR.

Alright. I have 1/2 other changes in mind, which are very cosmetic. Will create a single PR for all these changes.

**Comment by Tejas2805** [comment]
@jamessspanggg Can merge this now.

**Comment by damithc** [comment]
This version deployed to https://reposense.org/
The siteNav alignment issue has been fixed too

**Pull request merged**
