### PR TITLE
[#1754] Ignore case when comparing author usernames

### LINKED ISSUE #1754: Ignore case when comparing GitHub usernames to Git author name
Is it possible to ignore case when identifying the author of a commit based on the Git author name (as given in `author-config.csv`), or at least for the GitHub username?
Reason: in some cases students give us the GitHub username that may be case-wise different to the actual username (because GitHub usernames are case insensitive)

### PR DESCRIPTION
**Pull request by SkyBlaise99**
Fixes #1754

## Proposed commit message

```
Currently, identifying the author of a commit is done by getAuthor()
method in AuthorConfiguration.java. This matching is case-sensitive,
while GitHub usernames are case insensitive.

The function will not return the correct author if the input username is
case-wise different to the actual username.

Let's ignore case when identifying the author of a commit based on
author's aliases.
```

## Other information

Currently this is done by separating out `aliases` and `emails` from `details`.
Matching is case sensitive for `emails` but not for `aliases`.

### CODE REVIEW

**Review by yhtMinceraft1010X — APPROVED** [review]
LGTM

**Review by dcshzj — APPROVED** [review]
LGTM!

**Comment by dcshzj** [comment]
@SkyBlaise99 are you able to resolve the conflicts here?

**Comment by SkyBlaise99** [comment]
@dcshzj done, local test all good, waiting for CI to pass.

**Pull request merged**
