### PR TITLE
[#1765] Change npm version requirement to Node.js

### LINKED ISSUE #1765: Developer Guide: Change npm requirement to Node
**What would you like added or modified in the documentation?**

In the [Setting Up page](https://reposense.org/RepoSense/dg/settingUp.html) of the Developer Guide, the requirements are for `git`, `npm` and `JDK`. I am of the opinion that using `Node.js` in place of `npm` is better since `npm` is usually installed as part of `Node.js`. Other NUS-OSS projects also describe `Node.js` as a requirement, rather than `npm` by itself.

By using `Node.js`, it should also be easier to maintain the Developer Guide since the version can simply be updated whenever an older version reaches EOL, unlike `npm` where cross-referencing of the version against `Node.js` version is required.

### PR DESCRIPTION
**Pull request by yhtMinceraft1010X**
Fixes #1765 

## Proposed commit message

```
Node.js is often installed together with npm. With regards to tracking
version LTS and EOL, Node.js is often used instead of npm. Thus, it is
easier to update the Node.js version in the DG whenever the existing
version goes EOL and we upgrade to a newer version.

On the other hand, when updating the corresponding npm version, there
is a need to look for the Node.js version and then find the
corresponding npm version.

Let's change the DG pre-requisites to reference the Node.js version and
specify that it is for npm. This improves maintainability of the DG.
```

### CODE REVIEW

**Comment by dcshzj** [comment]
@yhtMinceraft1010X Were you able to verify if newer versions of Node.js are able to work, at least for Node.js 16?

**Comment by yhtMinceraft1010X** [comment]
I tested Node 16 with the existing CI. It did not work according to #1764 but merging #1767 should solve this.

**Comment by yhtMinceraft1010X** [comment]
> I tested Node 16 with the existing CI. It did not work according to #1764 but merging #1767 should solve this.

To add on, #1762 should also be merged before Node 16 can be used. I remember trying to use Node 16 directly but failing due to dependency conflicts that are addressed by #1762

**Comment by yhtMinceraft1010X** [comment]
I have tested it out using Node 16. It works so I have updated the Node requirement accordingly.

**Review by dcshzj — APPROVED** [review]
LGTM!

**Pull request merged**
