### PR TITLE
[#1634] Replace cdn links to import from node_modules instead

### LINKED ISSUE #1634: Replace cdn links to import from `node_modules` instead
**What feature(s) would you like to see in RepoSense?**
Replace [this](https://github.com/reposense/RepoSense/blob/c4d7690e7b2c3b2626187a2c26ee447d99adf15a/frontend/src/app.vue#L317-L322) with `node_module` imports

**Is the feature request related to a problem?**

Dependabot can track outdated packages in `package-lock.json` files, but not if they are imported directly in the code. Furthermore, it would be good if the frontend only had a 'single source of truth' for all externally imported packages, making the project easier to manage.

### PR DESCRIPTION
**Pull request by Zhou-Jiahao-1998**
Fixes #1634 

## Proposed commit message

```
Some css files are currently imported directly in the code, making it
difficult to manage.

Let us import from node_module for easy management.
```

### CODE REVIEW

**Review by yhtMinceraft1010X — APPROVED** [review]
LGTM

**Review by chan-j-d — COMMENTED** [review]
Just wanted to check if I understood it correctly. The dependencies needed are stored in `frontend/package.json` which are downloaded when the frontend is being build. And the issue here is that there are direct imports in `app.vue` from the websites themselves bypassing these dependencies. For example `highlight.js 10.5.0` is currently the dependency used but `app.vue` directly imports from `highlight.js 9.14`. Same for `vue-loading-overlay`. 

`muicss` and `normalize` were both originally not included in the dependency so they are included now. Lastly, the `font.css` used is stored in its own local file and does the linking to the google font from there. 

Is that correct?

**Comment by Zhou-Jiahao-1998** [comment]
@chan-j-d Yes that is correct. `package.json` allows us to easily track which dependency can be upgraded. With this PR, we can make sure that there is only one source of truth here. Therefore, avoiding the problem of `highlight.js` here in future.

**Comment by gerhean** [comment]
Instead of loading fonts from `fonts.gstatic.com`, would it be better to just bundle it into the project, such as by using [this](https://github.com/KyleAMathews/typefaces/) or other similar packages?

**Comment by Zhou-Jiahao-1998** [comment]
@gerhean I have decided to use [fontsource](https://github.com/fontsource/fontsource) because the one you suggested is deprecated. This is the alternative suggested by that package. I am not too sure why `codecov/project` is failing.

**Comment by Zhou-Jiahao-1998** [comment]
@gerhean @damithc I propose that we use the GitHub theme in highlight.js for syntax highlighting.
Screenshot 2022-03-14 at 13 03 28
This is what we are currently using.

Screenshot 2022-03-14 at 13 03 09
This is how the new one looks like.

Screenshot 2022-03-14 at 13 06 58

This is how it looks in GitHub.

**Comment by damithc** [comment]
> @gerhean @damithc I propose that we use the GitHub theme in highlight.js for syntax highlighting.

Good idea @Zhou-Jiahao-1998 . Not sure if this should be a separate PR though, given it is a stand-alone tweak.

**Review by gerhean — APPROVED** [review]
LGTM, minor change so will merge.

**Pull request merged**
