### PR TITLE
[#1336] Show non-blank line count in the brackets instead of blank lines

### LINKED ISSUE #1336: Show non-blank lines count instead of blank-lines count
Current: blank lines count is shown within brackets
image

Suggestion: It's more useful to show the non-blank links count instead? 

Reason: To save the user from having to do the mental calculation.

### PR DESCRIPTION
**Pull request by lm5lm5**
Fixes #1336 

```
Currently, the report in the code panel (authorship) part shows
the number of blank lines written by an author in a file or in all
files of a file type inside the brackets beside the total number of
lines written. The viewer needs to do mental calculation to get the
number of non-blank lines written by the author.

Let's change the front end code to show non-blank line count instead.
```
Before:
before
After:
after

### CODE REVIEW

**Comment by jamessspanggg** [comment]
Screen Shot 2020-10-06 at 11 10 04 AM

Do you have any idea why your commits are not linked to yourself? This might explain why Travis isn't running.

This might help: https://docs.github.com/en/free-pro-team@latest/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user

**Comment by fzdy1914** [comment]
> Screen Shot 2020-10-06 at 11 10 04 AM
> 
> Do you have any idea why your commits are not linked to yourself? This might explain why Travis isn't running.
> 
> This might help: https://docs.github.com/en/free-pro-team@latest/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user

@lm5lm5 ？

**Comment by lm5lm5** [comment]
@fzdy1914 Sorry for the delay. I figured out why my previous commits were not linked to my Github account - I didn't change the commit email to my current Github account email. My future commits will be properly linked to my Github account, but I suppose there is no convenient way of changing the author (i.e. email) of my previous commits.
In that case, how about I close my pending PRs and redo the commits from the master branch since not many lines of code were changed in these PRs?

**Comment by fzdy1914** [comment]
> @fzdy1914 Sorry for the delay. I figured out why my previous commits were not linked to my Github account - I didn't change the commit email to my current Github account email. My future commits will be properly linked to my Github account, but I suppose there is no convenient way of changing the author (i.e. email) of my previous commits.
> In that case, how about I close my pending PRs and redo the commits from the master branch since not many lines of code were changed in these PRs?

If you know git operations well, you can squash all your commit using command `git rebase -i` and force push to this PR.

**Comment by lm5lm5** [comment]
> > @fzdy1914 Sorry for the delay. I figured out why my previous commits were not linked to my Github account - I didn't change the commit email to my current Github account email. My future commits will be properly linked to my Github account, but I suppose there is no convenient way of changing the author (i.e. email) of my previous commits.
> > In that case, how about I close my pending PRs and redo the commits from the master branch since not many lines of code were changed in these PRs?
> 
> If you know git operations well, you can squash all your commit using command `git rebase -i` and force push to this PR.

I can try but I'm actually using SourceTree for git operations.

**Comment by fzdy1914** [comment]
> I can try but I'm actually using SourceTree for git operations.

The squash option is easier to use in SourceTree, choose a commit and right click and use `rebase the children of xxx interactively`.

**Comment by lm5lm5** [comment]
> > I can try but I'm actually using SourceTree for git operations.
> 
> The squash option is easier to use in SourceTree, choose a commit and right click and use `rebase the children of xxx interactively`.

@fzdy1914 Sorry I think I made some mistake when trying to rebase and I could not reverse it. I'll create another PR that does the same commits and close this PR once the new PR is approved and merged.

**Comment by lm5lm5** [comment]
I notice that my Github account has been flagged for potential abuse by Travis CI. I'll contact support@travis-ci.com for solution.

**Comment by fzdy1914** [comment]
> I notice that my Github account has been flagged for potential abuse by Travis CI. I'll contact [support@travis-ci.com](mailto:support@travis-ci.com) for solution.

OK, just make it fast.

**Review by Tejas2805 — APPROVED** [review]

**Pull request closed without merging**
