### PR TITLE
Fix lint warnings

### LINKED ISSUE #2181: Fix lint warnings
There are various lint warnings that appear when building. This can cause confusion on what lint problem exactly is causing a build to fail. Let's fix them.

image

### PR DESCRIPTION
**Pull request by jonasongg**
(cherry picked from commit 76a9425c94f84aeeef175b39f75c7034fa1ef205)

Fixes #2181

### Proposed commit message

```
Fix lint warnings

Currently, there are various lint warnings that appear when building.

This can cause confusion on what lint problem exactly is causing a
build to fail. Let's fix them.
```

### CODE REVIEW

**Comment by sopa301** [comment]
Is it possible to also fix the multiple tags warning in summary charts as well?

**Comment by jonasongg** [comment]
@sopa301 which warnings are you referring to ?

**Comment by sopa301** [comment]
These:
image

**Comment by jonasongg** [comment]
@sopa301 ah ok, just fixed as well!

**Review by sopa301 — APPROVED** [review]
LGTM!

**Review by MarcusTXK — APPROVED** [review]
LGTM

**Review by ckcherry23 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
