### PR TITLE
[#1061] Remove unused dependency

### PR DESCRIPTION
**Pull request by Tejas2805**
Fixes part of #1061 

```
Netlify build takes a lot of time due to a large number of 
dependencies. 

Let's remove the unused dependencies to reduce the build
time.
```

### CODE REVIEW

**Comment by Tejas2805** [comment]
Main focus on #1096

**Comment by fzdy1914** [comment]
Is there more dependency to remove?

**Comment by Tejas2805** [comment]
This is the only dependency that we can remove. There might be other optimizations in Gradle possible though

**Comment by Tejas2805** [comment]
@fzdy1914 Have checked for other Gradle lint rules. All seem to be okay.

**Comment by fzdy1914** [comment]
OK

**Comment by anubh-v** [comment]
I just have a question to better understand the gradle build file. Do we know how this dependency was being used in the past? Or was it always unused?

**Comment by anubh-v** [comment]
Based on a search, it seems that this Java Parser library was previously used in the `MethodAnalyzer` class which was removed in [PR 628](https://github.com/reposense/RepoSense/pull/628/)

**Pull request merged**
