### PR TITLE
[#746] CodeView: loading screen only shows when first time selecting to view code

### LINKED ISSUE #746: CodeView: loading screen only shows when first time selecting to view code
The loading screen only appears the first time selecting to view the code. 
After that, when users selects another code, they may not know that the code is loading as the loading screen does not appear.

loading-screen

### PR DESCRIPTION
**Pull request by fzdy1914**
Fixes #746

### CODE REVIEW

**Comment by fzdy1914** [comment]
@reposense/stage0-reviewers 
I would like to invite you guys to fill the proposed commit message for me. The key point is to illustrate why an additional `setTimeOut` is needed as technical details. You may just comment your answer below. 

By investigating this will allow you to have more understanding of how Vue deal with different tasks. :)

**Comment by 0blivious** [comment]
setTimeout pushes the callback function to the end of the execution queue. So before the initiate function was called, the browser will render the authorship tab first with isLoaded set to false

**Comment by jamessspanggg** [comment]
@0blivious I think u can co-author and take over this PR, edit the pr message and resolve the conflicts accordingly. 

The code LGTM

**Comment by fzdy1914** [comment]
@0blivious Yes, pls take over this PR when you are free.

**Comment by fzdy1914** [comment]
Closing this as this solution is no longer effective.

**Pull request closed without merging**
