### PR TITLE
[#770] Fix bug of file format contribution icons with no colours

### PR DESCRIPTION
**Pull request by jamessspanggg**
Fixes Bug 2 of #770 

```
The 'users' array within 'this.repos' may be empty in situations 
such as analysing repositories with no author commits within
the specified date.

The empty 'users' array will lead to bugs such as not assigning colours
to the file format icons.

Let's use 'this.filtered' instead of 'this.repos' to prevent such bugs
from occurring as 'this.filtered' filters out repositories with empty 
'users' array.
```

### CODE REVIEW

**Comment by eugenepeh** [comment]
From the bug description and the commit message

```
When analysing repositories with standalone config, if there is a 
repository with no authors that match the pre-specified authors 
within standalone config file, the 'users' array within 'this.repos' 
will be empty.
```

I don't think this truly solves the problem. 
E.g. reposense_testrepo-Alpha just disappear from the report, is not a good solution. 
It should follow the same style as the other repositories, when encounter an error, a place holder should still be there along with the error message.
image

**Comment by fzdy1914** [comment]
> I don't think this truly solves the problem.

Actually, he has separate the bug into two part. This part is stand alone from the other one. This just fixes an improper use of `user`. But the commit message needed to be edited anyway.

**Comment by jamessspanggg** [comment]
Am closing this PR as a more general solution #777 is found.

**Comment by fzdy1914** [comment]
> Am closing this PR as I have found a more general solution #777 that adds an error place holder and prevents file format icons with no colours.

But I believe the changes made in this PR is still needed. The original design does have drawbacks.

**Comment by jamessspanggg** [comment]
> > Am closing this PR as I have found a more general solution #777 that adds an error place holder and prevents file format icons with no colours.
> 
> But I believe the changes made in this PR is still needed. The original design does have drawbacks.

ok noted.

**Comment by fzdy1914** [comment]
@jamessspanggg 
>  But I believe the changes made in this PR is still needed. The original design does have drawbacks.

You just need to edit the commit message to show why the previous implement may lead to bugs.

**Comment by jamessspanggg** [comment]
> @jamessspanggg
> 
> > But I believe the changes made in this PR is still needed. The original design does have drawbacks.
> 
> You just need to edit the commit message to show why the previous implement may lead to bugs.

noted.

**Comment by eugenepeh** [comment]
Hmm.. with the first bug fix, will this problem still actually appears?

**Comment by jamessspanggg** [comment]
> Hmm.. with the first bug fix, will this problem still actually appears?

No it will no longer appear, but myself and @fzdy1914 thinks that it is more appropriate to use `this.filtered` as opposed to `this.repos` because 
- `this.filtered` will definitely not contain empty `users`, which ensures that this bug will no longer appear
- as we are displaying the ramp chart in terms of `this.filtered` instead of `this.repos`, it makes sense to set the contribution bar colours in terms of `this.filtered`

**Comment by eugenepeh** [comment]
Good points but with certain downside to this

>this.filtered will definitely not contain empty users, which ensures that this bug will no longer appear

This means that we wouldn't realize if there is such a problem in future

>as we are displaying the ramp chart in terms of this.filtered instead of this.repos, it makes sense to set the contribution bar colours in terms of this.filtered

The colour would be different upon changing of search terms and other variables

**Pull request closed without merging**
