### PR TITLE
[#1426] Zoom reloading not function properly

### PR DESCRIPTION
**Pull request by gerhean**
```
When following the steps mentioned in #1426,
we get an error.

The error is caused by the zFilterSearch parameter of the url
being the string 'undefined', which causes restoreZoomFiltered
in v_summary.js to crash as 'isMatchSearchedUser(zFilterSearch, user)'
does not match any user leading to an array index out of bounds error.

Lets fix this by ensuring that zFilterSearch is defined in v_ramp, 
such that zFilterSearch='undefined' is not generated in the url,
when one clicks on the ramp.

This does not fix the fact that a bad url can still cause the error.
```

### CODE REVIEW

**Review by 0blivious — APPROVED** [review]
LGTM, please write a complete PR message, including what causes the error and the explanation for your solution. Then you can ask review from stage2

**Comment by fzdy1914** [comment]
@gerhean Just a question, as mentioned in your commit message, a bad URL can still cause an error.  How do you define a bad URL? Can we ignore such parameters if they are provided?

**Comment by gerhean** [comment]
@fzdy1914 
I would define a bad URL as a URL which would cause the reposense website to crash, even if the URL cannot possibly be generated by the website itself.
Example of bad URL: go to any reposense, look for `&sort=groupTitle` in the url and change it to `&sort=a`, on refresh it will completely not work.

**Comment by fzdy1914** [comment]
> @fzdy1914
> I would define a bad URL as a URL which would cause the reposense website to crash, even if the URL cannot possibly be generated by the website itself.
> Example of bad URL: go to any reposense, look for `&sort=groupTitle` in the url and change it to `&sort=a`, on refresh it will completely not work.

Seems that this can be solved easily by a pre-verification step? Can you put it as an issue to solve such invalid parameters?

**Pull request merged**
