### PR TITLE
Convert UG and DG to MarkBind

### PR DESCRIPTION
**Pull request by Tejas2805**
Convert docs to Markbind

### CODE REVIEW

**Comment by Tejas2805** [comment]
@damithc I have started working on converting both the guides to Markbind format. I wish to know the exact thought in your mind - how the website looks, and what all it contains. From there, I will proceed accordingly.

**Comment by Tejas2805** [comment]
Screen Shot 2020-03-04 at 4 31 42 AM

This is how it currently looks

**Comment by damithc** [comment]
The more important task is to ensure PR previews can be used to preview any updates to the docs. Normally, a MarkBind site can use Netlify for that but as RepoSense is already using Netlify for dashborad preview, we need to go the extra mile to ensure both docs and the dashboard can be previewed for each PR.
Conversion to MarkBind can only go ahead after figuring out how to solve that problem.

**Comment by Tejas2805** [comment]
Ah I see. But I thought we had already discussed regarding how we were planning to go about it.

**If Netlify**:

We will add MarkBind site link to the same Netlify script (this is possible) and then access the docs using the UG link in the footer of the Charts Panel.

**If Surge**:

1) We can deploy the docs to a different domain in the script and then access the docs using the UG link in the footer of the Charts Panel.
2) We can deploy the docs to a different domain in the script and then access the site directly. 

**Using Both** (New suggestion but complicated):

We can use Surge to deploy the dashboard and use Netlify to access MarkBind site (since MarkBind gives a way to deploy using Netlify specifically) and then access the docs using the UG link in the footer of the Charts Panel.

Based on discussion #956

**Comment by Tejas2805** [comment]
Will keep this on hold, till we finalize a way to go about this.

**Comment by jamessspanggg** [comment]
@Tejas2805 may I know the command to run the build of this markbind website?

**Comment by damithc** [comment]
In case relevant https://markbind.org/userGuide/deployingTheSite.html

**Pull request closed without merging**
