### PR TITLE
[#2045] Fix cypress zoom feature test

### LINKED ISSUE #2045: Failure of Cypress zoom feature test
### Tell us about your environment

* **RepoSense Version:** Master branch
* **OS and Version:** N.A.
* **Web Browser and Version (if applicable):** GitHub Actions default

### Please include the steps to reproduce the bug.

Sample run with failing Cypress test can be found [here](https://github.com/reposense/RepoSense/actions/runs/6385743987/job/17331110521?pr=2037).
However, bug seems to not be exclusive to PR #2037, but also to master branch.

### What was expected to happen?
Cypress tests should be passing.

### What actually happened? Please include a screenshot of the output.
Cypress tests are failing due to changes in frontend behavior caused by PR #2034. However, behavioral changes are intentional and a fix to a pre-existing bug which resulted in the zoom range not selecting an accurate date range.
image

On local Windows 11 environment, Chrome 117
image
image
image

### PR DESCRIPTION
**Pull request by jq1836**
Fixes #2045 

### Proposed commit message

```
Currently, Cypress zoom feature tests are failing due to a recent change
in behavior caused by a bug fix. With the tests failing, we are unable
to detect any future regressions.

Let's update the Cypress tests to test for the new intended behavior.
```

### Other information
* Original point (200, 20) has been replaced by (185, 20), as it seems that the choice of (200, 20) leads to potentially non-deterministic behavior, i.e. Cypress test fails sometimes, but not others.
* Choice of (180, 20) is a boundary point, making it sensitive to small regressions, while being seemingly deterministic.

### CODE REVIEW

**Review by ckcherry23 — APPROVED** [review]
LGTM!

**Comment by ckcherry23** [comment]
> @reposense/active-reviewers-1 this PR is ready for review

@jq1836 Thanks for working on this. When PRs are ready for review, you can request for a review from the @reposense/active-reviewers-1 team on the right panel.

Screenshot 2023-10-04 at 7 08 53 AM

**Comment by jq1836** [comment]
@ckcherry23 Thanks for taking your time to review the code. Regarding the review requesting, seems like I do not quite have the permissions to request a review as you have described.

**Review by chan-j-d — APPROVED** [review]
LGTM!

**Pull request merged**
