### PR TITLE
[#912] DeveloperGuide: update links in table of contents

### LINKED ISSUE #912: Developer guide: Fix broken links in table of contents, and add useful links
The links outlined in the image below are broken:

toc

These links can be replaced by a single link to the section shown below:

jss

In addition, we could add links to the "Before writing code" and "Building and running RepoSense from code" sections, to make the content more obvious to new readers.

newlinks

### PR DESCRIPTION
**Pull request by anubh-v**
Fixes #912 

```
Developer guide: Update links in the table of contents

The table of contents in the developer guide has 2 broken links.
It also lacks links to the instructions for building / running
RepoSense locally and making contributions.

The table of contents should stay synchronised with the document.

Let's fix the broken links and add links to the instructions for
contributing and building RepoSense.

```

### CODE REVIEW

**Comment by anubh-v** [comment]
@yong24s could you help take a look at this? Thanks!

**Comment by anubh-v** [comment]
Thanks for the review @eugenepeh. I have added the remaining missing links as well.

**Comment by anubh-v** [comment]
@eugenepeh thanks again for the review. Could I check if this PR needs more work / improvements?

**Comment by anubh-v** [comment]
@jylee-git, may I seek your help to provide the 3rd approval for this PR? Thanks very much.

**Comment by eugenepeh** [comment]
@reposense/devs last call for review. Do highlight any changes potentially related to this PR

**Pull request merged**
