### PR TITLE
Ramp chart: optimize vertical space #21

### LINKED ISSUE #21: Ramp chart: optimize vertical space further
image

Red lines can be moved closer to the main bar.
Names can be as small as font size of code (but can show in bold)

### PR DESCRIPTION
**Pull request by ongspxm**
proposed message. fixes #21 

```
Let's increase readability by updating the template to display
the contribution line of the different users more prominently.
```

### CODE REVIEW

**Comment by ongspxm** [comment]
image
final view

**Comment by eugenepeh** [comment]
For Ui PR, please post the image of the Ui change after every iteration of request changes.

**Comment by ongspxm** [comment]
Means i copy the other pictures over?

**Comment by eugenepeh** [comment]
yes, in future, comment on PR itself.

Why is double line necessary though?

**Comment by harryggg** [comment]
In some scenario, a user contributes so much more than others, that the other users "bar" all seems very small on the same scale. That's why Dr damith proposed to use multiple "bars" to represent those who contributes "too much"

**Comment by eugenepeh** [comment]
>In some scenario, a user contributes so much more than others, that the other users "bar" all seems very small on the same scale. That's why Dr damith proposed to use multiple "bars" to represent those who contributes "too much"

I see, make sense.

**Comment by eugenepeh** [comment]
Can we have the [user guide's dashboard](https://github.com/reposense/RepoSense/blob/master/docs/user_guide.md#dashboard) updated with the new red line? 

Also for the [chart panel](https://github.com/reposense/RepoSense/blob/master/docs/user_guide.md#chart-panel) section, it would be nice that we illustrate the red line too.

**Comment by ongspxm** [comment]
ready for review

**Comment by ongspxm** [comment]
@damithc ready for review

**Pull request merged**
