### PR TITLE
[#1621] Docs: case 3 report and settings links do not match

### LINKED ISSUE #1621: Documentation Showcase: Case 3 report and settings links do not match
**Tell us about your environment**

* **RepoSense Version:**
* **OS and Version:**
* **Web Browser and Version (if applicable):**

**Please include the steps to reproduce the bug.**

1. Go to [showcase](https://reposense.org/showcase.html)
2. Click the report link
3. Click the settings link
4. Compare the URLs

**What was expected to happen?**
Settings link should lead to the [cs3281 2020 dashboard github page](https://github.com/nus-cs3281/2020-dashboard), to match this [report](https://nus-cs3281.github.io/2020-dashboard/?search=&sort=groupTitle&sortWithin=title&since=2019-12-01&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=false)

**What actually happened? Please include a screenshot of the output.**
Settings link leads to a [CS2113T page](https://github.com/nus-cs2113-AY1920S2/tp-dashboard)

**If possible, include the URL to your RepoSense report or log files (if any).**

### PR DESCRIPTION
**Pull request by yhtMinceraft1010X**
Fixes #1621 as well as some other links that do not work as intended.

Proposed commit message:
```
Some of the links in showcase.md do not match the links given in the
address bar. In some cases, the links do not match the respective
descriptions or repository. 

In addition, some reports were generated using an older version of
RepoSense, which results in different URL params.

Let's change these links and use newer reports for consistency in the
URL style.
```

### CODE REVIEW

**Comment by yhtMinceraft1010X** [comment]
I have noticed that for the links that don't seem to work, they would lead to a default view. For the case 1 examples, that would be: https://nus-cs2103-ay2021s1.github.io/ip-dashboard/?search=&sort=groupTitle&sortWithin=title&since=2020-08-14&until=2020-09-27&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=false

The unchanged links still work as intended, but they still use the `#` for the parameters rather than the `?`. Should I change the remaining links to use `?` instead?

**Comment by yhtMinceraft1010X** [comment]
I have made the changes for the case 1 and 3 report links but I noticed that the case 2 report link and example links do not change. Even if I were to replace the `#` with `?`, the `#` portion merely gets pushed back, resulting in a duplication of parameters. An example below for the case 2 report link:
https://nus-cs2103-ay2021s1.github.io/tp-dashboard/?breakdown=true&search=&sort=groupTitle&sortWithin=title&since=2020-08-14&timeframe=commit&mergegroup=&groupSelect=groupByRepos&checkedFileTypes=docs~functional-code~test-code~other&until=2020-11-10#search=&sort=groupTitle&sortWithin=title&since=2020-08-14&until=2020-11-10&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=false

I'm quite hesitant to make any changes to the case 2 links at the moment due to the above reason.

**Comment by dcshzj** [comment]
It's because the RepoSense report was generated using an older version before we made the change to use `?` instead of `#` in #1371. I think it should be okay to switch to a more recent iteration of CS2103 and use that report instead, so that we can also show users a more recent version of the software.

**Comment by gerhean** [comment]
Should update commit message to mention that it links to the newer reports now.

**Review by gerhean — APPROVED** [review]
LGTM

**Review by dcshzj — APPROVED** [review]
LGTM! I think including the deadline date was a nice touch.

**Pull request merged**
