### PR TITLE
Release branch update

### PR DESCRIPTION
**Pull request by HCY123902**
Related to #1560 

The current release of RepoSense 2.0 contains the latest implementation and documentation corresponding to the master branch. The corresponding documentation at `reposense.org/RepoSense` also matches the master branch, generated by MarkBind 3.0.6. However, the release branch is outdated and it needs to be merged with the master branch.

Note that `site.json` is the same in the 2 branches. The filter tags include both `-production` and `dev`. This may need to be adjusted, as the release branch should only have the `production` tag.

Commit message:
```
Merge the release branch with the current master branch

The current release branch was outdated compared with the
current master branch, The release branch documentation is written
in MarkBind 2.0 while the master branch documentation has been
migrated to MarkBind 3.0.

It is necessary to merge the release branch with the current
master branch as a prerequisite of publishing the documentation
at `reposense.org`.

Let's merge the release branch with the current master branch
```

### CODE REVIEW

**Comment by dcshzj** [comment]
I think it might not be a good idea to have 2 PRs every time we make a release. Instead, I propose to use rebasing to update the `release` branch, which will allow us to have both the `master` and the `release` branches to have the same commit history, with the `release` branch having additional commits that are specific to it (currently to get the documentation site working).

To outline the proposed process of making a release:
1. Make a release on GitHub as already outlined in our developer documentation. There is no change to this step in the current workflow.
2. Temporarily configure the branch protection rules on the `release` branch to allow for force pushes (see screenshot below):

image

3. Rebase the `release` branch to the `master` branch. This step will put aside any additional commits on the `release` branch, apply all the additional commits from the `master` branch that is not yet present in the `release` branch, and then apply the commits put aside onto the new `release` branch. The following picture illustrates it (main branch is the `master` branch and your branch is the `release` branch, [source](https://www.mohammedasker.com/explaining-how-git-rebase-works-in-laymans-terms-%F0%9F%8D%95-%F0%9F%A5%91-%F0%9F%8D%96)):

image

4. Force push the new `release` branch to GitHub.
5. Revert the temporary configuration of the branch protection rules on the `release` branch, to disable force pushes.

If additional commits need to be made to the `release` branch, the usual pull request workflow to the `release` branch is sufficient. If there are any conflicts during step 3, they can be resolved locally by the person making the release. This also means that only administrators have the ability to make new releases (since the branch protection rules need to be changed in step 2).

I think this way allows us to maintain the integrity of the `release` branch and no additional pull requests need to be made for every new release. It should also be less error prone as the custom changes on the `release` branch do not have to be made every time a release happens. @HCY123902 and Prof @damithc what do you think?

**Comment by HCY123902** [comment]
> I think it might not be a good idea to have 2 PRs every time we make a release. Instead, I propose to use rebasing to update the `release` branch, which will allow us to have both the `master` and the `release` branches to have the same commit history, with the `release` branch having additional commits that are specific to it (currently to get the documentation site working).
> 
> To outline the proposed process of making a release:
> 
> 1. Make a release on GitHub as already outlined in our developer documentation. There is no change to this step in the current workflow.
> 2. Temporarily configure the branch protection rules on the `release` branch to allow for force pushes (see screenshot below):
> 
> image
> 
> 1. Rebase the `release` branch to the `master` branch. This step will put aside any additional commits on the `release` branch, apply all the additional commits from the `master` branch that is not yet present in the `release` branch, and then apply the commits put aside onto the new `release` branch. The following picture illustrates it (main branch is the `master` branch and your branch is the `release` branch, [source](https://www.mohammedasker.com/explaining-how-git-rebase-works-in-laymans-terms-%F0%9F%8D%95-%F0%9F%A5%91-%F0%9F%8D%96)):
> 
> image
> 
> 1. Force push the new `release` branch to GitHub.
> 2. Revert the temporary configuration of the branch protection rules on the `release` branch, to disable force pushes.
> 
> If additional commits need to be made to the `release` branch, the usual pull request workflow to the `release` branch is sufficient. If there are any conflicts during step 3, they can be resolved locally by the person making the release. This also means that only administrators have the ability to make new releases (since the branch protection rules need to be changed in step 2).
> 
> I think this way allows us to maintain the integrity of the `release` branch and no additional pull requests need to be made for every new release. It should also be less error prone as the custom changes on the `release` branch do not have to be made every time a release happens. @HCY123902 and Prof @damithc what do you think?

Actually, it is possible to just release with the master branch? Currently, the purpose of the release branch is to make it more convenient to publish documentation at `reposense.org`. However, the fact that `reposense.org` is an organization site means it may only be possible to modify `reposense.org` in https://github.com/reposense/reposense.github.io, which makes the `release` branch less meaningful than intended.

It may be more convenient just to release with the master branch, and then deploy the documentation to the `reposense.github.io` repository. There is no `release` branch involved in this case

**Comment by damithc** [comment]
> Actually, is it possible to just release with the master branch?

A release branch is useful when we need to hot-patch a previous release to fix a critical bug. In that case, the PR can come against the release branch rather than the master branch.

The release is usually done by someone with admin permissions, which means merging master to release doesn't need a PR.

While rebasing the release branch is possible, I  think it is more common to maintain two parallel branches, which shows the release history more visually, including hot-patches.

@fzdy1914 can weigh in too.

**Comment by HCY123902** [comment]
I agree that direct merging will make release more convenient. However, it seems that I currently do not have access to merge and then directly push the changes to the release branch, or rebase it

**Comment by damithc** [comment]
> I agree that direct merging will make release more convenient. However, it seems that I currently do not have access to merge and then directly push the changes to the release branch, or rebase it, without creating this pull request. Can I propose to merge this pull request first? After merging and publishing `reposense.org`, I will modify the `site.json` in the release branch and the release guide

@HCY123902 I've removed protection from the `release` branch. You should be able to push to it now.

**Comment by damithc** [comment]
@HCY123902 Next time, do a normal merge locally and push (not via a PR). No need for a lengthy commit message as merging master to release is simply a default step of releasing a new version.

**Comment by HCY123902** [comment]
Noted. Many thanks

**Comment by damithc** [comment]
BTW, something is not right with the revision tree. I don't see a merge commit showing where master branch was merged to the release branch.

**Comment by HCY123902** [comment]
Oh the merge is fast forwarded. There is no additional commit created by the merge. Should I reset and merge again? Really sorry for not noticing this

**Comment by damithc** [comment]
> Oh the merge is fast forwarded. There is no additional commit created by the merge. Should I reset and merge again? Really sorry for not noticing this

No worries. We can leave it be. Next time, use a merge commit.

**Pull request merged**
