### PR TITLE
[#954] RepoConfiguration: remove redundant usage of streams

### LINKED ISSUE #954: RepoConfiguration: redundant usage of streams when setting isStandaloneConfigIgnored attribute
In the `setStandaloneConfigIgnoredToRepoConfigs` method of `RepoConfiguration`, 
we iterate through a list of `RepoConfiguration` objects and modify the `isStandaloneConfigIgnored` attribute in each object.

This is currently done use the `Stream.foreach()` method, but it could be done using the `forEach` that is available to Lists.

https://github.com/reposense/RepoSense/blob/c6ffecd214e73fc8ecf97a742108af5ac6d2ceab/src/main/java/reposense/model/RepoConfiguration.java#L181-L184

Line 181 could be rewritten as:
```
configs.forEach(config -> config.setStandaloneConfigIgnored(isStandaloneConfigIgnored));
```

### PR DESCRIPTION
**Pull request by litone01**
Fixes #954.

Commit message:
```
In the setStandaloneConfigIgnoredToRepoConfigs method of
RepoConfiguration, we iterate through a list of RepoConfiguration
objects and modify the isStandaloneConfigIgnored attribute in each
object. Currently, we use Stream.forEach(), which can be replaced by a
list.forEach() method since we already have a list.

Let's replace the redundant Stream.forEach() with the .forEach()
method.
```

### CODE REVIEW

**Comment by litone01** [comment]
Requesting review @dcshzj Thanks!

**Review by dcshzj — CHANGES_REQUESTED** [review]
Thanks @litone01 for your contribution! Some comments about the PR:
1. The proposed commit message and the PR description is the same, so it is alright to leave out the PR description and keep it in the proposed commit message.
2. There is a slight typo in the proposed commit message. `Stream.foreach()` should be written as `Stream.forEach()`.
3. In the call-to-action part of the commit message (last paragraph), use a full stop instead of an exclamation point.

Other than that, this is a simple PR, so there are no other comments on the code. Feel free to work on a slightly tougher first-timer issue if you wish, or another issue if you are more confident.

**Comment by dcshzj** [comment]
> PS I wander if it is normal that I cannot add labels and request for reviews for my first PR?

As for this, yep. External contributors are not able to add labels on PRs, so don't worry about it.

**Comment by litone01** [comment]
> Thanks @litone01 for your contribution! Some comments about the PR:
> 
> 1. The proposed commit message and the PR description is the same, so it is alright to leave out the PR description and keep it in the proposed commit message.
> 2. There is a slight typo in the proposed commit message. `Stream.foreach()` should be written as `Stream.forEach()`.
> 3. In the call-to-action part of the commit message (last paragraph), use a full stop instead of an exclamation point.
> 
> Other than that, this is a simple PR, so there are no other comments on the code. Feel free to work on a slightly tougher first-timer issue if you wish, or another issue if you are more confident.

Thanks @dcshzj I agree that this is a very simple PR. Maybe I should go with another more complicated first timer issue. Will pick another one in the next few days and notify the developer teams. Thanks!

**Review by dcshzj — APPROVED** [review]
LGTM!

**Review by fzdy1914 — APPROVED** [review]

**Pull request merged**
