### PR TITLE
[#1485] Watch tab info directly

### LINKED ISSUE #1485: Error in connection between chart panel and code panel.
Can check the video below. 
1: The file-breakdown doesn't go away from the commits panel though the commit goes.
2: On restoring, the ramp appears first but the commits don't appear. 

https://user-images.githubusercontent.com/35946746/111701934-81322e00-8876-11eb-8e08-d61844cf85b9.mov

### PR DESCRIPTION
**Pull request by gerhean**
Resolves #1485
```
Regression by #1390.

Currently zoom tab does not update properly if one of the
zoom watchables do not change.

Let's watch the tabZoomInfo stored in vuex instead of 
zoomOwnerWatchable.

This works as we ensure that every change to tabZoomInfo 
stored in vuex replaces tabZoomInfo with a new object. 

Hence watching the object pointer stored in tabZoomInfo 
is sufficient.

Everything here also applies to the authorship tab with
authorshipOwnerWatchable and tabAuthorshipInfo instead.
```

Changes in behavior:
Clicking on an already highlighted zoom/authorship tab icon on the summary chart will reset the tab even if there is no changes to summary chart.

### CODE REVIEW

**Comment by damithc** [comment]
Lines in the proposed commit message seem too short i.e., premature line wrapping

**Comment by gerhean** [comment]
I have increased the length thanks.

**Comment by HCY123902** [comment]
Not sure about the original specified behavior. However, unticking a checkbox in the break down file type does not seem to synchronize the corresponding file type in the zoom panel

**Comment by gerhean** [comment]
@HCY123902 I believe that the zoom tab has never actually been responsive to changes in summary-charts until the zoom tab has been reloaded. Hence your suggestions seems more like a new feature? Similarly, changing the date range in summary does not affect the zoom tab.

**Review by HCY123902 — APPROVED** [review]

**Review by HCY123902 — APPROVED** [review]
I think this pull request can be merged before #1490 because it seems that #1490 is indeed handling a slightly different issue

**Review by 0blivious — APPROVED** [review]
Please change the PR title according to the DG

**Pull request merged**
