### PR TITLE
Github Action for Closing Stale PRs

### PR DESCRIPTION
**Pull request by Tejas2805**
``` 
Few PRs are left open for a long time without any follow-up activity 
from the author of the PRs. This prevents other developers from 
taking up the issue and solving it. Therefore, the senior developers 
need to find such PRs manually and close them.

Let's automate the process of closing inactive PRs using GitHub Actions.
```

### CODE REVIEW

**Comment by jamessspanggg** [comment]
@eugenepeh might need you to add the access token as a secret

**Comment by Tejas2805** [comment]
> LGTM, we would have to create a `GITHUB_TOKEN` secret so that u can use this workflow right

I think that it will be required.

**Comment by eugenepeh** [comment]
From the [GitHub Action Docs](https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#:~:text=and%20use%20secrets.-,About%20the%20GITHUB_TOKEN%20secret,GitHub%20App%20on%20your%20repository.&text=The%20token%20expires%20when%20the%20job%20is%20finished.)

```
GitHub automatically creates a GITHUB_TOKEN secret to use in your workflow. 
You can use the GITHUB_TOKEN to authenticate in a workflow run.
```

Hmm, doesn't seems like its needed to create this token.
Could you test it out in another repository?

**Comment by jamessspanggg** [comment]
@Tejas2805 have u tried it in your repo?

**Comment by Tejas2805** [comment]
> @Tejas2805 have u tried it in your repo?

Yup have. This is the [link](https://github.com/Tejas2805/Github-Actions)

**Comment by jamessspanggg** [comment]
> Yup have. This is the [link](https://github.com/Tejas2805/Github-Actions)

Ok, you did not need to setup the GITHUB_TOKEN right?

**Comment by Tejas2805** [comment]
> Ok, you did not need to setup the GITHUB_TOKEN right?

Oh, thought you were asking if it works. Yup, don't need to set GITHUB_TOKEN for actions related to PR, Issues, and more. Just checked documentation too.

**Comment by Tejas2805** [comment]
@fzdy1914 If all okay, can merge this?

**Comment by eugenepeh** [comment]
@Tejas2805 it seems to be failing

**Comment by fzdy1914** [comment]
Yep, seems to be failing.

**Comment by jamessspanggg** [comment]
The PR has been reverted to prevent the failures and spam emails. The failure has the following log, @Tejas2805 can you investigate on it:

Screen Shot 2020-08-02 at 2 35 01 PM

**Comment by Tejas2805** [comment]
@jamessspanggg @fzdy1914 I don't have access but can you guys check if this is enabled? 

image

**Comment by Tejas2805** [comment]
> @jamessspanggg @fzdy1914 I don't have access but can you guys check if this is enabled?
> 
> image

If this is enabled, then need to switch to - Enable local and third-party Actions for this repository.

**Comment by fzdy1914** [comment]
@Tejas2805 So `actions/stale@v3.0.7` this is a third party action?

**Comment by fzdy1914** [comment]
@Tejas2805 
image

Is this enough?

**Comment by Tejas2805** [comment]
> @Tejas2805 So `actions/stale@v3.0.7` this is a third party action?

Actually when they say local they mean - actions for which the code is written within the repository or organization itself.

**Comment by Tejas2805** [comment]
> @Tejas2805
> Is this enough?

Should be okay.

**Comment by Tejas2805** [comment]
Do we want the Actions to work on all PRs (current implementation) or PRs to the master branch only?

**Comment by fzdy1914** [comment]
Can we exempt for draft PRs like #1096?

**Comment by Tejas2805** [comment]
> Can we exempt for draft PRs like #1096?

We can exempt them by adding a label to the PR. And exempt PRs with those labels from being closed. Does the label - s.DoNotMerge - work?

**Pull request merged**
