### PR TITLE
[#1005,#1010] Code Panel: match font with GitHub and break lines when overflow

### LINKED ISSUE #1005: Code Panel: Large empty space when author has edited a file with a long filepath
When an author has contributed to a file with a long filepath, a large empty space is seen in the Code Panel, in order to accomodate the length of the filepath.

largeEmpty

Suggestion: Show filepaths in a separate scrollable div

### PR DESCRIPTION
**Pull request by jamessspanggg**
Fixes #1005 and #1010 

```
When the file path or lines of code overflows, it takes up a 
large amount of empty space in order to accomodate to 
it's length. The font size of the code and file path is also 
rather big and takes up much space.

Let's set the file path and lines of code to break into next 
lines when it overflows. Also, let's set the font-family 
and font-size of the code to match with GitHub.
```

- [x] break file path or lines of code to next line when overflow
- [x] match font family and font size with GitHub's
- [x] decrease the size of the file path
- [x] ~~match the font sizes of group title in summary panel and file title in code panel~~
- [x] ~~match the font styles and sizes between code panel and commit panel~~

### CODE REVIEW

**Comment by Tejas2805** [comment]
Since this is similar to #1010 can fix that also in this PR as well ?

**Comment by fzdy1914** [comment]
Break word seems a little bit weird for text.

**Comment by jamessspanggg** [comment]
> Break word seems a little bit weird for text.

You mean for the path or the code? 

For the path, since the path will be a continuous text: e.g. `src/webapp/util.js`, I think it is fine to break it in terms of each character.

As for the code, I have modified the code to break in terms of each word instead of character.

**Comment by fzdy1914** [comment]
> As for the code, I have modified the code to break in terms of each word instead of character.

Yes, that's what I mean.

**Comment by Tejas2805** [comment]
@jamessspanggg the Prof wanted consistency between the Code Panel and Commit Panel. As suggested by him, can you make the font sizes between the two views same too?

**Comment by jamessspanggg** [comment]
@Tejas2805 may I ask specifically which fonts should be standardised?

**Comment by Tejas2805** [comment]
> @Tejas2805 may I ask specifically which fonts should be standardised?

`Group title` and `file title`

**Comment by jamessspanggg** [comment]
> `Group title` and `file title`

Ok done.

**Comment by Tejas2805** [comment]
@jamessspanggg Though all CSS is the same, the fonts look different in Ui. What do you think?

**Comment by jamessspanggg** [comment]
> @jamessspanggg Though all CSS is the same, the fonts look different in Ui. What do you think?

Do you mean the font for the segments of code? Prof asked me to follow the font-family and font-size of GitHub's code.

**Comment by Tejas2805** [comment]
@jamessspanggg Is this PR ready?

**Comment by jamessspanggg** [comment]
> there seems to be some discrepancy in the font among the ui now, especially commit view which is supposed to be standardized with authorship.
> Can you apply the change to commit view as well?

I have standardised the title fonts and sizes between commit and authorship view. 

For the commit message body in commit view, monospace font is used to show the length of the commit message bodies, as each character represents a space. So I'm unsure if the change of font is needed.

**Comment by jamessspanggg** [comment]
may revert the changes in zoom view as #1048 requires to change the font of commit message title to be `monospace`.

**Comment by eugenepeh** [comment]
Sorry for the delay in response, let's review this again once #1048 is merged

**Comment by jamessspanggg** [comment]
Reverted the changes in zoom. Ready for review.

**Comment by jylee-git** [comment]
@damithc your thoughts on the UI changes?

**Comment by damithc** [comment]
> @damithc your thoughts on the UI changes?

Looks fine to me 👍

**Pull request merged**
