### PR TITLE
[#1929] Add dynamic positioning support for tooltips

### LINKED ISSUE #1929: Add dynamic positioning support for tooltip
### What feature(s) would you like to see in RepoSense

Currently, most tooltips are shown above buttons and text. When these tooltips appear at the top of the viewport, part of the tooltips will not be rendered.

image

A previous pull request #1860 has implemented a solution to add dynamic positioning support for collapse file tooltips so that they will move below the title when appearing at the top of the viewport. The same changes can be applied to the other tooltips as well, including those on the chart panel, authorship contribution panel, and commits panel.

### If possible, describe the solution

A possible solution has been proposed in #1860

### PR DESCRIPTION
**Pull request by pratham31012002**
Fixes #1929 

### Proposed commit message

```
Currently, most tooltips are shown above buttons and text. 
When these tooltips appear at the top of the viewport, 
part of the tooltips will not be rendered.

Let's implement changes such that these tooltips appear below the
text or button, when appearing at the top of the viewport.
```

### Other information

The changes were implemented in a manner similar to #1860. However, since this functionality was required across multiple components, a mixin was created in `dynamicTooltipMixin.ts` for the shared methods for this functionality.

Illustration:
Tooltip below the viewport:
image
Tooltip at the viewport:
image

### CODE REVIEW

**Comment by pratham31012002** [comment]
Kindly requesting your attention to review this pending PR at your earliest convenience.

**Review by ckcherry23 — APPROVED** [review]
Great work! LGTM

**Comment by pratham31012002** [comment]
Kindly requesting your attention to review this pending PR at your earliest convenience.

**Review by MarcusTXK — APPROVED** [review]
Apologies for the late review. LGTM, nice job!

**Pull request merged**
