### PR TITLE
[#463] Add sorting of ramp chart by repo contribution

### LINKED ISSUE #463: Ramp chart: allow sorting by total team contribution
Current: ramp chart can be sorted by individual contribution

image

Suggestion: also allow sorting by total team contribution so that more active teams can be identified easily

### PR DESCRIPTION
**Pull request by chelseyong**
Fixes #463.
```
Ramp charts can only be sorted by individual contribution.

Let's allow users to sort ramp charts by repo contribution so that more active repos 
can be identified.
```

### CODE REVIEW

**Comment by eugenepeh** [comment]
Hmm not sure if this is what Prof means.

I think it should be sorted by repositories automatically when the `group` checkbox is checked?
need clarification from you, @damithc

**Comment by damithc** [comment]
> I think it should be sorted by repositories automatically when the `group` checkbox is checked?
> need clarification from you, @damithc

This is a tricky situation. Normally, the sorting criterion is applied within the group, if `group` is ticked. As `Repo contribution` is applicable only when `group` is ticked, maybe auto-tick the `group` when that sort criterion is selected? I can't think of a clean solution because there are two sort levels (within group, and overall) and some sort criteria are linked to other settings.

**Comment by chelseyong** [comment]
@damithc Currently, if it is not grouped by repo, sorting order will still be the same, the only difference being each ramp chart is labelled with the repo name.
image
So I think this is not very significant?
Another solution would be to disable the un-selection of the `group by repo` button when `repo contribution` is chosen as sorting criteria.

**Comment by damithc** [comment]
@chelseyong is this PR still relevant?
There seems to be a way to sort groups by the contribution in the current version.
image

**Comment by chelseyong** [comment]
Yes, it has been resolved in #639.

**Pull request closed without merging**
