### PR TITLE
[#1004] Make Authorship Panel consistent with Chart Panel

### LINKED ISSUE #1004: Inconsistency between Chart Panel and Authorship Panel
The current Chart Panel and Authorship Panel use different font size, color, background color and header height. As suggested by Prof, we can try to make the 2 panels more similar to make the website look more consistent.

### PR DESCRIPTION
**Pull request by Tejas2805**
Fixes #1004

### CODE REVIEW

**Comment by Tejas2805** [comment]
@damithc What do you think of the Ui?
 Based on our discussion, have followed github's style for file-header and made panels white

**Comment by damithc** [comment]
GitHub UI has a way to clearly separate each file. We need to have something similar. As of now we have a horizontal line but that seems to separate the filename from the code, rather than showing where a file ends.

image

**Comment by Tejas2805** [comment]
Screen Shot 2020-02-10 at 8 47 45 AM

@damithc What do you think

**Comment by damithc** [comment]
> @damithc What do you think?

As Github does, use a very light grey for the box containing the file name?

**Comment by Tejas2805** [comment]
@damithc I have added the Github colour. I have also suggested two options for borders. Let me know how to proceed.

1) 
Screen Shot 2020-02-11 at 2 59 05 AM


2) 
Screen Shot 2020-02-11 at 3 21 18 AM

**Comment by damithc** [comment]
Option 2 looks better. May be reduce the thickness of the border between the filename and the content as there is no reason for it to be thicker than others?

**Comment by Tejas2805** [comment]
Screen Shot 2020-02-11 at 7 25 22 PM

@damithc For review. Will proceed accordingly then.

**Comment by damithc** [comment]
Are you able increase the curvature at the top and bottom corners like this? No curve for the middle one.
image

**Comment by Tejas2805** [comment]
The initial one was 2.

Current top: 4
Current bottom: 8

Screen Shot 2020-02-11 at 8 23 46 PM

**Comment by damithc** [comment]
> Current top: 4
> Current bottom: 8

let's make both 4 as there is no logical reason to make them different.

**Comment by Tejas2805** [comment]
Closing this PR due to some issues. Have re=opened in #1080

**Pull request closed without merging**
