### PR TITLE
[#1933] Fix broken DevOps Guide link in Learning Basics

### LINKED ISSUE #1933: Link to DevOps guide is broken
### What problem(s) did you run into that caused you to request additional documentation? What, if any, existing documentation relates to this proposal?

1. Under the [DevOps section in the developer guide](https://reposense.org/dg/learningBasics.html), the link to DevOps guide leads a Wiki link instead of redirecting to the DevOps guide on the actual Reposense website.
2. This is likely due to #1548, where the DevOps guide was shifted from Wiki to DG but the learning basics page itself was not updated.

### What would you like added or modified in the documentation?

1. Fix the broken link
2. If possible, look through the entire Reposense documentation for any other possible broken links.

### PR DESCRIPTION
**Pull request by supermii2**
Fixes #1933

```
Fix broken link to DevOps Guide in Learning Basics page.

Under the DevOps section in the developer guide,
the link to DevOps guide leads a Wiki link instead of redirecting to
the DevOps guide on the actual Reposense website.

Let's fix the broken link by changing the address to the correct page.
```

### CODE REVIEW

**Review by ckcherry23 — APPROVED** [review]
LGTM

**Review by sopa301 — APPROVED** [review]
LGTM!

**Review by gok99 — APPROVED** [review]
LGTM

**Comment by ckcherry23** [comment]
Hi @supermii2, can you format your commit message body according to these guidelines?
https://se-education.org/guides/conventions/git.html#commit-message-body

Specifically, wrap the message body at 72 characters. You can utilise online tools for this.

**Comment by supermii2** [comment]
Fixed! Thank you for pointing this out

**Pull request merged**
