### PR TITLE
Fix missing space and use of raw types

### PR DESCRIPTION
**Pull request by chan-j-d**
Fixes some minor issues I found while working on other pull requests.
1. removed use of raw types
2.  add missing space from error message in `CommandRunnerProcess::waitForProcess()`

Commit Message:
```
Fix missing space and use of raw types

There are multiple occurrences of use of raw type within the code
which results in compilation warnings. Additionally, there is a 
missing space in one of the error messages.

Let's address these minor issues in the code.
```

### CODE REVIEW

**Comment by damithc** [comment]
@chan-j-d thanks for fixing this. Can use a more specific name ('minor issue' is too generic) for PR and commit message?

**Comment by chan-j-d** [comment]
Ok, will change it now

**Comment by chan-j-d** [comment]
Ready for review

**Review by HCY123902 — APPROVED** [review]

**Comment by HCY123902** [comment]
LGTM. Similar to #1566, I suggest separating this into 2 individual pull requests since it is handling 2 separate issues. The reason why pull request needs to be atomic is that this can help to keep a clear record of what work is done for each issue and enable future contributors to know the previous progress

**Comment by chan-j-d** [comment]
Thank you for the suggestion! Will take note of it for future pull requests.

**Review by Tejas2805 — APPROVED** [review]
LGTM!

**Review by fzdy1914 — APPROVED** [review]

**Pull request merged**
