### PR TITLE
[On hold] generating daily view from raw commits. relies on #168, #157

### PR DESCRIPTION
**Pull request by ongspxm**
part of #134, depends on #157, #168

```
Currently, all the commit information is formatted and processed during
the report generation and the dashboard only used for the displaying of
the information.

This means that to support both daily and weekly view, the details for
the different views will all have to be generated and stored as part of
the report. This duplicated information artifically increases the size
of the report as well, without providing much additional information.

Let's shift to generating and storing only the raw commits of the
project, then generate the day view for the summary module from the raw
commit information.
```

### CODE REVIEW

**Comment by damithc** [comment]
Does this result in shifting some logic from java to js, or the shift is within js?

**Comment by ongspxm** [comment]
yep, this shifts the consolidating of the daily insertion and deletion from java to js. this is an extension of a comment in #134, where it is suggested to generate the weekly view from the daily view. 

considering we are gonna have per-commit view as our lowest level (smallest) view, it would be natural to base our daily and weekly view off the raw data for consistent results.

**Comment by damithc** [comment]
hmm... I'm not that keen to move critical logic to js, or to move too much work to the browser. Java is a better place to keep logic for ease of testing. Generating files is a one-time cost and the report viewer is not affected. The more we try to generate things on the fly on the browser side, the more it will affect the end-user experience.

**Comment by yamidark** [comment]
@ongspxm Do update your PR to the `per-commit-view` branch.

**Comment by ongspxm** [comment]
closing this due to requirement changes.

**Pull request closed without merging**
