### PR TITLE
 Dashboard: add an indicator to code view

### PR DESCRIPTION
**Pull request by ongspxm**
part of #259 

```
New users are confused as to how to view the code from an author.

Let's add a tooltip to the ramp chart title so that new users can
intuitively know how to view code.
```

### CODE REVIEW

**Comment by ongspxm** [comment]
this tooltip is similar to github's header link in the markdown view. please check if appropriate.

image
the link icon available on hover

**Comment by ongspxm** [comment]
@damithc do give a check on netlify to see if okay

**Comment by damithc** [comment]
> @damithc do give a check on netlify to see if okay

1. I prefer to have it as a proper tool tip if that is possible. That is, the tip is a callout _from/near_ the icon, or at least together with the icon rather than split the icon and the text.
Example:
image

2. If not possible to have both _before_ the name, can consider having both _after_ the name.

**Comment by ongspxm** [comment]
image

in that case, i will be using the browser default title tag for this feature, it will look something like that

**Comment by damithc** [comment]
> couldn't get the cursor in the screenshot, but it is at the title of of the ramp chart
> 
> in that case, i will be using the browser default title tag for this feature, it will look something like that

Sure. 
I have to say I find it more intuitive if the icon comes after the name, but that could be just me.
Also, I prefer if the icon is visible all the time, as opposed to appearing on hover. The whole purpose of this feature is to tell the user that there is a way to see the code, without user having to read the user guide. If the icon appears only on hover, we leave it to the chance that user will discover the feature by accident.

**Comment by ongspxm** [comment]
> I have to say I find it more intuitive if the icon comes after the name

i could do that, but it looks a little ugly, because the icon will then be unaligned.
image

**Comment by damithc** [comment]
> i could do that, but it looks a little ugly, because the icon will then be unaligned.

Let's do that in this version. We can tweak in a future version if required.

**Comment by ongspxm** [comment]
> Also, I prefer if the icon is visible all the time, as opposed to appearing on hover.
image
Also possible, but the icon will look like a bullet point instead, okay?

**Comment by damithc** [comment]
> Also possible, but the icon will look like a bullet point instead, okay?

Not applicable as we'll show the icon at the end of the name.

**Comment by ongspxm** [comment]
donez

**Comment by eugenepeh** [comment]
Proposed message tweak:

```
New users may not know all the functionalities that are available to
them, hence hidden functionality such as code view may go unnoticed.

To enhance our user friendliness, let's add a tool-tip and icon to the
ramp chart title so that the code view feature stands out more by
intuitive.
```

**Pull request merged**
