### PR TITLE
Model: Add ReportConfiguration

### PR DESCRIPTION
**Pull request by fzdy1914**
Related #590, #467 

Our user cannot edit the property of generated report.

Let's add a new model, ReportConfiguration, which serves the role to
configure the generated report.

### CODE REVIEW

**Comment by fzdy1914** [comment]
@eugenepeh @yamidark 
As this is a totally new component, so I would like to ask for your opinion on the implementation of this pr.

For my implementation, I suppose that the report-config.json should under the same folder with the other two configs, which means, this feature only works with `ConfigCliArgument`. 

There is also another possible implementation. We add one more arg e.g. `--report-config` to specify the location of the folder and put all the file related to the report config in it.

**Comment by eugenepeh** [comment]
>For my implementation, I suppose that the report-config.json should under the same folder with the other two configs, which means, this feature only works with ConfigCliArgument.

I think we can go with that for now. `--repo` is usually meant for few repositories, so its not that important to add support for it yet.

**Comment by fzdy1914** [comment]
Put this PR on hold as there is no time to finish it.

**Comment by fzdy1914** [comment]
Anyone who is willing to take over the PR can just go ahead.

**Comment by fzdy1914** [comment]
Closing this PR because it has been inactive for a very long time. For the contributors who are willing to take over, you may just use the code here as a start point.

**Pull request closed without merging**
