### PR TITLE
[#1485] Make file types selection consistent across panel

### PR DESCRIPTION
**Pull request by HCY123902**
Part of #1485 

Commit message:
```
Synchronize the file types in zoom panel with the file types in
the summary view

The file types in zoom panel currently do not change actively
when the file type filtering condition in the summary view is
changed.

Making the file types on zoom panel change with the file types
in the summary view can enhance the consistency between
different interface components.

Let's synchronize the zoom panel with the summary view.
```

### CODE REVIEW

**Comment by gerhean** [comment]
Don't really agree, I believe my fix #1490 is cleaner.

**Review by fzdy1914 — COMMENTED** [review]
PR duplicated with #1490 and #1491 ?

**Comment by HCY123902** [comment]
> PR duplicated with #1490 and #1491 ?

There seems to be some slight difference between #1490 and #1491 in the sense that #1491 restores the original implementation of how zoom tab is updated when `tabZoomInfo` is changed and it restores the original behavior. #1490 synchronizes the change in break down file types with the file types in the zoom panel immediately after the checkbox in break down by file types are ticked or unticked. This change is made because I interpret that #1485 points out a need to synchronize the file types in the summary view and the file types in the panel responsively.

**Comment by 0blivious** [comment]
This disconnection was actually the intended design. The idea is, we wish to separate the tab from the summary view and not updating it until we click to open a new zoom panel. Thus, I am not sure if this PR is necessary.

@damithc may I get your opinion on this change?

**Comment by damithc** [comment]
> This disconnection was actually the intended design. The idea is, we wish to separate the tab from the summary view and not updating it until we click to open a new zoom panel. Thus, I am not sure if this PR is necessary.
> 
> @damithc may I get your opinion on this change?

Are we talking about the chart panel and the code panel? Let's use these terms consistently (those are the names used in the UG https://reposense.org/ug/usingReports.html#report-structure), irrespective of the terms used in the code.

Yes, no need to link them up. The more we link different things, the more susceptible they are to break. 

On a related note, it is better to discuss and get the greenlight before implementing a feature. That will reduce the chance of a PR not getting merged down the line.

**Comment by Tejas2805** [comment]
> This disconnection was actually the intended design. The idea is, we wish to separate the tab from the summary view and not updating it until we click to open a new zoom panel. 

If you see the video I have posted for the issue, the error is in the fact, that the commits are removed but the file types are still on display. Therefore it should either be that both are not removed or both are removed together. Removal of just one might cause the user to be confused, is my opinion. And that's why I created an issue calling it a bug.

**Comment by 0blivious** [comment]
> If you see the video I have posted for the issue, the error is in the fact, that the commits are removed but the file types are still on display in the Commits Panel when I click to open the Commits Panel. Therefore it should either be that both are not removed or both are removed together. Removal of just one might cause the user to be confused, is my opinion. And that's why I created an issue calling it a bug.

The bug should be handled in #1490. This PR looks more like a new feature to me.

**Comment by damithc** [comment]
> If you see the video I have posted for the issue, the error is in the fact, that the commits are removed but the file types are still on display in the Commits Panel when I click to open the Commits Panel. Therefore it should either be that both are not removed or both are removed together. Removal of just one might cause the user to be confused, is my opinion. And that's why I created an issue calling it a bug.

Yes, that sounds like a bug. Either the panel should be fully disconnected, or fully connected. It's simpler if we keep it disconnected? Is there a significant value in keeping it connected?

**Comment by 0blivious** [comment]
> Yes, that sounds like a bug. Either the panel should be fully disconnected, or fully connected. It's simpler if we keep it disconnected? Is there a significant value in keeping it connected?

I don't really see much value in making them connected. Would prefer the fully disconnected one.

**Comment by fzdy1914** [comment]
Closing the PR as the discussion should have reached a conclusion.

**Pull request closed without merging**
