### PR TITLE
[#944] Fix wrong credit information inherited by annotated author

### PR DESCRIPTION
**Pull request by SkyBlaise99**
Part of #944

### Proposed commit message

```
AnnotatorAnalyzer only overwrites the author but not the credit
information, when an author tag is found. If the analyze authorship
flag is enabled, credit information based on the blame author will be
wrongly inherited by the annotated author.

Lets assign partial credit if the annotated author is not the same as
the blame author, and keep the analyzed credit information if the 2
are the same.
```

### CODE REVIEW

**Comment by SkyBlaise99** [comment]
The frontend tests are failing even though this PR did not touch the frontend at all. Seems to be because of #2066.
And codecov seems to refuse to work. #2067 proves that nothing is wrong with this PR.

**Comment by SkyBlaise99** [comment]
codecov is working now, I tried the fix in #2066 but that didn't work.

**Comment by SkyBlaise99** [comment]
Can someone review and merge this? Thanks!

**Review by chan-j-d — APPROVED** [review]
LGTM!

**Pull request merged**
