### PR TITLE
[#1201] Fix regressions of PR #779

### LINKED ISSUE #1201: Wrong repo name displayed and invalid links to commits when merging by author
When `group by` is set to `author` and `merge group` is selected, the commits panel still shows the name of the first repo, although the commits do not belong to it. Also, clicking on commits which do not belong to the repo being shown directs to a GitHub 404 page because of wrong URL.

image

Clicking the first link (`Add zero bottom margin to last child of tip boxes (#133)`):
image
Note the wrong URL being joined. The correct URL should be https://github.com/markbind/vue-strap/commit/cc4c4d327625b89d0c960b03b97454ead3b80419.

### PR DESCRIPTION
**Pull request by jamessspanggg**
Fixes #1201 

```
There are regressions caused by PR #779, where the zIsMerge and 
zFilterGroup properties are not used properly within zoom tab.
They are using isMergeGroup and filterGroupSelection instead.

Let's modify them to use zIsMerge and zFilterGroup instead, in this 
way the zoom tab will be using the correct property values.
```

### CODE REVIEW

**Comment by niqiukun** [comment]
image

Besides the link to GitHub commits, I think it may be better to replace the repo name (highlighted in pic) with the author's name instead? Since the commits panel should show commits across all repositories, the title can be misleading.

**Comment by jamessspanggg** [comment]
> Besides the link to GitHub commits, I think it may be better to replace the repo name (highlighted in pic) with the author's name instead (when group by author + merge group)? Since the commits panel should show commits across all repositories, the title can be misleading.

Ahhh, okay noted. It's due to the same regression. Thanks!

**Comment by Tejas2805** [comment]
> image
> 
> Besides the link to GitHub commits, I think it may be better to replace the repo name (highlighted in pic) with the author's name instead (when group by author + merge group)? Since the commits panel should show commits across all repositories, the title can be misleading.

@jamessspanggg Was referring to this too.

**Comment by jamessspanggg** [comment]
@eugenepeh may i get your review on this? This issue is currently affecting the users, where clicking on ramps in the zoom tab does not bring them to the correct commit

**Comment by jamessspanggg** [comment]
@fzdy1914 ready to merge

**Pull request merged**
