### PR TITLE
Upgrade Gradle to 7.6.1

### PR DESCRIPTION
**Pull request by yhtMinceraft1010X**
### Proposed commit message

```
The latest Gradle 7 version is 7.6.1. This release includes the ability
to re-run tasks individually.

Let's upgrade to Gradle 7.6.1.
```

### Other information

Release notes for [Gradle 7.6.1](https://docs.gradle.org/7.6.1/release-notes.html)

### CODE REVIEW

**Review by MarcusTXK — APPROVED** [review]
LGTM

**Comment by chan-j-d** [comment]
Wanted to check, are the changes to gradlew and gradlew.bat automated or manual?

**Comment by yhtMinceraft1010X** [comment]
> image
> 
> LGTM! But can I also check if it is not necessary to update the wrapper version stated in `build.gradle`? It seems like this PR doesn't change the wrapper version to match.

Thanks for pointing it out. I will fix this by saturday.

**Comment by yhtMinceraft1010X** [comment]
> Wanted to check, are the changes to gradlew and gradlew.bat automated or manual?

They are automatic. I just run `gradlew wrapper --gradle-version 7.6.1` and all the changes happen there

**Review by chan-j-d — APPROVED** [review]
LGTM!

**Review by dcshzj — APPROVED** [review]

**Pull request merged**
