### PR TITLE
[#1874] Use clearer author names in test template

### LINKED ISSUE #1874: Update unconventional author names to match logic in GitTestTemplate.java
**What feature(s) would you like to see in RepoSense?**

Following the changes made in #1857, the author names in GitTestTemplate.java do not match what they should signify (unconventional author name is currently -invalidGitUsername_TreatedAsUnknownUser, and whitespace author name is harryggg invalidAuthorLineFormat).

**Is the feature request related to a problem?**

As there is a mismatch between variable name and the value it stored, it can cause unnecessary confusion to developers as to which should be the correct representation (does -invalidGitUsername_TreatedAsUnknownUser mean something else apart from being unconventional?). Admittedly this is not a important change, as the developers should be able to understand the intentions just fine, however this is bad code quality and should be cleaned up.

This issue was also discussed in the aforementioned PR:
image

**If possible, describe the solution**
The most direct solution is to simply update the author names within `GitTestTemplate.java`. However, due to `AnnotatorAnalyzerTest.java`'s reliance on [testrepo-Alpha](https://github.com/reposense/testrepo-Alpha) to provide an example file (`annotationTest.java`) for authorship tag testing which cannot be updated in the same PR due to them existing as different repos, separate but synchronized PRs must be made, one which updates `GitTestTemplate.java` with the updated and more representative author names, one which updates `annotationTest.java` with the new authorship tags and correct content.

Pre-generated RepoSense report JSON files in systemtest -> resource -> LocalRepoSystemTest must also be appropriately updated with the new authors and content. It is much easier to update these JSON files manually for the time being rather than to generate them (locally or not) since 1) commits have to be made to testrepo-Alpha first; 2) RepoSense generates the JSONs through git commit history, so the commits.json may be inaccurate when testrepo-Alpha is updated. The expected changes are minimal and simple (changes from -invalidGitUsername_TreatedAsUnknownUser to -unconventional_author- in only one path `annotation.java` for example). These changes can be observed and checked easier by pretty printing the JSON files.

**Additional information**
After the above described PR is commited to testrepo-Alpha, `AnnotatorAnalyzerTest.java` should work the same since it uses a SINCE_DATE and UNTIL_DATE to demarcate its start and end to clone and test from. The new commit not found in the (above described) JSON files should not affect it. We can adjust these after the PR is commited to testrepo-Alpha, or maybe even explore other means such that we do not rely on such "timestamped" JSON files to perform our testings.

### PR DESCRIPTION
**Pull request by sikai00**
Fixes #1874 

## Proposed commit message
```
The names used for unconventional author and white space author do not
reflect its meaning correctly and may cause confusion for developers
when reading through the code.

Let's update the names in GitTestTemplate to accurately and better
reflect the meaning of unconventional author and whitespace author.
```

## Other information

This PR follows the changes made by #1857 

This PR is related to a [PR made in testrepo-Alpha](https://github.com/reposense/testrepo-Alpha/pull/15) and should be commited at the same time.

2 tests found in `AnnotatorAnalyzerTest.java`, namely `analyzeAnnotation_authorNamePresentInConfig_overrideAuthorship` and `analyzeAnnotation_authorNameNotInConfigAndNoAuthorConfigFile_acceptTaggedAuthor` will fail due to the current mismatch of content in `annotationTest.java` found in [testrepo-Alpha](https://github.com/reposense/testrepo-Alpha). The mentioned PR for testrepo-Alpha should fix the failing test.

This solution reflects the solution as described in the issue (#1874).

### CODE REVIEW

**Review by chan-j-d — APPROVED** [review]
The Java code changes look good. Awaiting the merge of the PR in the testrepo to verify that CI passes

**Review by yhtMinceraft1010X — COMMENTED** [review]
Looks good on this end

**Review by yhtMinceraft1010X — APPROVED** [review]
LGTM

**Review by HCY123902 — COMMENTED** [review]
@sikai00 The changes have been merged in https://github.com/reposense/testrepo-Alpha/pull/15. You can proceed to check whether this breaks anything aside from the JSON here

**Comment by sikai00** [comment]
> @sikai00 The changes have been merged in [reposense/testrepo-Alpha#15](https://github.com/reposense/testrepo-Alpha/pull/15). You can proceed to check whether this breaks anything aside from the JSON here

Currently it is failing for a few reasons (systemtest):
1) The LAST_COMMIT_DATE used to clone the testrepo-Alpha is at 01/04/2022 and is used as the until date parameter. In order to get the most updated JSON from testrepo-Alpha, we need to update the date. Correspondingly, `summary.json` will have to be updated to reflect the changed date parameter.
2) The changes made in `annotationTest.java` uses my git username instead of fakeAuthor. So we need to overwrite the changes using fakeAuthor.
3) Because of 2), the `authorship.json` reports are mismatching.

I think the best solution to this is to:
1) Overwrite the `annotationTest.java` with the correct git username and email (fakeAuthor and ma.tanghao@dhs.sg), update the testrepo-Alpha with it
2) After that, generate a fresh report (the JSON files) from testrepo-Alpha. These JSON files will be checked for sanity, then used to replace the pre-existing JSON files mentioned in this current PR.

The new PR for that can be found here: [testrepo-Alpha #16](https://github.com/reposense/testrepo-Alpha/pull/16)

(test):
AnnotatorAnalyzerTest failing tests:
- AnnotatorAnalyzerTest inherits from GitTestTemplate. GitTestTemplate clones the repo for AnnotatorAnalyzerTest as such, without any untilDates. Despite the `before()` in AnnotatorAnalyzerTest setting the repo config's untilDate to August 2021, I believe the assert uses the latest version of `annotationTest.java`, which attributes the last two lines to me rather than fakeAuthor. As a direct result of that, the tests in AnnotatorAnalyzerTest that relies on `annotationTest.java` currently fails. This can be fixed with the aforementioned PR to testrepo-Alpha.

GitDiffTest failing test:
- LATEST_COMMIT_HASH in `GitTestTemplate.java` is different from the current commit in testrepo-Alpha as a result of the update to testrepo-Alpha. As such the test is failing.

GitShortlogTest failing test:
- Due to the update in testrepo-Alpha, two more authors are added: sikai00 and HCY123902. We will have to add the two authors into the expected author list to make the test pass again.

**Comment by HCY123902** [comment]
> > @sikai00 The changes have been merged in [reposense/testrepo-Alpha#15](https://github.com/reposense/testrepo-Alpha/pull/15). You can proceed to check whether this breaks anything aside from the JSON here
> 
> Currently it is failing for a few reasons (systemtest):
> 
> 1. The LAST_COMMIT_DATE used to clone the testrepo-Alpha is at 01/04/2022 and is used as the until date parameter. In order to get the most updated JSON from testrepo-Alpha, we need to update the date. Correspondingly, `summary.json` will have to be updated to reflect the changed date parameter.
> 2. The changes made in `annotationTest.java` uses my git username instead of fakeAuthor. So we need to overwrite the changes using fakeAuthor.
> 3. Because of 2), the `authorship.json` reports are mismatching.
> 
> I think the best solution to this is to:
> 
> 1. Overwrite the `annotationTest.java` with the correct git username and email (fakeAuthor and [ma.tanghao@dhs.sg](mailto:ma.tanghao@dhs.sg)), update the testrepo-Alpha with it
> 2. After that, generate a fresh report (the JSON files) from testrepo-Alpha. These JSON files will be checked for sanity, then used to replace the pre-existing JSON files mentioned in this current PR.
> 
> The new PR for that can be found here: [testrepo-Alpha #16](https://github.com/reposense/testrepo-Alpha/pull/16)
> 
> (test): AnnotatorAnalyzerTest failing tests:
> 
> * AnnotatorAnalyzerTest inherits from GitTestTemplate. GitTestTemplate clones the repo for AnnotatorAnalyzerTest as such, without any untilDates. Despite the `before()` in AnnotatorAnalyzerTest setting the repo config's untilDate to August 2021, I believe the assert uses the latest version of `annotationTest.java`, which attributes the last two lines to me rather than fakeAuthor (due to the update in testrepo-Alpha where sikai00 overwrites fakeAuthor). As a direct result of that, the tests in AnnotatorAnalyzerTest that relies on `annotationTest.java` currently fails. This can be fixed with the aforementioned PR to testrepo-Alpha.
> 
> GitDiffTest failing test:
> 
> * LATEST_COMMIT_HASH in `GitTestTemplate.java` is different from the current commit in testrepo-Alpha as a result of the update to testrepo-Alpha. As such the test is failing.
> 
> GitShortlogTest failing test:
> 
> * Due to the update in testrepo-Alpha, two more authors are added: sikai00 and HCY123902. We will have to add the two authors into the expected author list to make the test pass again.

I have merged https://github.com/reposense/testrepo-Alpha/pull/16. You can go ahead with the remaining changes

**Comment by chan-j-d** [comment]
I believe it is possible to fork `testrepo_Alpha` and then use that remote repo to test the edited test cases by replacing the URL for testrepo_Alpha to the one in your fork. Once the changes are finalized than PR from your fork to testrepo_Alpha

**Comment by chan-j-d** [comment]
@sikai00 is this PR ready for review?

**Comment by sikai00** [comment]
> @sikai00 is this PR ready for review?

Hi yes, sorry thought I had requested for one alr 😅

**Review by chan-j-d — APPROVED** [review]
LGTM! Hope we don't have to change these tests too often. Should probably try to speed this PR up as it's a relatively minor change which also causes CI to fail for other PRs

**Review by HCY123902 — APPROVED** [review]

**Review by dcshzj — APPROVED** [review]
LGTM. Will skip the 2-day minimum waiting period for this PR as it is a blocker for all other existing PRs.

**Pull request merged**
