### PR TITLE
[#1936] Migrate safari_date.js to typescript

### PR DESCRIPTION
**Pull request by jq1836**
Part of #1936 

### Proposed commit message
```
Currently, there is still some JavaScript code which remains unmigrated.
This allows for type unsafe code to be written, potentially resulting in
unintended behavior.

Let's migrate safari_date.js to TypeScript code to facilitate future
changes to the code.
```

### Relevant changes made
* Updated code to use of `key` attribute instead of `keycode` attribute of `KeyboardEvent` as `keycode` is deprecated, slated for removal in the near future. Leaving code as such would possibly lead to situations where code suddenly no longer works.

### CODE REVIEW

**Comment by damithc** [comment]
@reposense/active-reviewers-1 this PR seems to be ready for review

**Review by ckcherry23 — APPROVED** [review]
LGTM

**Comment by jq1836** [comment]
Kindly requesting for your attention in reviewing the bunch of PRs related to the migration to TypeScript. Once done, issue #1936 can be closed.

**Review by chan-j-d — APPROVED** [review]
LGTM!

**Comment by chan-j-d** [comment]
Hi @jq1836, could you check if removing the `src/**/*.js` in the lint command in `frontend/package.json` fixes the build? This seems to be the last unmigrated js file in the frontend code. Might need you to add it as a separate PR later

**Comment by jq1836** [comment]
Hi @chan-j-d, seems like updating the lint command fixes the build. I have put up a new PR #2063 which fixes the lint command. I am unsure if the problem warrants an entire issue dedicated to it, so I have not put one up. Do let me know if an issue should be put up.

**Comment by chan-j-d** [comment]
@jq1836 Thanks so much! The change looks good

**Pull request merged**
