### PR TITLE
[#1532] Change mergegroups in URL to be group index for concision

### LINKED ISSUE #1532: URL for a dashboard is quite long when the `merge groups` is used
It looks like the URL for a dashboard is quite long when the `merge groups` is used e.g.,

```
https://nus-cs2103-ay2021s2.github.io/tp-dashboard/?search=&sort=groupTitle&sortWithin=title&timeframe=commit&mergegroup=AY2021S2-CS2103-T14-1%2Ftp%5Bmaster%5D~AY2021S2-CS2103-T14-2%2Ftp%5Bmaster%5D~AY2021S2-CS2103-T14-3%2Ftp%5Bmaster%5D~AY2021S2-CS2103-T14-4%2Ftp%5Bmaster%5D~AY2021S2-CS2103-T16-1%2Ftp%5Bmaster%5D~AY2021S2-CS2103-T16-2%2Ftp%5Bmaster%5D~AY2021S2-CS2103-T16-3%2Ftp%5Bmaster%5D~AY2021S2-CS2103-W16-1%2Ftp%5Bmaster%5D~AY2021S2-CS2103-W16-2%2Ftp%5Bmaster%5D~AY2021S2-CS2103-W16-3%2Ftp%5Bmaster%5D~AY2021S2-CS2103-W16-4%2Ftp%5Bmaster%5D~AY2021S2-CS2103-W17-1%2Ftp%5Bmaster%5D~AY2021S2-CS2103-W17-2%2Ftp%5Bmaster%5D~AY2021S2-CS2103-W17-3%2Ftp%5Bmaster%5D~AY2021S2-CS2103-W17-4%2Ftp%5Bmaster%5D~AY2021S2-CS2103T-T10-1%2Ftp%5Bmaster%5D~AY2021S2-CS2103T-T10-2%2Ftp%5Bmaster%5D~AY2021S2-CS2103T-T11-1%2Ftp%5Bmaster%5D~AY2021S2-CS2103T-T11-2%2Ftp%5Bmaster%5D~AY2021S2-CS2103T-T11-3%2Ftp%5Bmaster%5D~AY2021S2-CS2103T-T11-4%2Ftp%5Bmaster%5D~AY2021S2-CS2103T-T12-1%2Ftp%5Bmaster%5D~AY2021S2-CS2103T-T12-2%2Ftp%5Bmaster%5D~AY2021S2-CS2103T-T12-3%2Ftp%5Bmaster%5D~AY2021S2-CS2103T-T12-4%2Ftp%5Bmaster%5D~AY2021S2-CS2103T-T13-1%2Ftp%5Bmaster%5D~AY2021S2-CS2103T-T13-2%2Ftp%5Bmaster%5D~AY2021S2-CS2103T-T13-3%2Ftp%5Bmaster%5D~AY2021S2-CS2103T-T13-4%2Ftp%5Bmaster%5D~AY2021S2-CS2103T-W10-1%2Ftp%5Bmaster%5D~AY2021S2-CS2103T-W10-2%2Ftp%5Bmaster%5D~AY2021S2-CS2103T-W10-3%2Ftp%5Bmaster%5D~AY2021S2-CS2103T-W10-4%2Ftp%5Bmaster%5D~AY2021S2-CS2103T-W12-1%2Ftp%5Bmaster%5D~AY2021S2-CS2103T-W12-2%2Ftp%5Bmaster%5D~AY2021S2-CS2103T-W12-3%2Ftp%5Bmaster%5D~AY2021S2-CS2103T-W13-1%2Ftp%5Bmaster%5D~AY2021S2-CS2103T-W13-2%2Ftp%5Bmaster%5D~AY2021S2-CS2103T-W13-3%2Ftp%5Bmaster%5D~AY2021S2-CS2103T-W13-4%2Ftp%5Bmaster%5D~AY2021S2-CS2103T-W14-1%2Ftp%5Bmaster%5D~AY2021S2-CS2103T-W14-2%2Ftp%5Bmaster%5D~AY2021S2-CS2103T-W14-3%2Ftp%5Bmaster%5D~AY2021S2-CS2103T-W14-4%2Ftp%5Bmaster%5D~AY2021S2-CS2103T-W15-1%2Ftp%5Bmaster%5D~AY2021S2-CS2103T-W15-2%2Ftp%5Bmaster%5D~AY2021S2-CS2103T-W15-3%2Ftp%5Bmaster%5D~AY2021S2-CS2103T-W15-4%2Ftp%5Bmaster%5D&groupSelect=groupByRepos&breakdown=true&checkedFileTypes=docs~functional-code~test-code~other&since=2021-02-19&tabOpen=true&tabType=authorship&tabAuthor=hengyongming&tabRepo=AY2021S2-CS2103T-W14-4%2Ftp%5Bmaster%5D&authorshipIsMergeGroup=true&isTabOnMergedGroup=true&authorshipFilesGlob=*.fxml
```
image

URLs have length limits. We might break such a limit if we are not careful.

### PR DESCRIPTION
**Pull request by jonasongg**
Fixes #1532 

### Proposed commit message

```
Change mergegroup hash in URL to refer to group index instead of name

Currently, the mergegroup hash param in the URL lists down all groups
that are merged. This can result in an extremely long URL when many
groups are merged which can cause the URL to exceed the length limit.

Let's change the param to refer to the repo index instead to prevent
this issue.
```

### Other information

This required a few changes to the order in which methods are called in `created()` of `c-summary.vue`. The original behaviour was `renderFilterHash` sets data from the URL, then `getFiltered` sets the URL from the fields as well as populates `this.filtered`. Changing the URL to refer to group index instead necessitates that setting and getting the merged groups from the URL happen after `this.filtered` is populated.

It might not be worth changing the logic of `c-summary.vue` just to shorten the URL; let me know what you think! If it's worth it to make this change, I will need to change `codeView_renderFilterHash.cy.js` as well. (So please ignore the failing CI for now!)

An additional consideration is to +1 the index that is displayed in the URL to match the index shown on the page since arrays are zero-indexed but the index shown on the page is one-indexed.

### CODE REVIEW

**Review by asdfghjkxd — COMMENTED** [review]
Looks good! However, it is failing CI due to some failing frontend test cases, specifically:

```
Running:  chartView/chartView_zoomFeature.cy.js                                          (9 of 25)


  zoom features in code view
    ✓ click on view commits button (1035ms)
    ✓ zoom into ramp (482ms)
    ✓ zoom into ramp when merge group (595ms)

  date changes in chart view should reflect in zoom
    ✓ setting 'since' date range changes the zoom view (1134ms)
    ✓ setting 'since' date again results in a different zoom view (976ms)
    ✓ setting the 'until' date changes the zoom view (1187ms)
    ✓ setting the 'until' date again results in a different zoom view (1435ms)
    ✓ setting the 'until' and 'since' date changes the zoom view (1316ms)
    ✓ setting the 'until' and 'since' date again results in a different zoom view (1329ms)

  range changes in chartview should reflect in zoom
    1) selecting the initial righthand and lefthand boundary
    2) changing the righthand boundary
    ✓ changing the lefthand boundary (1387ms)
    ✓ changing the righthand and lefthand boundary (806ms)


  11 passing (1m)
  2 failing

  1) range changes in chartview should reflect in zoom
       selecting the initial righthand and lefthand boundary:

      Timed out retrying after 30000ms
      + expected - actual

      -'[2019-12-31] [#785] ChartView: fix authors with unaccounted lines (#789): +49 -42 lines '
      +'[2019-12-20] [#46] Show total time after batch processing (#758): +43 -0 lines '
      
      at Context.eval (webpack:///./tests/chartView/chartView_zoomFeature.cy.js:270:7)

  2) range changes in chartview should reflect in zoom
       changing the righthand boundary:

      Timed out retrying after 30000ms
      + expected - actual

      -'[2019-12-31] [#785] ChartView: fix authors with unaccounted lines (#789): +49 -42 lines '
      +'[2019-12-20] [#46] Show total time after batch processing (#758): +43 -0 lines '
      
      at Context.eval (webpack:///./tests/chartView/chartView_zoomFeature.cy.js:296:7)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        13                                                                               │
  │ Passing:      11                                                                               │
  │ Failing:      2                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     1 minute, 14 seconds                                                             │
  │ Spec Ran:     chartView/chartView_zoomFeature.cy.js                                            │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
```

```
Running:  codeView/codeView_renderFilterHash.cy.js                                      (17 of 25)


  render filter hash
    ✓ search: url params should persist after change and reload (1340ms)
    ✓ group by: url params should persist after change and reload (888ms)
    ✓ sort groups by: url params should persist after change and reload (1611ms)
    ✓ sort within groups by: url params should persist after change and reload (1613ms)
    ✓ granularity: url params should persist after change and reload (670ms)
    ✓ since: url params should persist after change and reload (647ms)
    ✓ until: url params should persist after change and reload (708ms)
    ✓ breakdown by file type: url params should persist after change and reload (348ms)
    1) merge all groups: url params should persist after change and reload
    ✓ checked file types: url params should persist after change and reload (1265ms)


  9 passing (40s)
  1 failing

  1) render filter hash
       merge all groups: url params should persist after change and reload:
     AssertionError: Timed out retrying after 30000ms: expected 'http://localhost:9000/?search=&sort=groupTitle%20dsc&sortWithin=title&since=2018-05-03&timeframe=commit&groupSelect=groupByRepos&breakdown=false&mergegroup=0' to include 'mergegroup=reposense%2FRepoSense%5Bcypress%5D'
      at Context.eval (webpack:///./tests/codeView/codeView_renderFilterHash.cy.js:297:7)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        10                                                                               │
  │ Passing:      9                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     39 seconds                                                                       │
  │ Spec Ran:     codeView/codeView_renderFilterHash.cy.js                                         │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by jonasongg** [comment]
@asdfghjkxd Thanks for the review! I originally wanted to see if it was worth performing this change before I changed the cypress tests, but with your review, I'll go ahead and change it :)

**Comment by ckcherry23** [comment]
Hi @jonasongg, noticed a bug in the current implementation:

### Steps to reproduce
1. Merge the first and second repositories using the Merge Group icon. Let's say their names are A and B respectively.
2. Change the sort by option to something else, for example, '↑ Contribution'.

### Expected
1. A and B are still merged when the sort order is changed. 
2. The rest of the repos are not merged.

### Actual
1. Instead of A and B being the merged ones, the first and second repositories in the new order are the merged groups. 
---
Can you please take a look?

**Comment by jonasongg** [comment]
@ckcherry23 Should be fixed now!

**Comment by jonasongg** [comment]
@ckcherry23 Also added a test for this bug!

**Pull request closed without merging**
