### PR TITLE
[#1486] Frontend: rename zIsMerge to zIsMerged

### LINKED ISSUE #1486: Restoring not working properly for zoom panel
**Tell us about your environment**

* **RepoSense Version:**master
* **OS and Version:**Windows10
* **Web Browser and Version (if applicable):**Edge

**Please include the steps to reproduce the bug.**

1. Open the zoom panel of an individual author
1. Merge the group and open the group zoom panel
1. Reload the page 

**What was expected to happen?**
The zoom panel of the merged group should be shown on the screen

**What actually happened? Please include a screenshot of the output.**
The zoom panel of an individual author is shown

image

**If possible, include the URL to your RepoSense report or log files (if any).**

### PR DESCRIPTION
**Pull request by HCY123902**
Resolves #1486 

This is a regression caused by #1457 

Commit message:
```
Change all instances of zIsMerge to zIsMerged

The zoom panel of a merged group currently cannot seem 
to be restored after reloading the page. This seems to be 
caused by incomplete renaming of the zIsMerge argument
in #1457.

Renaming other instances of zIsMerge can resolve this
issue and make the reloading behavior more consistent
with the user expectation.

Let's change all instances of zIsMerge to zIsMerged.
```

### CODE REVIEW

**Comment by gerhean** [comment]
Bug is actually a regression due to #1457 changing only some instances of `isMerge` to `isMerged`, hence I do not approve of this changes.

The only real change which needs to be made is to rename all `isMerge` to `isMerged`, and:

`v_summary_charts.js` line 178:
from
`zAuthor: user.name,`
to
`zAuthor: isMerged ? '' : user.name`
which I believe is the reasonable change to make as there should not be an author when the group is merged.

**Comment by HCY123902** [comment]
> Bug is actually a regression due to #1457 changing only some instances of `isMerge` to `isMerged`, hence I do not approve of this changes.
> 
> The only real change which needs to be made is to rename all `isMerge` to `isMerged`, and:
> 
> `v_summary_charts.js` line 178:
> from
> `zAuthor: user.name,`
> to
> `zAuthor: isMerged ? '' : user.name`
> which I believe is the reasonable change to make as there should not be an author when the group is merged.
> 
> Alternatively it should be fixed by #1490 once all `isMerge` is renamed to `isMerged`.

Thanks for the suggestion. However, I believe #1490 is handling a separate issue and it is necessary to handle this particular issue here.

**Comment by fzdy1914** [comment]
> Bug is actually a regression due to #1457 changing only some instances of `isMerge` to `isMerged`, hence I do not approve of this changes.


@gerhean 
If you got doubles on some implementation, you should mention that early instead of just not approve it.

**Review by 0blivious — APPROVED** [review]
Had a brief look through. Please double confirm that you have changed all the `zisMerge` and `isMerge` for the project. In IDE there is a quick search that allows you to locate the string in all files.

**Comment by gerhean** [comment]
I think the commit message of this PR should be changed to just renaming isMerge to isMerged since that is what the PR is about now.

@fzdy1914 Sorry I'll try to check out frontend issues faster given that most of the current ones are just regressions caused by my PRs

**Comment by HCY123902** [comment]
> Had a brief look through. Please double confirm that you have changed all the `zisMerge` and `isMerge` for the project. In IDE there is a quick search that allows you to locate the string in all files.

Thanks for the suggestion. I have checked again and all the instances should have been renamed now.

**Comment by fzdy1914** [comment]
There are conflicts here.

**Review by gerhean — APPROVED** [review]
LGTM

**Pull request merged**
