### PR TITLE
[#185] Use realistic person names for test repos

### PR DESCRIPTION
**Pull request by Tejas2805**

### CODE REVIEW

**Comment by jylee-git** [comment]
https://github.blog/2019-02-14-introducing-draft-pull-requests/

When making a PR next time, you may want to draft pull request if it isn't ready for review at the time of making the PR.

**Comment by fzdy1914** [comment]
Regarding this issue,  we have a discussion before. We believe it is not good to use the student's real name in this case because they are not a part of our developer team.

**Comment by jylee-git** [comment]
> Regarding this issue, we have a discussion before. We believe it is not good to use the student's real name in this case because they are not a part of our developer team.

We should use realistic, but dummy names instead of the real names of those students.

**Comment by Tejas2805** [comment]
> > Regarding this issue, we have a discussion before. We believe it is not good to use the student's real name in this case because they are not a part of our developer team.
> 
> We should use realistic, but dummy names instead of the real names of those students.

Alright I will make the changes accordingly. 

(I thought since using proper repositories, names need to e proper too)

**Comment by Tejas2805** [comment]
Can anyone guide me as to how to fix this error in Travis? I am not being able to understand how to remove /r/n and just use /n?

**Pull request closed without merging**
