### PR TITLE
[#1129] Reposense class: Throw exception earlier

### LINKED ISSUE #1129: RepoSense crashes too late if there are 0 valid locations in `--repo` argument
To replicate, run the command:
`./gradlew run -Dargs="--repo abc.git"`

Output:
```
01:51:34 - [WARNING] abc.git is an invalid location.
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:372)
        at java.base/java.util.ArrayList.get(ArrayList.java:458)
        at reposense.report.ReportGenerator.cloneAndAnalyzeRepos(ReportGenerator.java:153)
        at reposense.report.ReportGenerator.generateReposReport(ReportGenerator.java:98)
        at reposense.RepoSense.main(RepoSense.java:69)
```

As seen in the stack trace, RepoSense tries to proceed with report generation even though there are no valid repo locations.

Expected: RepoSense should not proceed with report generation if there are no valid locations.

To solve: Check that there is at least one valid location

### PR DESCRIPTION
**Pull request by lingzhiyu**
Fixes #1129 

Reposense class: throw exception earlier in `getRepoConfigurations`
Currently, `Reposense` continues with report generation even though there are no valid repo locations in the `--repo` arguments. 

This results in a late crash during the execution of the `cloneAndAnalyzeRepos` method quite some time after Reposense runs. 

Let’s add a state-test at the end of the `getRepoConfigurations` method, to check if any repo location(s) are valid. If there are none, then throw an `IllegalStateException`.

`getRepoConfigurations` is the method that constructs a list of `RepoLocation` objects from the inputs. It is the earliest way to check if there are valid locations, making it easier to identify the cause of the command failure. `IllegalStateException` is thrown as it is not possible for the application to recover and generate reports, because the precondition that is at least 1 valid argument is not met.

### CODE REVIEW

**Comment by jamessspanggg** [comment]
Hi @lingzhiyu, thanks for contributing to RepoSense! It seems like there's an existing PR #1157 that targets to solve this issue. Perhaps you can check if there's an existing targeted PR before starting to work on the issue?

**Comment by lingzhiyu** [comment]
Hi @jamessspanggg, I unfortunately attempted working on the issue a few days earlier and resumed today. I will take note of the etiquette. Should I submit another PR on another issue then?

**Comment by jamessspanggg** [comment]
> Hi @jamessspanggg, I unfortunately attempted working on the issue a few days earlier and resumed today. I will take note of the etiquette. Should I submit another PR on another issue then?

No worries! That would be great!

**Comment by jamessspanggg** [comment]
Closing this PR as it conflicts with #1157

**Comment by jamessspanggg** [comment]
@lingzhiyu do ask for the devs if you want to work on the issue, we will assign it to you so that situations like these won't happen.

**Pull request closed without merging**
