### PR TITLE
[#1538] Frontend: make glob input wider

### LINKED ISSUE #1538: Code view: make the glob filter input box wider
image

We can make this input text box wider as there is plenty of spare space here.

### PR DESCRIPTION
**Pull request by Punpun1643**
Fixes #1538 

## Proposed commit message

```
There is plenty of space left beside the glob filter input box. We can
increase the box size to make use of the remaining spaces.

The glob filter input box and the filter button also does not align
properly after the increase in the box width when the viewport is
smaller.

Let's increase the width of the glob filter input box and fix the
alignment of the filter button. 
```

## Other information

Before:
64F88712-CDE0-4FCE-A765-38962215CCDA_4_5005_c

6E53BF4F-C295-47E4-93DF-5167AB212588_4_5005_c

After:

5E2B318E-8DA9-4872-AE0A-123FAE238AA1_4_5005_c

54A2337A-3A94-4A9C-9AA6-7012AD9E5585_4_5005_c

### CODE REVIEW

**Comment by HCY123902** [comment]
Thank you for the contribution. Can you also align the height of the input box and the button?

The height is aligned originally.

image

After your modification, the button height slightly exceeds that of its neighbor.

image

**Comment by Punpun1643** [comment]
Hi @HCY123902, have fixed it as requested.

DE5C92A8-7561-49CB-BD62-E5E602F0B467_4_5005_c
E6337414-EB60-44ED-85B9-C56E5ED198AE_4_5005_c

**Review by HCY123902 — APPROVED** [review]

**Comment by Zhou-Jiahao-1998** [comment]
@Punpun1643 Hi there! May I know if it is possible to make the input box on your second screenshot a little longer such that `Filter by glob` can be fully visible?

**Review by Zhou-Jiahao-1998 — APPROVED** [review]
LGTM!

**Comment by Zhou-Jiahao-1998** [comment]
@Punpun1643 I think you need to fetch from upstream `reposense:master`. The CI is failing.

**Comment by Punpun1643** [comment]
@Zhou-Jiahao-1998, Sorry! I have fetched the upstream.

**Comment by Punpun1643** [comment]
Hi @Zhou-Jiahao-1998, it seems like the CI was still failing even after I had fetched the upstream. I have tried re-fetching it again. I think codecov was failing due to a fall in the coverage from the backend side. Could you please advise on how I should resolve this issue? Thank you!

**Comment by Zhou-Jiahao-1998** [comment]
@Punpun1643 from what I see here, this branch and master are still behind `reposense:master`. Did you pull after fetching? After that you need to merge your updated master into your branch.
Screenshot 2022-07-21 at 20 55 15
e

**Comment by Punpun1643** [comment]
Hi @Zhou-Jiahao-1998, thank you for the help. I think I was confused about how fetching is supposed to work. I have tried attempting it again. 

My current `master` is up-to-date with `reposense:master`
F2231842-C579-4F29-A6EA-E90F6DFACABA

And I have merged my updated `master` to this branch
2472D65F-0EC2-4E13-8CC9-EBB336085FB9

However, instead of doing everything on `master` (i.e. fetch and pull on master, then merge the updated master to this branch), I went to click the `Fetch upstream` button on this branch, causing the `reposense:master` to be merged to this branch. I'm not very sure if that would cause any problem.

68DFF411-FBCE-4B60-8AA3-8D7311723468_4_5005_c

**Comment by Zhou-Jiahao-1998** [comment]
@Punpun1643 Your way of doing works as well. The problem was that you forgot to pull after fetching. That resulted in your branch being behind and ahead at the same time. The issue is now solved. 

The reason why I suggest you to fetch on master and do a merge request is so that if you want to start a new branch concurrently you will avoid this issue. It might be easier to resolve any conflicts(?) just my personal view.

Please be patient as we are going through the approval process. In the meantime, you can start looking into other issues.

**Review by dcshzj — APPROVED** [review]
LGTM! The glob input box itself is not working, which I have filed #1810. That bug can be fixed in a separate pull request.

**Pull request merged**
