### PR TITLE
[#944] Resolve Merge Conflict

### PR DESCRIPTION
**Pull request by SkyBlaise99**
Part of #944

### Proposed commit message

```
Currently the branch is ready but out of sync with the master branch,
which had some major revamp in both the frontend and backend.

Let's merge the master branch into this branch to keep it up to date.
```

### Other information

This PR has no new feature, purely just for updating and resolving merge conflicts.

### CODE REVIEW

**Comment by gok99** [comment]
It is a little hard to tell what conflicts are resolved in this PR as it is. Would it be possible to mark out where you've had to resolve conflicts, perhaps with the original changes before the conflict was resolved?

**Comment by SkyBlaise99** [comment]
Here's a short summary of the merge conflicts.

| Conflict | Commit | Remark |
| --- | --- | --- |
| frontend/src/utils/segment.ts | 83510f19594cbefba374ba97dd9bacc97bd8593f | Removed |
| frontend/src/views/c-authorship.vue | 83510f19594cbefba374ba97dd9bacc97bd8593f | Followed updates from master. Lines 864 - 1042 are relocated to lines 75 - 151 in [`c-segment.vue`](https://github.com/reposense/RepoSense/pull/2139/commits/1d1a76de41d34b14f049d140f599be5c4568b85a#diff-066e57d1d3c347d1f1078b214972da86b34342732ea6cbdc53f727549d8b7518). |
| src/main/java/reposense/model/CliArguments.java | ef320c0d5155e4be41b3a70b01e3025601c0ef78 | Added lines 38, 39, 479 and 489. The rest followed updates from master |
| src/main/java/reposense/parser/ArgsParser.java | 83510f19594cbefba374ba97dd9bacc97bd8593f | Added lines 314, 315, 335 and 336. The rest followed updates from master |
| src/main/java/reposense/util/StringsUtil.java | 83510f19594cbefba374ba97dd9bacc97bd8593f | Followed updates from master |

I think it is easier to just merge this and look at the diff of 2 branches instead. The merge conflicts are simply relocating my codes to the new places as the old file/structures are changed. (frontend is splitting the code into smaller files and backend has updated the builder pattern).

**Review by gok99 — APPROVED** [review]
That's very helpful, thanks! Backend changes look good

**Review by ckcherry23 — APPROVED** [review]
Thanks a lot @SkyBlaise99 for creating #2140 to view the diff. Frontend changes look good to me. 

I may have a few simple code quality suggestions we could tackle in another PR:
* Add a comment to line 22 in `c-segment.vue` to show that the author color is applied only when the author color exists, else it takes the default mui color value (This was not your change, but since there is a lot of highlight color logic now, this could help).
* Define a type for `lastState` in line 413 of `c-authorship.vue` that includes both the last known author's name and the last line's full credit status for easier comparison, if possible.

**Comment by SkyBlaise99** [comment]
Thanks for the feedbacks. Can this be merged so I can put a PR to merge the feature branch into master like #2140? Thanks.

**Pull request merged**
