### PR TITLE
[#1397, #1460] Charts panel: header info misplaced

### LINKED ISSUE #1397: Long contribution bar causes UI issue
**Tell us about your environment**

* **RepoSense Version:** master
* **OS and Version:** Mac OS 
* **Web Browser and Version (if applicable):** Chrome

**Please include the steps to reproduce the bug.**

1. Visit http://tnb-contribution-04-01-2020.surge.sh/?search=&sort=groupTitle&sortWithin=totalCommits%20dsc&since=2020-06-04&timeframe=commit&mergegroup=thenewboston-developers%2FAccount-Manager%5Bmaster%5D&groupSelect=groupByRepos&breakdown=false
1. Observe that the second group appends to the first group, instead of being at the next line of the first group

**What was expected to happen?**
Next group should be at the next line of the first group

**What actually happened? Please include a screenshot of the output.**
Second group appends to the first group
Screen Shot 2021-01-04 at 11 11 19 AM

**More context**
Currently, the length of the contribution bar is directly proportional to the LoC contribution. For repositories that have users with very big difference in contribution, the users with large contribution will have very long contribution bar, as shown below:
Screen Shot 2021-01-04 at 11 13 01 AM

Since we already have the LoC displayed for each user/group, I think it may not be necessary for the contribution bar to be directly proportional to the LoC. Perhaps we should re-think the logic to calculate the length contribution bars? Or limit the length of contribution bar to a certain amount?

### LINKED ISSUE #1460: Charts panel: header info misplaced
image

https://nus-cs2103-ay2021s2.github.io/tp-dashboard/?search=&sort=totalCommits%20dsc&sortWithin=title&since=2021-02-19&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=true&checkedFileTypes=docs~functional-code~test-code~other

### PR DESCRIPTION
**Pull request by gerhean**
Fixes #1460, fixes #1397
```
Currently long chart__contribution bars can overflow and
cause some visual bugs.

Let's remove overflow: visible; and tweak the css slightly
to make it more pleasant to look at.
```

### CODE REVIEW

**Comment by Tejas2805** [comment]
Can show a ss of how the deployment looks for the repo that caused the bug to appear?

**Review by Tejas2805 — COMMENTED** [review]
Any reason for reducing the margins? Too much white space or something?

**Comment by gerhean** [comment]
The margin was reduced since the initial margin was very large in order to compensate for the overflow of the contribution lines caused by `overflow: visible`.
The actual margin to use is a matter of aesthetics though, so if you believe the current margin looks too narrow I can increase it.

**Comment by Tejas2805** [comment]
> @Tejas2805
> The margin was reduced since the initial margin was very large in order to compensate for the overflow of the contribution lines caused by `overflow: visible`.
> The actual margin to use is a matter of aesthetics though, so if you believe the current margin looks too narrow I can increase it.

I tried out different margins. The current implementation looks neat to me. More will be just extra. So looks good. 

@damithc your input on UI? The margins between each summary chart and between each group/repo have been reduced in comparison to what it was initially. Like @gerhean pointed just a matter of aesthetics now.

**Comment by gerhean** [comment]
> Can show a ss of how the deployment looks for the repo that caused the bug to appear?
The state of the repo that caused the bug to appear, hence the bug is gone.  I'll try to regenerate that particular repo at that time period.

**Comment by damithc** [comment]
> @damithc your input on UI? The margins between each summary chart and between each group/repo have been reduced in comparison to what it was initially. Like @gerhean pointed just a matter of aesthetics now.

Where can I see the new UI? Previously I was able to navigate to the PR preview site from the PR (when we were using Travis) -- how do I do that now?

**Comment by gerhean** [comment]
@damithc 
You can see the deployments here 
image

**Comment by damithc** [comment]
> You can see the deployments here, below the comments and just above the review required
> image

Ah. Nice!

No objections to the UI from my side. Actually, I couldn't detect any big difference.

**Review by HCY123902 — APPROVED** [review]
LGTM

**Review by 0blivious — APPROVED** [review]

**Review by Tejas2805 — APPROVED** [review]
LGTM!

**Comment by fzdy1914** [comment]
Any possibile way to re-produce the bug and to show that the issue is truly fixed?

**Comment by Tejas2805** [comment]
> Any possibile way to re-produce the bug and to show that the issue is truly fixed?

@gerhean Maybe you can show it on the repo actually creating the bug based on the issue and post a screenshot or something here.

**Review by fzdy1914 — APPROVED** [review]
Verified using the link in #1397

**Comment by fzdy1914** [comment]
```
Long `chart__contribution` bars in chart view can overflow and
cause some visual bugs.

Let's remove `overflow: visible;` and tweak the CSS slightly to fix
the bug.
```

**Pull request merged**
