### PR TITLE
Add highlighting to ramps

### PR DESCRIPTION
**Pull request by ongspxm**
```
To be able to open up a "zoomed-in" view of the ramp, the user must
first be able to select part of the ramp to focus on.

Let's add a way for the user to highlight the range of the ramp to
focus on. This will later translate into the date range for the
"zoomed-in" view to display the relevant commits.

In this particular implementation, we use a global `drags` object as a
way of preventing user from highlighting on multiple ramp charts. E.g.
if a user mousedown on one ramp chart and mouseup on the other, the
second chart will be highlighted with the positions defined between the
two mouse events.
```

### CODE REVIEW

**Comment by ongspxm** [comment]
@yamidark, @yong24s, @eugenepeh  if i were to use the tab functions in #524, should i just implement the ramp selection here (the ui part) and do the actual display of the information in the tab as another pr?

**Comment by eugenepeh** [comment]
>@yamidark, @yong24s, @eugenepeh if i were to use the tab functions in #524, should i just implement the ramp selection here (the ui part) and do the actual display of the information in the tab as another pr?

no need. both should be part of this feature.

**Comment by ongspxm** [comment]
@yamidark can create a new branch for me to merge into instead? i think this gonna be pretty big

**Comment by yamidark** [comment]
>@yamidark can create a new branch for me to merge into instead? i think this gonna be pretty big

Done, `ramp-chart-zoom` branch created

**Pull request merged**
