### PR TITLE
Make Travis-CI test RepoSense on Mac OSX #143

### LINKED ISSUE #143: Explore multiple OS support on Travis
```
As an Java application, RepoSense is able to execute on all OSes that
supports jar executable. It is important to ensure that our application
does not break on the supported OSes.

In addition to the linux execution environment, Travis also supports CI
on macOS. Furthermore, this multi-environment configuration allows
parallel execution according to Travis-CI documentation [1].

Let's enable a second build environment, macOS, on travis, so we can
ensure RepoSense runs correctly on all supported OSes.

[1] Testing Your Project on Multiple Operating Systems:
https://docs.travis-ci.com/user/multi-os/
```

### PR DESCRIPTION
**Pull request by yong24s**
Fixes #143 
```
As an Java application, RepoSense is able to execute on all OSes that
supports jar executable. It is important to ensure that our application
does not break on the supported OSes.

In addition to the linux execution environment, Travis also supports CI
on macOS. Furthermore, this multi-environment configuration allows
parallel execution according to Travis-CI documentation [1].

Let's enable a second build environment, macOS, on travis, so we can
ensure RepoSense runs correctly on all supported OSes.

[1] Testing Your Project on Multiple Operating Systems:
https://docs.travis-ci.com/user/multi-os/

```

### CODE REVIEW

**Comment by yong24s** [comment]
@eugenepeh, for your review, please.

**Comment by eugenepeh** [comment]
Seems a bit abnormal, osx took 15 minutes in total whereas linux only took 6 minutes. Can you look into it? 

Thanks.

**Comment by yong24s** [comment]
@eugenepeh 

According to Travis blog [1], Travis runs Linux and OSX on different cloud providers, which may have performance capabilities.

Furthermore, an issue on Travis GitHub [2], claims that the slowness in OSX may be attributed to high amount of disk accesses. This could be a reason why RepoSense run so slowly as it has both IO-Bound and CPU-bound tasks.

[1] Travis cloud providers 
https://blog.travis-ci.com/2017-09-22-macos-update

[2] Test execution very slow and timing out on OSX
https://github.com/travis-ci/travis-ci/issues/7185

**Comment by eugenepeh** [comment]
As `an java application,` RepoSense is ~designed to run~`able to execute` on ~multiple~`all` OSes `that supports jar executable.`~,~ ~it is good that
we have CI on all supported OSes.~ `It is important to ensure that our application does not break on the supported OSes.`

`In addition to the linux execution environment, Travis also supports CI on macOS. Furthermore, this multi-environment configuration allows parallel execution a`~A~ccording to Travis-CI documentation [1].~, it can concurrently run
CI tests on both Linux and Mac OSX.~

Let's ~explore the multiple OS support on Travis~ `enable a second build environment, macOS, on travis`, so we can 
ensure RepoSense runs correctly on all supported OSes.

[1] Testing Your Project on Multiple Operating Systems:
https://docs.travis-ci.com/user/multi-os/

**Pull request merged**
