### PR TITLE
[#1967] Use GitHub environmental files instead of set-output

### LINKED ISSUE #1967: Use GitHub environmental files instead of using soon-to-be deprecated set-output
### What feature(s) would you like to see in RepoSense

Currently, our `surge.yml` uses `set-output` to extract and save the PR number for use as part of the surge.sh preview domain. However, GitHub will be deprecating `set-output` to "avoid untrusted logged data to use save-state and set-output workflow commands without the intention of the workflow author."

image

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

This feature will be fully disabled by 31st May 2023, which is 2 months from now. 

### If possible, describe the solution

As described in the article, we can use GitHub environmental files available within an action to save the PR number instead.

https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#sending-values-to-the-pre-and-post-actions

### PR DESCRIPTION
**Pull request by sikai00**
Fixes #1967

### Proposed commit message

```
surge.yml currently uses set-output to extract and save the PR number
for use as part of the surge.sh preview domain. However, GitHub will be
deprecating set-output for security reasons.

Let's update surge.yml to use the new GITHUB_OUTPUT environment files
instead.
```

### Other information

The change were as per [GitHub's article](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).

While our surge.sh preview is still currently down, the correctness of this PR can be checked against the link produced.

### CODE REVIEW

**Comment by sikai00** [comment]
### Example
I have a [completed workflow](https://github.com/sikai00/RepoSense/actions/runs/4719192310) on my forked repo, which shows the correctness of the PR. The warning no longer shows up.

Note that the workflow is ran using a different commit than the PR, so that the workflow is indeed using the updated line to run. Furthermore I disabled codecov in my repo, as it will fail and prevent the surge workflow from happening.

**Review by ckcherry23 — APPROVED** [review]
LGTM!

**Review by chan-j-d — APPROVED** [review]
LGTM!

**Review by yhtMinceraft1010X — APPROVED** [review]
LGTM

**Pull request merged**
