### PR TITLE
[#1329] FileInfoExtractor: Add  check for optional quotes in diff file regex

### LINKED ISSUE #1329: CS2103T iP: Fails to load one repo
This report is failing to load one repo https://nus-cs2103-ay2021s1.github.io/ip-dashboard

image

This is the error message in the CI log https://github.com/nus-cs2103-AY2021S1/ip-dashboard/runs/1169901121

>04:42:13 - Extracting relevant file info from https://github.com/Jillzyt/ip.git (master)...
04:42:13 - [ERROR] java.lang.IndexOutOfBoundsException: Index: 10, Size: 10
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at reposense.authorship.FileInfoExtractor.setLinesToTrack(FileInfoExtractor.java:165)
	at reposense.authorship.FileInfoExtractor.getEditedFileInfos(FileInfoExtractor.java:117)
	at reposense.authorship.FileInfoExtractor.extractFileInfos(FileInfoExtractor.java:70)
	at reposense.authorship.AuthorshipReporter.generateAuthorshipSummary(AuthorshipReporter.java:21)
	at reposense.report.ReportGenerator.analyzeRepo(ReportGenerator.java:248)
	at reposense.report.ReportGenerator.analyzeRepos(ReportGenerator.java:206)
	at reposense.report.ReportGenerator.cloneAndAnalyzeRepos(ReportGenerator.java:172)
	at reposense.report.ReportGenerator.generateReposReport(ReportGenerator.java:100)
	at reposense.RepoSense.main(RepoSense.java:69)

### PR DESCRIPTION
**Pull request by jamessspanggg**
Fixes #1329 

```
When file names contain spaces, the git diff statement will be wrapped 
with double quotes. (shown in screenshot below)

The diff file chunk separator within FileInfoExtractor do not handle 
the case where the diff statement is surrounded by quotes, which 
causes the regex to not separate each diff-ed files correctly, causing 
the outOfBounds error from issue 1329.

Let's add the optional check for quotes within the regex, this will 
handle the situations where the diff statement is surrounded by quotes.
```

diff statement surrounded by quotes, as file name contains spaces:

Screen Shot 2020-09-26 at 10 37 05 PM

### CODE REVIEW

**Comment by jamessspanggg** [comment]
Tried to re-run the analysis with the same configs as the CS2103 ip repo. Works fine. Link to the generated report [here](http://reposense-1329.surge.sh) (Note: the loading might be slow as hosting on surge)

**Comment by damithc** [comment]
> Tried to re-run the analysis with the same configs as the CS2103 ip repo. Works fine. Link to the generated report [here](http://reposense-1329.surge.sh) (Note: the loading might be slow as hosting on surge)

Great. I'll regenerated the report after this is merged. Thanks for the fix @jamessspanggg

**Review by fzdy1914 — APPROVED** [review]

**Review by Tejas2805 — APPROVED** [review]

**Comment by jamessspanggg** [comment]
@damithc can try to regenerate the report and see if the issue still occurs.

**Comment by damithc** [comment]
> @damithc can try to regenerate the report and see if the issue still occurs.

Done. No more error. Thanks for the fix 💯

**Pull request merged**
