### PR TITLE
[#2142] Fix Vulnerabilities

### LINKED ISSUE #2142: Fix Vulnerabilities in Code Base
### What feature(s) would you like to see in RepoSense

There are currently 12 vulnerabilities (11 moderate, 1 critical) as of commit `bbb2f6`. We should fix these to prevent vulnerabilities from causing unexpected issues.

### If possible, describe the solution
Update the relevant dependencies.

### PR DESCRIPTION
**Pull request by sopa301**
Fixes #2142

### Proposed commit message

```
Fix Vulnerabilities in Code Base

There are existing vulnerabilities in the code base.

Let's fix as many as possible.
```

### Other information

`@vue/cli-service` is being put on maintenance mode. It might be worthwhile to migrate to the suggested [`create-vue`](https://github.com/vuejs/create-vue) to keep dependencies updated.

`postcss` and `vue-loader` had to be installed manually because `@vue/cli-service` is not updated with the fixed dependencies yet. These can be removed when `@vue/cli-service` has a similar update.

### CODE REVIEW

**Review by asdfghjkxd — APPROVED** [review]
LGTM!

**Review by ckcherry23 — APPROVED** [review]
LGTM, thanks for this! @sopa301 
Would it be better to merge this after the Node 18 PR is merged?

**Comment by sopa301** [comment]
I think so, the change in Node version may cause unexpected errors, and this PR isn't as high priority as the Node one.

**Review by MarcusTXK — APPROVED** [review]
LGTM, nice job

**Pull request merged**
