### PR TITLE
Upgrade to Gradle 5.2.1

### PR DESCRIPTION
**Pull request by fzdy1914**
Upgrade to the latest version of Gradle to keep up to date with its
development.

### CODE REVIEW

**Comment by Tejas2805** [comment]
Just want to understand one thing. Any specific reason for not using the latest versions of Gradle and Shadow?

**Comment by fzdy1914** [comment]
> Just want to understand one thing. Any specific reason for not using the latest versions of Gradle and Shadow

You can have a try. I got some previous experience to be sure that this setting is compatible with java 8. If you tried that the latest one also works, we can switch the latest stable version of them.

**Comment by Tejas2805** [comment]
We can update the Shadow version to 5.2.0 but updating the Gradle Version causes errors. So maybe can just use that.

**Comment by fzdy1914** [comment]
> We can update the Shadow version to 5.2.0 but updating the Gradle Version causes errors. So maybe can just use that.

OK, nice finding.

**Comment by fzdy1914** [comment]
@Tejas2805 If you are free, can you help investigate why there is a huge drop in codecov coverage rate?

**Comment by jylee-git** [comment]
No issues from my side when using the specified configs.

**Comment by Tejas2805** [comment]
> @Tejas2805 If you are free, can you help investigate why there is a huge drop in codecov coverage rate?

Sorry, for the late reply. Saw this right now. 

I have figured out the issue. Not sure how to fix it. 

```
JaCoCo plugin now works with the build cache and parallel test execution

... the tasks running with code coverage are configured to delete the execution data just before they starts executing ...
```

Based on this update, looks like we need to use a different file, currently we use the same file, as seen in this [line](https://github.com/reposense/RepoSense/blob/6c59593168fb5df060df95d288b11db14421cb31/build.gradle#L86).

Therefore, need to just split that up.

**Comment by fzdy1914** [comment]
> > @Tejas2805 If you are free, can you help investigate why there is a huge drop in codecov coverage rate?
> 
> Sorry, for the late reply. Saw this right now.
> 
> I have figured out the issue. Not sure how to fix it.
> 
> ```
> JaCoCo plugin now works with the build cache and parallel test execution
> 
> ... the tasks running with code coverage are configured to delete the execution data just before they starts executing ...
> ```
> 
> Based on this update, looks like we need to use a different file, currently we use the same file, as seen in this [line](https://github.com/reposense/RepoSense/blob/6c59593168fb5df060df95d288b11db14421cb31/build.gradle#L86).
> 
> Therefore, need to just split that up.
> 
> **UPDATE**: It's been fixed and is working in #1300

OK， close this

**Pull request closed without merging**
