### PR TITLE
[#1622] Upgrade highlight.js to version 11

### PR DESCRIPTION
**Pull request by Zhou-Jiahao-1998**
Fixes https://github.com/reposense/RepoSense/issues/1622

Proposed commit message:

```
The highlight.js package used by the frontend is currently
version 10.7.3, which is no longer supported. 

Upgraded highlight.js to 11.4.0 for better compatibility.
```

### CODE REVIEW

**Review by gerhean — APPROVED** [review]
Code-wise LGTM, can you improve your [commit message](http://se-education.org/guides/conventions/github.html) a bit?

**Comment by Zhou-Jiahao-1998** [comment]
@gerhean Alright noted! Is this better now?

**Comment by gerhean** [comment]
> @gerhean Alright noted! Is this better now? On a side note, is it possible to test on your system to double check as I am on MacOS.

Computer OS should have no impact on frontend changes, since it is the browser which runs the JavaScript code.

That being said, I do not see anything wrong when running on Chrome.

**Review by gerhean — APPROVED** [review]
LGTM

**Review by dcshzj — CHANGES_REQUESTED** [review]
We still have a reference to an older version of highlight.js here:

https://github.com/reposense/RepoSense/blob/c4d7690e7b2c3b2626187a2c26ee447d99adf15a/frontend/src/app.vue#L321

Do we need to upgrade this as well?

Also, looking at the dashboard deployment for this PR, it doesn't seem like any of the code is highlighted.

**Comment by gerhean** [comment]
> We still have a reference to an older version of highlight.js here:
> 
> https://github.com/reposense/RepoSense/blob/c4d7690e7b2c3b2626187a2c26ee447d99adf15a/frontend/src/app.vue#L321
> 
> Do we need to upgrade this as well?
> 
> Also, looking at the dashboard deployment for this PR, it doesn't seem like any of the code is highlighted.

Thanks for catching this, by right nothing should be imported `cdn.jsdelivr.net`, and should instead be installed and imported from `node_modules` folder. (This should be fixed in another PR).

In fact, I just realized that highlightjs is broken in the [netlify deployment](https://reposense.netlify.app/) as well, seems like a regression of #1412 which nobody caught unfortunately.

Perhaps this PR should be closed, and a new PR to be opened to fix the regression.

**Comment by Zhou-Jiahao-1998** [comment]
@gerhean In that case, I will close the PR.

**Pull request closed without merging**
