### PR TITLE
[#720] Set command-click to activate zoom-in feature for macOS devices

### LINKED ISSUE #720: Unable to activate zoom-in feature for macOS device
I have tried using `control-click`, `command-click`, and other combinations but am still unable to activate the zoom-in feature.

### PR DESCRIPTION
**Pull request by jamessspanggg**
Fixes #720 

```
Ctrl + mouse left-click is the default combination to activate the
zoom-in feature for all environment.

However, as the combination is registered as a right-click in macOS
environment, users of macOS devices wouldn't be able to activate the
corresponding feature.

Let's modify the zoom-in controls to allow command click for macOS 
devices and control click for all other devices.
```

### CODE REVIEW

**Comment by jamessspanggg** [comment]
> Please make sure the PR has passed all the CI before requesting a review.

Noted. Will take note from now onwards.

**Comment by jamessspanggg** [comment]
> LGTM, but remember to add this in UG.

Noted. Will update the UG along with resolving #727 when PR #696 has been merged to avoid merge conflicts.

**Comment by jamessspanggg** [comment]
> Noted. Is it okay if I update the UG along with resolving #727 when PR #696 has been merged to avoid merge conflicts?

@fzdy1914

**Comment by fzdy1914** [comment]
It is OK for me. Just request an review from me after updating it.

**Comment by jamessspanggg** [comment]
Ready to merge?

**Pull request merged**
