### PR TITLE
[#1539] Fix console error when doing individual merge group

### LINKED ISSUE #1539: Console error when doing individual merge group
**Tell us about your environment**

https://dashboard-1530-pr-reposense-reposense.surge.sh/?search=&sort=groupTitle&sortWithin=title&since=2017-10-09&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=false

**Please include the steps to reproduce the bug.**

1. Open console
2. Click this:
image

**What was expected to happen?**
No console error.

**What actually happened? Please include a screenshot of the output.**
Console error.
UI wise everything seems ok.

### PR DESCRIPTION
**Pull request by yhtMinceraft1010X**
Fixes #1539 

Proposed commit message:
```
Passing slice.repoId to getBaseLink() after merging groups causes the
console error to happen. This is due to
window.REPOS[slice.repoId].location being undefined.

Let's put repoId in the commit itself and rename the "slice" argument
to "commit". This should give a valid commit.repoId since getLink()
for v-ramp takes in a commit. This would also allow the usage of
commit.repoId for separate users instead of user.repoId.
```

### CODE REVIEW

**Comment by gerhean** [comment]
Suspicious point: The inside and outside the `if` statement is the same.

I suspect that by changing the `user.repo` to not match with the slice repo, the link will fail. 

To check, group by `Author`, and set sort within groups by to `↓ title`

Go to author `eugenepeh (eugenepeh)`
image

Check that pressing the bottom pink triangle brings you to the merge commit link

Click merge group, and press the bottom pink triangle again, it brings you to 404 page.

This worked in previous version as `getLink` did not overwrite the original link due to crashing.

I checked whether this problem exists if you refresh the page but it does not.

**Comment by yhtMinceraft1010X** [comment]
After looking through this, I decided to put the `repoId` inside the `commitResults` object for the commit.
Whenever a group gets merged for group by `Author`, `getBaseLink` will use the `repoId` which the commit is assigned to.

**Comment by gerhean** [comment]
Looks ok, but can you verify how `repoId` is assigned when the page is refreshed? Maybe there is a function to reuse?

**Comment by gerhean** [comment]
Since you have assigned the `repoId` to each slice, does it make sense to remove the if statement here?

 https://github.com/reposense/RepoSense/blob/65052fc2039a5d88bbd023b5b8440af862aa8053/frontend/src/components/v-ramp.vue#L48-L54

**Comment by gerhean** [comment]
Commit message should be edited to reflect change

**Comment by yhtMinceraft1010X** [comment]
> Commit message should be edited to reflect change

I've made the edit to the proposed commit message.

**Review by gerhean — APPROVED** [review]
LGTM

**Review by fzdy1914 — APPROVED** [review]

**Pull request merged**
