### PR TITLE
[#1109] Config.json: include active author and pug file format

### LINKED ISSUE #1109: Add/Replace recent active authors of RepoSense in default configuration
As title.

@jamessspanggg Can be a good candidate.

Reason: the authors in the preview are quite old from now and their commits will not be updated anymore. 

Introduce a recent active author may reveal potential bugs.

@eugenepeh @damithc Your idea?

### PR DESCRIPTION
**Pull request by jamessspanggg**
Fixes #1109 

```
The default configuration consists of authors that are no longer
active in committing code to RepoSense. The jade file format is
no longer used in RepoSense as it is replaced by pug file format.

Let's add a recent active author, as it may reveal potential bugs.
Let's replace jade to pug file format as well.
```

### CODE REVIEW

**Comment by jamessspanggg** [comment]
@fzdy1914 is one active author enough?

**Comment by Tejas2805** [comment]
I think replacing is better. As loading will otherwise take more time?

**Comment by fzdy1914** [comment]
One should be enough and you may delete `Aditya`'s configuration.

**Comment by jamessspanggg** [comment]
@fzdy1914 note that I also added `pug` file format as we no longer are using `jade`.

**Comment by Tejas2805** [comment]
Can remove jade then?

**Comment by jamessspanggg** [comment]
> Can remove jade then?

done

**Comment by Tejas2805** [comment]
@jylee-git Can we get one final review from you. Thank you for your time

**Pull request merged**
