### PR TITLE
[#944] Implement authorship analysis

### LINKED ISSUE #944: Improve code authorship attribution
Currently in the code panel, an author is credited for lines of code that was last modified them. However, another author might have written the line initially and the current author (author who last modified the line) might have only made a slight modification to the line. In such a case, the current author gets credited for work that is not entirely done by them.

Proposed solution:
Assign partial or full credit of a line to the current author based on whether they introduced the line or someone else introduced the line and they only made a slight modification to it. This is done by checking the ancestor line (previous version of the line) to see how similar it is to the line. Users add a command line flag to indicate if they want this feature to be turned on - it is turned off by default.

For a given line **l** and author **a** who last modified the line, we can assign credit to author **a** using the following steps:
1) Check the commit in which author **a** modified line **l**
2) Get the diffs of the commit and find the hunk which line **l** belongs to
3) Go through all the deleted lines in the hunk and compare them with line **l** to see how similar they are (using Levenshtein string distance metric)
4) If we do not find a deleted line with high similarity with line **l**, we give author **a** full credit. If we find such a deleted line, we find out the author of the deleted line.
5) If the author of the deleted line is not author **a**, we give partial credit to author **a**. If the author of the deleted line is author **a**, we set line **l** as the deleted line and repeat from step 1.

After we assign partial or full credit to the author, we can display the results in the code panel by using a darker shade of green to highlight code with full credit.

Picture1

### PR DESCRIPTION
**Pull request by SkyBlaise99**
Fixes #944 

### Proposed commit message

```
A line is credited to the author who last modified it.

Another author might have written the line initially and the current
author only modified it slightly. In such a case, the current author
gets credited for work that is not entirely done by them.

Lets analyze how similar a line is to its ancestor line (previous
version of the line) and give partial or full credit to the author
based on the analysis. This feature is turned off by default as
it takes quite long to run.
```

### Other information

There is a small change as compared to the initial idea. I have set the default value for `isFullCredit` to `true` in [LineInfo.java](https://github.com/SkyBlaise99/RepoSense/blob/944-analyze-authorship/src/main/java/reposense/authorship/model/LineInfo.java#L25). When the feature is turned off, the default behavior should be that the last author is given full credit.

Sample preview:

image

### CODE REVIEW

**Comment by damithc** [comment]
@SkyBlaise99 How is the performance affected? For example, for https://github.com/nus-cs2103-AY2223S2/tp-dashboard
You can compare locally and also on GitHub Actions environment, which has limitations on minutes and memory.

**Comment by SkyBlaise99** [comment]
Here's a comparison:

| |Local | GitHub Actions |
| -------- |  -------- | ------- |
| Normal | 14 min | 4 min |
| With Authorship Analysis | tbc | tbc |

**Comment by damithc** [comment]
Thanks for the performance data, @SkyBlaise99 
Given this huge disparity of performance, we might not merge this to the master branch yet, until we are sure there is a solution that has acceptable performance tradeoffs. In the meantime, we can merge this to a separate feature branch and you can this code in a separate _long-lived feature branch_ and you can PR against that. 

@reposense/active-developers can you guys set up such a long-lived feature branch and merge this code to that branch?

**Comment by damithc** [comment]
Others, you are welcome and encouraged to give feedback on this work, but there is no need for a thorough code review until we are ready to merge this work to the master branch.

**Comment by chan-j-d** [comment]
Hi @SkyBlaise99, I've created a branch on the repo for you to work with at https://github.com/reposense/RepoSense/tree/944-analyze-authorship. Do let me know if you need any additional support for it

**Comment by SkyBlaise99** [comment]
@damithc I explored around with caching and the performance it now around 1h. I'll continue to try and see if it can be further reduced.

@chan-j-d thanks. So for any future works, I'll just push to the branch instead? Then this PR can be closed first?

**Comment by ckcherry23** [comment]
@SkyBlaise99 For any future work, I think the recommended workflow is to create PRs with `944-analyze-authorship` as the target branch instead of the `master` branch. The team may also give some preliminary feedback for each PR but we don't need a thorough code review to merge to this new branch.

**Comment by SkyBlaise99** [comment]
@ckcherry23 noted with thanks. Then in that case should I close this PR since it is already on `944-analyze-authorship` branch?

**Comment by gok99** [comment]
@SkyBlaise99 you could mark it as draft - it would be a long-term PR that you can merge into, and mark back as open when ready

**Comment by chan-j-d** [comment]
@SkyBlaise99 Yep, closing this PR sounds like a good idea. If you need some comments from us, could PR to the other branch instead and ping us.

**Comment by SkyBlaise99** [comment]
Okay, then closing this PR and further improvements will be made towards [this branch](https://github.com/reposense/RepoSense/tree/944-analyze-authorship) instead.

**Pull request closed without merging**
